enum StringsFeatureEn {
    static let values: [L10nKey: String] = [
        // Feed
        .feedTitle: "Feeds",
        .feedLoading: "Loading your feed...",
        .feedEmptyTitle: "No Posts Yet",
        .feedEmptyMessage: "Share a moment with your friends to get started!",
        .feedEmptyAction: "Take a Photo",
        .feedPhotoAlbumAccessibility: "Photo album",
        .feedAlbumTitle: "Collection",
        .feedAlbumLoading: "Loading album...",
        .feedAlbumEmptyTitle: "No photos yet",
        .feedAlbumEmptyMessage: "Photos from your posts will appear here.",

        // Streak
        .feedStreakTitle: "Streak",
        .feedStreakCurrentStreak: "Current streak",
        .feedStreakDays: "days in a row",
        .feedStreakEmptyDay: "No photo",
        .feedStreakNoPhotosToday: "Post a photo today to keep your streak!",
        .feedStreakQuoteZero: "Zero-day streak — your camera requested paid leave.",
        .feedStreakQuoteGrowing: "Just warming up. Don't let your fridge out-streak you.",
        .feedStreakQuoteSolid: "Solid streak — the algorithm still hasn't figured you out.",
        .feedStreakQuoteLegend: "True legend. NASA called but you were busy taking photos.",
        .feedStreakLoading: "Loading streak...",
        .feedStreakError: "Failed to load streak",
        .feedFilterTitle: "Filters",
        .feedFilterNoFriends: "You have no friends yet",
        .feedFilterFriendsNotFound: "No friends found",
        .feedFilterByFriends: "Filter by friends",
        .feedFilterNoGroups: "You haven't joined any groups",
        .feedFilterByGroups: "Filter by groups",
        .feedPostCommentsTitle: "Comments",
        .feedPostCommentsHeader: "Comments",
        .feedPostCommentsEmpty: "No comments yet. Be the first!",
        .feedPostCommentsLoadMore: "Load more comments",
        .feedPostViewAllComments: "View all %d comments",
        .feedPostWriteComment: "Write a comment...",
        .feedCompanionsEmpty: "No companions found",
        .feedCompanionsTitle: "Out with (%d)",
        .feedCompanionsSummary: "Out with %@",
        .feedCheckInAt: "Checked in at %@",
        .feedViewersTitle: "Viewed by (%d)",
        .feedBillSplitTitle: "Bill split",
        .feedBillRemindAll: "Remind all (%d)",
        .feedBillRemindTitle: "Reminder",
        .feedBillRemindAllTitle: "Remind all",
        .feedBillRemindAllMessage: "Send a reminder to %d people who haven't paid",
        .feedBillPaidAccessibility: "Paid",
        .feedBillRemindUserAccessibility: "Remind %@",
        .feedReactionsTitle: "Reactions",
        .feedReactionsCount: "%d reactions",
        .feedReactionsMore: "+%d others reacted",
        .feedCreateTitle: "New post",
        .feedCreatePosting: "Posting...",
        .feedCreateAddMedia: "Add media",
        .feedCreateMediaLimit: "Up to 5 photos and 3 videos",
        .feedCreateCaption: "Caption",
        .feedCreateTagFriends: "Tag friends",
        .feedCreateTagFriendsHint: "Tag friends to split the bill with others.",
        .feedCreateFriendsNotFound: "No friends found",
        .feedCreateLocation: "Location",
        .feedCreateTotalAmount: "Total amount",
        .feedCreateCurrencySymbol: "₫",
        .feedMentionSuggestions: "Friend suggestions",
        .feedEmojiPickerTitle: "Choose emoji",
        .feedEmojiPickerQuickBarTitle: "Quick bar",
        .feedEmojiPickerQuickBarHint: "Tap a slot, then pick an emoji below to assign. Tap an emoji to react instantly.",
        .feedEmojiPickerAllTitle: "All emojis",
        .feedEmojiPickerHint: "The iPhone emoji keyboard appears when you tap the field above.",
        .feedProfileMessage: "Message",
        .feedProfileAddFriend: "Add friend",
        .profileLoading: "Loading profile…",
        .profileRetry: "Retry",
        .profileStatFriends: "Friends",
        .profileStatPosts: "Posts",
        .profileStatGroups: "Groups",
        .profilePaymentManage: "Receive money",
        .profilePaymentTitle: "Payment QR",
        .profilePaymentQrSection: "QR code image",
        .profilePaymentBankSection: "Bank account",
        .profilePaymentAccountName: "Account holder name",
        .profilePaymentAccountNumber: "Account number",
        .profilePaymentBankName: "Bank",
        .profilePaymentSave: "Save",
        .profilePaymentDelete: "Remove payment info",
        .profilePaymentDeleteConfirm: "Remove your payment QR and bank details?",
        .profilePaymentUploadQr: "Upload QR image",
        .profilePaymentFriendSection: "Receive money",
        .profilePaymentEmptySelf: "No payment info yet. Tap Receive money to add your QR or bank details.",
        .profilePaymentEmptyFriend: "This friend hasn't added payment info yet.",

        // Friends
        .friendsTitle: "Friends",
        .friendsTabFriends: "Friends",
        .friendsTabGroups: "Groups",
        .friendsIncomingRequests: "Friend requests (%d)",
        .friendsOutgoingRequests: "Sent requests (%d)",
        .friendsOutgoingRequestsPlain: "Sent requests",
        .friendsBlockedUsers: "Blocked users",
        .friendsAddFriendTitle: "Add friend",
        .friendsUsername: "Username",
        .friendsMessageOptional: "Message (optional)",
        .friendsJoinGroupTitle: "Join group",
        .friendsGroupInviteCode: "Group invite code",
        .friendsJoinGroupAction: "Join group",
        .friendsScanGroupQR: "Scan QR code",
        .friendsRelationFriend: "Friends",
        .friendsRelationSent: "Sent",
        .friendsAccept: "Accept",
        .friendsAddFriendAction: "Add friend",
        .friendsReject: "Reject",
        .friendsCancel: "Cancel",
        .friendsClose: "Close",
        .friendsMyQRTitle: "My QR code",
        .friendsMyQRHint: "Friends scan this code to send you a friend request on Splick.",
        .friendsMyQRRefresh: "Refresh code",
        .friendsMyQRShare: "Share code",
        .friendsMyQRGenerating: "Generating QR code...",
        .friendsMyQRFailed: "Could not generate QR code",
        .friendsMyQRVersion: "Code version %d",
        .friendsMyQRPreviewTitle: "My QR code",
        .friendsMyQRPreviewHint: "Tap to enlarge or share",
        .friendsScanQRAddFriend: "Scan QR code",
        .friendsScanQRJoinGroup: "Scan group code",
        .friendsScanSimulatorHint: "The Simulator has no camera. Paste a QR payload below or use a real device to scan.",
        .friendsScanManualHint: "Or paste a code manually",
        .friendsScanUseCode: "Use this code",
        .friendsIncomingTitle: "Friend requests",
        .friendsIncomingLoading: "Loading requests...",
        .friendsIncomingEmptyTitle: "No pending requests",
        .friendsIncomingEmptyMessage: "When someone sends you a friend request, it will appear here.",
        .friendsOutgoingTitle: "Sent requests",
        .friendsOutgoingLoading: "Loading sent requests...",
        .friendsOutgoingEmptyTitle: "No sent requests",
        .friendsOutgoingEmptyMessage: "Friend requests you send will appear here until they accept or you cancel.",
        .friendsBlockedTitle: "Blocked users",
        .friendsBlockedLoading: "Loading blocked users...",
        .friendsBlockedEmptyTitle: "No blocked users",
        .friendsBlockedEmptyMessage: "Users you block will appear here. You can unblock them anytime.",
        .friendsUnblock: "Unblock",
        .friendsSetNickname: "Set nickname",
        .friendsRemoveFriend: "Remove friend",
        .friendsBlockUser: "Block user",
        .friendsNicknameTitle: "Nickname",
        .friendsNicknamePlaceholder: "Nickname (only you see this)",
        .friendsRemoveFriendConfirmTitle: "Remove friend?",
        .friendsRemoveFriendConfirmAction: "Remove friend",
        .friendsBlockConfirmTitle: "Block this user?",
        .friendsBlockConfirmAction: "Block",
        .friendsGroupPending: "Pending approval (%d)",
        .friendsGroupMembers: "Members (%d)",
        .friendsGroupMemberCount: "%d members",
        .friendsGroupInviteCodeLabel: "Invite code: %@",

        // Expense
        .expenseTitle: "Expenses",
        .expenseLoading: "Loading expenses...",
        .expenseEmptyTitle: "No Expenses",
        .expenseEmptyMessage: "Create your first shared expense to start splitting bills.",
        .expenseEmptyAction: "Add Expense",
        .expenseFilteredEmptyTitle: "No matching expenses",
        .expenseFilteredEmptyMessage: "Try changing filters or clearing them.",
        .expenseYouAreOwed: "You are owed",
        .expenseYouOwe: "You owe",
        .expensePaidBy: "Paid by %@",
        .expenseCreatedAt: "Created %@",
        .expenseSettledAt: "Settled %@",
        .expenseStatusPending: "Pending",
        .expenseStatusPartial: "Partial",
        .expenseStatusSettled: "Settled",
        .expenseFilterSearchCaption: "Search by caption",
        .expenseFilterMore: "More filters",
        .expenseFilterClear: "Clear filters",
        .expenseFilterStatus: "Status",
        .expenseFilterUser: "User",
        .expenseFilterSearchUser: "Search user",
        .expenseFilterNoUsers: "No users found",
        .expenseFilterDateRange: "Date range",
        .expenseFilterFrom: "From",
        .expenseFilterTo: "To",
        .expenseFilterAnyTime: "Any time",
        .expenseFilterFromDate: "From date",
        .expenseFilterToDate: "To date",
        .expenseDebtAll: "All",
        .expenseDebtOwe: "I owe",
        .expenseDebtOwed: "Owed to me",
        .expenseCreateTitle: "New Expense",
        .expenseCreateHowMuch: "How much?",
        .expenseCreateDescription: "What's this for?",
        .expenseCreateCategory: "Category",
        .expenseCreateSplitType: "Split Type",
        .expenseCreateAction: "Create Expense",
        .expenseSplitEqual: "Split Equally",
        .expenseSplitExact: "Exact Amounts",
        .expenseSplitPercentage: "By Percentage",

        // Notification
        .notificationTitle: "Notifications",
        .notificationLoading: "Loading notifications...",
        .notificationEmptyTitle: "No Notifications",
        .notificationEmptyMessage: "You're all caught up! Notifications will appear here.",
        .notificationReadAll: "Read All",
        .notificationInboxTitle: "Inbox",
        .notificationInboxEmpty: "No notifications yet",
        .notificationBellAccessibility: "Notifications",

        // Tab
        .tabMessages: "Messages",

        // Messaging
        .messagingTitle: "Messages",
        .messagingLoading: "Loading messages...",
        .messagingEmptyTitle: "No Conversations",
        .messagingEmptyMessage: "Search for a friend above to start chatting.",
        .messagingNewConversation: "New Message",
        .messagingInputPlaceholder: "Message...",
        .messagingSend: "Send",
        .messagingYou: "You",
        .messagingChatLoading: "Loading messages...",
        .messagingChatEmptyTitle: "No messages yet",
        .messagingChatEmptyMessage: "Say hello!",
        .messagingSelectFriend: "Select a friend to message",
        .messagingSearchPlaceholder: "Search friends",
        .messagingSearchLoading: "Searching...",
        .messagingSearchEmptyTitle: "No friends found",
        .messagingSearchEmptyMessage: "Try another name or username.",
        .messagingStartConversationError: "Unable to start conversation",
        .messagingBellAccessibility: "Notifications",
        .messagingMessageButton: "Message",

        // Common extras
        .commonClose: "Close",
        .commonOK: "OK",
        .commonSave: "Save",
        .commonError: "Error",
        .commonSuccess: "Success",
        .commonOr: "or",
    ]
}
