enum StringsVi {
    static let values: [L10nKey: String] = [
        .commonDone: "Xong",
        .commonCancel: "Huỷ",
        .commonTryAgain: "Thử lại",
        .commonReferenceId: "Mã tham chiếu",

        .tabFeed: "Bảng tin",
        .tabExpenses: "Chi tiêu",
        .tabFriends: "Bạn bè",
        .tabCamera: "Máy ảnh",
        .tabNotifications: "Thông báo",

        .profileTitle: "Hồ sơ",
        .profileEdit: "Sửa hồ sơ",
        .profileChangePassword: "Đổi mật khẩu",
        .profileDevicesSessions: "Thiết bị & phiên đăng nhập",
        .profileConnectedAccounts: "Tài khoản liên kết",
        .profileDeactivateDelete: "Vô hiệu hoá hoặc xoá tài khoản",
        .profileSignOut: "Đăng xuất",
        .profileLanguage: "Ngôn ngữ",
        .profileLanguageVi: "Tiếng Việt",
        .profileLanguageEn: "English",
        .profileRefreshFailed: "Không thể làm mới hồ sơ.",
        .profileSettingsAccessibility: "Cài đặt hồ sơ",

        .authWelcomeTitle: "Chào mừng đến Splick",
        .authWelcomeSubtitle: "Quản lý chi tiêu và kết nối bạn bè",
        .authEmail: "Email",
        .authPassword: "Mật khẩu",
        .authSignIn: "Đăng nhập",
        .authSendCode: "Gửi mã",
        .authSignUp: "Đăng ký",
        .authForgotPassword: "Quên mật khẩu?",
        .authContinueWithGoogle: "Tiếp tục với Google",
        .authVerifyPhoneTitle: "Xác minh số điện thoại",
        .authVerifyPhoneSubtitle: "Nhập mã đã gửi tới %@",
        .authNoAccount: "Chưa có tài khoản?",
        .authHaveAccount: "Đã có tài khoản?",

        .errorNetworkNoConnection: "Không có kết nối mạng. Vui lòng kiểm tra lại.",
        .errorNetworkServerUnreachable: "Không thể kết nối máy chủ. Vui lòng thử lại sau.",
        .errorNetworkServerUnreachableDebug: "Không thể kết nối API. Trong Terminal, chạy: make -C splick-mobile-ios stubs",
        .errorNetworkTimeout: "Yêu cầu quá thời gian. Vui lòng thử lại.",
        .errorNetworkServer: "Đã xảy ra lỗi. Vui lòng thử lại sau.",
        .errorNetworkDecoding: "Không thể xử lý phản hồi từ máy chủ.",
        .errorNetworkInvalidURL: "Yêu cầu không hợp lệ.",
        .errorNetworkUnauthorized: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
        .errorNetworkForbidden: "Bạn không có quyền thực hiện thao tác này.",
        .errorNetworkNotFound: "Không tìm thấy tài nguyên yêu cầu.",
        .errorNetworkRateLimited: "Quá nhiều yêu cầu. Vui lòng đợi một lát.",
        .errorNetworkUnexpected: "Đã xảy ra lỗi không mong muốn.",

        .errorAuthInvalidCredentials: "Email hoặc mật khẩu không đúng.",
        .errorAuthTokenExpired: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
        .errorAuthRefreshFailed: "Không thể làm mới phiên đăng nhập.",
        .errorAuthAccountLocked: "Tài khoản của bạn đã bị khoá.",
        .errorAuthAccountInactive: "Tài khoản này đã bị vô hiệu hoá.",
        .errorAuthCannotUnlinkLast: "Giữ ít nhất một phương thức đăng nhập trên tài khoản.",
        .errorAuthGoogleAlreadyLinked: "Tài khoản Google này đã liên kết với người dùng khác.",
        .errorAuthProviderAlreadyLinked: "Phương thức đăng nhập này đã được liên kết.",
        .errorAuthOtpRateLimited: "Quá nhiều lần xác minh. Vui lòng đợi vài phút trước khi yêu cầu mã mới.",
        .errorAuthRegistrationFailed: "Đăng ký thất bại: %@",
        .errorAuthEmailExists: "Email này đã có tài khoản. Hãy đăng nhập.",
        .errorAuthEmailUseGoogle: "Tài khoản này dùng Google. Chọn Tiếp tục với Google ở màn hình đăng nhập.",
        .errorAuthPhoneExists: "Số điện thoại này đã có tài khoản. Hãy đăng nhập bằng SMS.",
        .errorAuthUsernameExists: "Tên người dùng đã được sử dụng. Chọn tên khác.",
        .errorAuthInvalidOtpDefault: "Mã xác minh không hợp lệ hoặc đã hết hạn.",
        .errorAuthInvalidOtpPrompt: "Nhập mã 6 chữ số từ email của bạn.",
        .errorAuthEmailDeliveryFailed: "Không thể gửi email. Vui lòng thử lại sau.",
    ]
}
