enum StringsEn {
    static let values: [L10nKey: String] = [
        .commonDone: "Done",
        .commonCancel: "Cancel",
        .commonClear: "Clear",
        .commonTryAgain: "Try Again",
        .commonReferenceId: "Reference ID",

        .tabFeed: "Feeds",
        .tabExpenses: "Expenses",
        .tabFriends: "Friends",
        .tabCamera: "Camera",
        .tabNotifications: "Notifications",

        .profileTitle: "Profile",
        .profileEdit: "Edit profile",
        .profileChangePassword: "Change password",
        .profileDevicesSessions: "Devices & sessions",
        .profileConnectedAccounts: "Connected accounts",
        .profileDeactivateDelete: "Deactivate or delete account",
        .profileSignOut: "Sign Out",
        .profileLanguage: "Language",
        .profileLanguageVi: "Tiếng Việt",
        .profileLanguageEn: "English",
        .profileRefreshFailed: "Could not refresh profile.",
        .profileSettingsAccessibility: "Profile settings",

        .authWelcomeTitle: "Welcome to Splick",
        .authWelcomeSubtitle: "Manage expenses and connect with friends",
        .authEmail: "Email",
        .authPassword: "Password",
        .authSignIn: "Sign In",
        .authSendCode: "Send code",
        .authSignUp: "Sign Up",
        .authForgotPassword: "Forgot password?",
        .authContinueWithGoogle: "Continue with Google",
        .authVerifyPhoneTitle: "Verify your phone",
        .authVerifyPhoneSubtitle: "Enter the code sent to %@",
        .authNoAccount: "Don't have an account?",
        .authHaveAccount: "Already have an account?",

        .errorNetworkNoConnection: "No internet connection. Please check your network.",
        .errorNetworkServerUnreachable: "Cannot reach the server. Please try again later.",
        .errorNetworkServerUnreachableDebug: "Cannot reach the API server. In Terminal, run: make -C splick-mobile-ios stubs",
        .errorNetworkTimeout: "Request timed out. Please try again.",
        .errorNetworkServer: "Something went wrong. Please try again later.",
        .errorNetworkDecoding: "Failed to process server response.",
        .errorNetworkInvalidURL: "Invalid request.",
        .errorNetworkUnauthorized: "Session expired. Please log in again.",
        .errorNetworkForbidden: "You don't have permission to perform this action.",
        .errorNetworkNotFound: "The requested resource was not found.",
        .errorNetworkRateLimited: "Too many requests. Please wait a moment.",
        .errorNetworkUnexpected: "An unexpected error occurred.",

        .errorAuthInvalidCredentials: "Invalid email or password.",
        .errorAuthTokenExpired: "Your session has expired. Please log in again.",
        .errorAuthRefreshFailed: "Failed to refresh session.",
        .errorAuthAccountLocked: "Your account has been locked.",
        .errorAuthAccountInactive: "This account has been deactivated.",
        .errorAuthCannotUnlinkLast: "Keep at least one sign-in method on your account.",
        .errorAuthGoogleAlreadyLinked: "This Google account is already linked to another user.",
        .errorAuthProviderAlreadyLinked: "This sign-in method is already connected.",
        .errorAuthOtpRateLimited: "Too many verification attempts. Please wait a few minutes before requesting a new code.",
        .errorAuthRegistrationFailed: "Registration failed: %@",
        .errorAuthEmailExists: "An account with this email already exists. Sign in instead.",
        .errorAuthEmailUseGoogle: "This account uses Google sign-in. Tap Continue with Google on the login screen.",
        .errorAuthPhoneExists: "This phone number already has an account. Sign in with SMS instead.",
        .errorAuthUsernameExists: "That username is taken. Choose another.",
        .errorAuthInvalidOtpDefault: "Invalid or expired verification code.",
        .errorAuthInvalidOtpPrompt: "Enter the 6-digit code from your email.",
        .errorAuthEmailDeliveryFailed: "Unable to send email. Please try again later.",
    ]
}
