enum StringsVi {
    static let values: [L10nKey: String] = [
        .commonDone: "Xong",
        .commonCancel: "Huỷ",
        .commonClear: "Xoá",
        .commonTryAgain: "Thử lại xem nào",
        .commonErrorTitle: "Ối dồi ôi!",
        .commonReferenceId: "Mã tham chiếu",
        .commonBack: "Quay lại",
        .commonClose: "Đóng",
        .commonOK: "OK",
        .commonError: "Lỗi",

        .tabFeed: "Bảng tin",
        .tabExpenses: "Chi tiêu",
        .tabFriends: "Bạn bè",
        .tabCamera: "Máy ảnh",
        .tabNotifications: "Thông báo",

        .profileTitle: "Hồ sơ",
        .profileEdit: "Sửa hồ sơ",
        .profileChangePassword: "Đổi mật khẩu",
        .profileDevicesSessions: "Thiết bị & phiên đăng nhập",
        .sessionsTitle: "Thiết bị & phiên đăng nhập",
        .sessionsSubtitle: "Các thiết bị đang đăng nhập vào tài khoản của bạn. Gỡ thiết bị nào bạn không nhận ra.",
        .sessionsThisDevice: "Thiết bị này",
        .sessionsSignOut: "Đăng xuất",
        .sessionsSignOutAll: "Đăng xuất tất cả thiết bị khác",
        .sessionsSignedIn: "Đăng nhập",
        .sessionsExpires: "Hết hạn",
        .sessionsLocation: "Vị trí",
        .sessionsUnknownLocation: "Không có thông tin vị trí",
        .sessionsLoadFailed: "Chưa tải được danh sách thiết bị.",
        .sessionsRevokeFailed: "Chưa đăng xuất được thiết bị đó.",
        .sessionsRevokeAllFailed: "Chưa đăng xuất được tất cả thiết bị.",
        .profileConnectedAccounts: "Tài khoản liên kết",
        .connectedAccountsProviderGoogle: "Google",
        .connectedAccountsProviderEmail: "Email & mật khẩu",
        .connectedAccountsProviderPhone: "Số điện thoại",
        .connectedAccountsProviderFacebook: "Facebook",
        .connectedAccountsStatusLinked: "Đã liên kết",
        .connectedAccountsStatusNotLinked: "Chưa liên kết",
        .connectedAccountsLinkAccessibility: "Liên kết %@",
        .connectedAccountsUnlinkAccessibility: "Gỡ liên kết %@",
        .connectedAccountsPhoneSheetHint: "Nhập số điện thoại. Chúng tôi sẽ gửi mã xác minh qua SMS.",
        .connectedAccountsPhoneField: "Số điện thoại",
        .connectedAccountsSendCode: "Gửi mã xác minh",
        .connectedAccountsConnectPhone: "Liên kết số điện thoại",
        .connectedAccountsConnectPhoneTitle: "Liên kết số điện thoại",
        .connectedAccountsEmailSheetPhoneOnlyHint: "Thêm email và mật khẩu để đăng nhập không cần SMS.",
        .connectedAccountsEmailSheetHint: "Đặt mật khẩu cho %@. Chúng tôi sẽ gửi mã xác minh qua email.",
        .connectedAccountsEmailField: "Email",
        .connectedAccountsPasswordField: "Mật khẩu",
        .connectedAccountsConfirmPasswordField: "Xác nhận mật khẩu",
        .connectedAccountsConnectEmail: "Liên kết email",
        .connectedAccountsConnectEmailTitle: "Liên kết email",
        .connectedAccountsVerifyWith: "Xác minh bằng",
        .connectedAccountsVerifyPassword: "Mật khẩu",
        .connectedAccountsVerifyEmailCode: "Mã email",
        .connectedAccountsSendEmailCode: "Gửi mã qua email",
        .connectedAccountsUnlinkGoogle: "Gỡ liên kết Google",
        .connectedAccountsUnlinkGoogleTitle: "Gỡ liên kết Google",
        .connectedAccountsLoadFailed: "Không thể tải tài khoản liên kết.",
        .connectedAccountsGoogleUnavailable: "Google Sign-In không khả dụng trên thiết bị này.",
        .connectedAccountsGoogleLinked: "Đã liên kết tài khoản Google.",
        .connectedAccountsGoogleLinkFailed: "Không thể liên kết Google.",
        .connectedAccountsGoogleUnlinked: "Đã gỡ liên kết Google.",
        .connectedAccountsUnlinkFailed: "Không thể gỡ liên kết Google.",
        .connectedAccountsPhoneRequired: "Nhập số điện thoại.",
        .connectedAccountsCodeSentPhone: "Đã gửi mã tới %@.",
        .connectedAccountsSendCodeFailed: "Không thể gửi mã xác minh.",
        .connectedAccountsPhoneLinked: "Đã liên kết số điện thoại.",
        .connectedAccountsPhoneLinkFailed: "Không thể liên kết số điện thoại.",
        .connectedAccountsEmailRequired: "Nhập địa chỉ email.",
        .connectedAccountsEmailLinked: "Đã liên kết email và mật khẩu.",
        .connectedAccountsEmailLinkFailed: "Không thể liên kết email.",
        .connectedAccountsPasswordTooShort: "Mật khẩu phải có ít nhất %d ký tự.",
        .connectedAccountsUnlinkGoogleHint: "Xác minh danh tính trước khi gỡ liên kết Google khỏi tài khoản này.",
        .profileDeactivateDelete: "Vô hiệu hoá hoặc xoá tài khoản",
        .profileSignOut: "Đăng xuất",
        .profileLanguage: "Ngôn ngữ",
        .profileLanguageVi: "Tiếng Việt",
        .profileLanguageEn: "English",
        .profileRefreshFailed: "Không thể làm mới hồ sơ.",
        .profileSettingsAccessibility: "Cài đặt hồ sơ",
        .profileAvatarView: "Xem avatar",
        .profileAvatarEdit: "Thay đổi avatar",
        .profileAvatarDelete: "Dùng avatar mặc định",
        .profileEditDisplayName: "Sửa tên hiển thị",
        .profileGroupAccount: "Tài khoản",
        .profileGroupPersonal: "Hồ sơ cá nhân",
        .profileGroupApp: "Ứng dụng",
        .profileQrReceive: "QR nhận tiền",
        .profileCopyInviteLink: "Chia sẻ link mời",
        .profileBirthday: "Ngày sinh",
        .profileBirthdayAgeError: "Bạn phải từ 13 tuổi trở lên",
        .profileChangeUsername: "Đổi username",
        .profileUsernameTooShort: "Username phải có ít nhất 3 ký tự",
        .profileUsernameTooLong: "Username quá dài",
        .profileUsernameInvalid: "Chỉ dùng chữ, số, _ và .",
        .profileUsernameChecking: "Đang kiểm tra…",
        .profileNotifications: "Thông báo",
        .profileTheme: "Theme",
        .profileAppIcon: "Icon ứng dụng",
        .profileWidget: "Widget",
        .profileGroupAbout: "Giới thiệu",
        .profileShareSplick: "Chia sẻ Splick",
        .profileShareSplickMessage: "Tham gia Splick — mạng xã hội và quản lý chi tiêu chung.",
        .profileRateSplick: "Đánh giá Splick",
        .profileTermsOfService: "Điều khoản dịch vụ",
        .profilePrivacyPolicy: "Chính sách riêng tư",
        .profileSupport: "Hỗ trợ",
        .legalTermsTitle: "Điều khoản dịch vụ",
        .legalPrivacyTitle: "Chính sách quyền riêng tư",
        .legalConsentPrefix: "Khi đăng ký, bạn đồng ý với",
        .legalConsentPrefixSignIn: "Khi đăng nhập, bạn đồng ý với",
        .legalConsentRequiredError: "Vui lòng đồng ý Điều khoản và Chính sách quyền riêng tư",
        .legalOpenInBrowser: "Mở trên trình duyệt",
        .legalDocumentLoadFailed: "Không thể tải tài liệu.",
        .profileDeactivate: "Vô hiệu hoá",
        .profileDeleteAccount: "Xoá tài khoản",
        .accountClosureDeactivateWarning: "Tài khoản sẽ bị vô hiệu hoá và bạn sẽ bị đăng xuất trên mọi thiết bị. Bạn không thể đăng nhập lại cho đến khi được hỗ trợ kích hoạt lại.",
        .accountClosureDeleteWarning: "Hành động này xoá vĩnh viễn hồ sơ và đăng xuất bạn trên mọi thiết bị. Không thể hoàn tác.",
        .accountClosureVerifiedHint: "Đã xác minh danh tính. Bạn có thể hoàn tất thao tác bên dưới.",
        .accountClosureConfirmDeactivate: "Vô hiệu hoá tài khoản của tôi",
        .accountClosureConfirmDelete: "Xoá vĩnh viễn tài khoản của tôi",
        .accountClosureVerifyFirst: "Xác minh mật khẩu trước khi tiếp tục.",
        .accountClosureDeactivateFailed: "Không thể vô hiệu hoá tài khoản.",
        .accountClosureDeleteFailed: "Không thể xoá tài khoản.",
        .profileComingSoon: "Sắp ra mắt",
        .profileComingSoonMessage: "Tính năng này chưa khả dụng.",
        .profileSave: "Lưu",
        .profileAvatarChangeHint: "Chọn ảnh đại diện mới.",

        .changePasswordTitle: "Đổi mật khẩu",
        .createPasswordTitle: "Tạo mật khẩu",
        .createPasswordHint:
            "Tài khoản của bạn chưa có mật khẩu. Xác minh email bằng mã OTP rồi tạo mật khẩu để đăng nhập bằng email.",
        .createPasswordSubmit: "Tạo mật khẩu",
        .createPasswordVerifiedHint: "Đã xác minh. Tạo mật khẩu bên dưới.",
        .changePasswordVerifyWith: "Xác minh bằng",
        .changePasswordMethodCurrent: "Mật khẩu hiện tại",
        .changePasswordMethodEmail: "Mã email",
        .changePasswordCurrentPassword: "Mật khẩu hiện tại",
        .changePasswordNewPassword: "Mật khẩu mới",
        .changePasswordConfirmPassword: "Xác nhận mật khẩu",
        .changePasswordVerifyContinue: "Xác minh và tiếp tục",
        .changePasswordUpdate: "Cập nhật mật khẩu",
        .changePasswordSendCode: "Gửi mã qua email",
        .changePasswordCodeSent: "Đã gửi mã tới %@. Kiểm tra hộp thư của bạn.",
        .changePasswordCurrentRequired: "Vui lòng nhập mật khẩu hiện tại",
        .changePasswordInvalidCurrent: "Mật khẩu hiện tại không đúng",
        .changePasswordPasswordsMismatch: "Mật khẩu không khớp",
        .changePasswordWeakPassword: "Mật khẩu chưa đủ mạnh",
        .changePasswordOtpRequired: "Nhập mã 6 chữ số",
        .changePasswordFailed: "Không thể đổi mật khẩu.",
        .changePasswordVerifiedHint: "Đã xác minh. Nhập mật khẩu mới bên dưới.",
        .changePasswordEmailHint: "Mã xác minh sẽ được gửi tới email tài khoản của bạn.",
        .changePasswordResendCode: "Gửi lại mã",
        .changePasswordResendIn: "Gửi lại sau %d giây",
        .authShowPassword: "Hiện mật khẩu",
        .authHidePassword: "Ẩn mật khẩu",

        .authWelcomeTitle: "Chào mừng đến Splick",
        .authWelcomeSubtitle: "Quản lý chi tiêu và kết nối bạn bè",
        .authEmail: "Email",
        .authIdentifier: "Email hoặc số điện thoại",
        .authPassword: "Mật khẩu",
        .authConfirmPassword: "Xác nhận mật khẩu",
        .authUsername: "Tên người dùng",
        .authDisplayName: "Họ và tên",
        .authDisplayNameOptional: "Họ và tên (không bắt buộc)",
        .authDateOfBirth: "Ngày sinh",
        .authDateOfBirthOptional: "Ngày sinh (không bắt buộc)",
        .authDateOfBirthPlaceholder: "Chọn ngày sinh",
        .authContinue: "Tiếp tục",
        .authSignIn: "Đăng nhập",
        .authSendCode: "Gửi mã",
        .authSignUp: "Đăng ký",
        .authCompleteProfileTitle: "Hoàn tất hồ sơ",
        .authCompleteProfileSubtitle: "Thêm tên, ngày sinh và ảnh đại diện — hoặc bỏ qua và làm sau.",
        .authSetupLater: "Thiết lập sau",
        .authForgotPassword: "Quên mật khẩu?",
        .authContinueWithGoogle: "Tiếp tục với Google",
        .authSignInWithGoogle: "Đăng nhập bằng Google",
        .authSignInWithApple: "Đăng nhập bằng Apple",
        .authSignInWithFacebook: "Đăng nhập bằng Facebook",
        .authSignInFailedGeneric: "Chưa đăng nhập được. Thử lại phát nhé!",
        .authFacebookComingSoon: "Đăng nhập Facebook sẽ sớm có mặt.",
        .authResetPasswordTitle: "Đặt lại mật khẩu",
        .authResetPasswordSubtitle: "Nhập email hoặc số điện thoại của tài khoản. Chúng tôi sẽ gửi mã xác minh.",
        .authForgotPasswordPhoneUnsupported: "Đặt lại mật khẩu qua SĐT chưa hỗ trợ. Hãy dùng email.",
        .authResetCodeRequested: "Nếu email có tài khoản, mã đã được gửi. Kiểm tra hộp thư của bạn.",
        .authValidationInvalidEmail: "Vui lòng nhập email hợp lệ",
        .authValidationInvalidPhone: "Dùng định dạng quốc tế, ví dụ +84901234567",
        .authUseDifferentIdentifier: "Dùng email hoặc SĐT khác",
        .authVerifyPhoneTitle: "Nhập mã xác minh",
        .authVerifyPhoneSubtitle: "Mã 6 chữ số đã được gửi qua SMS tới %@.",
        .authVerifyEmailTitle: "Nhập mã xác minh",
        .authVerifyEmailSubtitle: "Mã 6 chữ số đã được gửi tới %@.",
        .authOtpEmailHint: "Không thấy email? Kiểm tra thư rác hoặc thư quảng cáo.",
        .authOtpPhoneHint: "SMS có thể mất vài phút để tới.",
        .authOtpPhoneHintDebug: "Mã đã gửi qua SMS. Xem log auth-service [MockTwilio].",
        .authOtpSmsCodeRequired: "Nhập mã 6 chữ số từ SMS.",
        .authNoAccount: "Chưa có tài khoản?",
        .authHaveAccount: "Đã có tài khoản?",

        .errorNetworkNoConnection: "Mạng đang hơi 'mất sóng'. Check wifi/4G phát nhé!",
        .errorNetworkServerUnreachable: "Chưa kết nối được server. Đợi tí rồi thử lại nhé!",
        .errorNetworkServerUnreachableDebug: "Không thể kết nối API. Trong Terminal, chạy: make -C splick-mobile-ios stubs",
        .errorNetworkTimeout: "Chờ hơi lâu quá rồi... Thử lại một phát nha!",
        .errorNetworkServer: "Có gì đó hơi sai sai rồi. Thử lại phát nữa nhé!",
        .errorNetworkDecoding: "Data về hơi lạ. Thử lại xem sao nhé!",
        .errorNetworkInvalidURL: "Yêu cầu này chưa ổn. Thử lại giúp mình nha!",
        .errorNetworkUnauthorized: "Phiên đăng nhập hết hạn rồi. Đăng nhập lại nhé!",
        .errorNetworkForbidden: "Bạn chưa có quyền làm việc này đâu nha.",
        .errorMediaForbiddenGroupAvatar: "Chỉ thành viên nhóm mới đổi được ảnh đại diện nhóm.",
        .errorNetworkNotFound: "Không tìm thấy nội dung này rồi.",
        .errorNetworkRateLimited: "Bạn thao tác hơi nhanh đó. Nghỉ một chút rồi thử lại nha!",
        .errorNetworkUnexpected: "Úi, có lỗi rồi. Thử lại giúp mình nha!",

        .errorAuthInvalidCredentials: "Email hoặc mật khẩu không đúng.",
        .errorAuthTokenExpired: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
        .errorAuthRefreshFailed: "Không thể làm mới phiên đăng nhập.",
        .errorAuthAccountLocked: "Tài khoản của bạn đã bị khoá.",
        .errorAuthAccountInactive: "Tài khoản này đã bị vô hiệu hoá.",
        .errorAuthCannotUnlinkLast: "Giữ ít nhất một phương thức đăng nhập trên tài khoản.",
        .errorAuthGoogleAlreadyLinked: "Tài khoản Google này đã liên kết với người dùng khác.",
        .errorAuthProviderAlreadyLinked: "Phương thức đăng nhập này đã được liên kết.",
        .errorAuthOtpRateLimited: "Quá nhiều lần xác minh. Vui lòng đợi vài phút trước khi yêu cầu mã mới.",
        .errorAuthRegistrationFailed: "Đăng ký thất bại: %@",
        .errorAuthEmailExists: "Email này đã có tài khoản. Hãy đăng nhập.",
        .errorAuthEmailUseGoogle: "Tài khoản này dùng Google. Chọn Tiếp tục với Google ở màn hình đăng nhập.",
        .errorAuthPhoneExists: "Số điện thoại này đã có tài khoản. Hãy đăng nhập bằng SMS.",
        .errorAuthUsernameExists: "Tên người dùng đã được sử dụng. Chọn tên khác.",
        .errorAuthInvalidOtpDefault: "Mã xác minh không hợp lệ hoặc đã hết hạn.",
        .errorAuthInvalidOtpPrompt: "Nhập mã 6 chữ số từ email của bạn.",
        .errorAuthEmailDeliveryFailed: "Chưa gửi được email. Thử lại sau nhé!",
        .notificationSettingsStatusSection: "Trạng thái",
        .notificationSettingsActionSection: "Thao tác",
        .notificationSettingsPermissionLabel: "Quyền hệ thống",
        .notificationSettingsDeviceRegistrationLabel: "Đăng ký với backend",
        .notificationSettingsPermissionAllowed: "Đã cho phép",
        .notificationSettingsPermissionDenied: "Đã từ chối",
        .notificationSettingsPermissionNotDetermined: "Chưa yêu cầu",
        .notificationSettingsPermissionUnknown: "Không rõ",
        .notificationSettingsRegistrationSynced: "Đã đồng bộ",
        .notificationSettingsRegistrationPending: "Đang chờ đồng bộ",
        .notificationSettingsRegistrationUnavailable: "Chưa có device token",
        .notificationSettingsEnableAction: "Bật thông báo",
        .notificationSettingsOpenSystemSettingsAction: "Mở cài đặt hệ thống",
        .notificationSettingsDescription: "Splick dùng APNs để gửi thông báo theo thời gian thực. Hãy cho phép thông báo và duy trì phiên đăng nhập hợp lệ để nhận thông báo trên thiết bị này.",
    ]
}
