enum StringsFeatureVi {
    static let values: [L10nKey: String] = [
        // Feed
        .feedTitle: "Tin",
        .feedLoading: "Đang tải bảng tin...",
        .feedEmptyTitle: "Chưa có bài đăng",
        .feedEmptyMessage: "Chia sẻ khoảnh khắc với bạn bè để bắt đầu!",
        .feedEmptyAction: "Chụp ảnh",
        .feedEndReachedTitle: "Hết tin rồi đó",
        .feedEndReachedMessage: "Bạn đã lướt sạch feed. Đi đời thật một chút — tin mới sẽ chờ bạn quay lại.",
        .feedPhotoAlbumAccessibility: "Album ảnh",
        .feedAlbumTitle: "Album",
        .feedAlbumLoading: "Đang tải album...",
        .feedAlbumEmptyTitle: "Chưa có ảnh",
        .feedAlbumEmptyMessage: "Ảnh từ bài đăng của bạn sẽ hiện ở đây.",

        // Streak
        .feedStreakTitle: "Chuỗi",
        .feedStreakCurrentStreak: "Chuỗi hiện tại",
        .feedStreakDays: "ngày liên tiếp",
        .feedStreakEmptyDay: "Không có ảnh",
        .feedStreakNoPhotosToday: "Đăng ảnh hôm nay để giữ chuỗi!",
        .feedStreakQuoteZero: "Chuỗi 0 ngày — máy ảnh đang xin nghỉ phép có lương.",
        .feedStreakQuoteGrowing: "Mới lót đường thôi, đừng để chiếc tủ lạnh vượt streak bạn.",
        .feedStreakQuoteSolid: "Streak ngon lành — thuật toán chưa kịp hiểu bạn đang làm gì.",
        .feedStreakQuoteLegend: "Huyền thoại thật sự. NASA gọi mà bạn bận chụp ảnh.",
        .feedStreakLoading: "Đang tải chuỗi...",
        .feedStreakError: "Không tải được chuỗi",
        .feedFilterTitle: "Bộ lọc",
        .feedFilterNoFriends: "Bạn chưa có bạn bè",
        .feedFilterFriendsNotFound: "Không tìm thấy bạn bè",
        .feedFilterByFriends: "Lọc theo bạn bè",
        .feedFilterNoGroups: "Bạn chưa tham gia nhóm nào",
        .feedFilterByGroups: "Lọc theo nhóm",
        .feedPostCommentsTitle: "Bình luận",
        .feedPostCommentsHeader: "Bình luận",
        .feedPostCommentsEmpty: "Chưa có bình luận. Hãy là người đầu tiên!",
        .feedPostCommentsLoadMore: "Xem thêm bình luận",
        .feedPostViewAllComments: "Xem tất cả %d bình luận",
        .feedPostWriteComment: "Viết bình luận...",
        .feedCompanionsEmpty: "Không tìm thấy người đi cùng",
        .feedCompanionsTitle: "Cùng với (%d)",
        .feedCompanionsSummary: "Cùng với %@",
        .feedCompanionsWith: "Cùng với",
        .feedCompanionsAndOthers: " và +%d người khác",
        .feedCheckInAt: "Check-in tại %@",
        .feedViewersTitle: "Đã xem (%d)",
        .feedBillSplitTitle: "Chia bill",
        .feedBillRemindAll: "Nhắc tất cả (%d)",
        .feedBillRemindTitle: "Nhắc nhở",
        .feedBillRemindAllTitle: "Nhắc tất cả",
        .feedBillRemindAllMessage: "Gửi nhắc tới %d người chưa thanh toán",
        .feedBillPaidAccessibility: "Đã thanh toán",
        .feedBillRemindUserAccessibility: "Nhắc %@",
        .feedBillPaidCount: "%d/%d người",
        .feedBillTotalLabel: "Tổng",
        .feedBillSettled: "Đã tất toán",
        .feedBillReminderCooldown: "Vừa gửi nhắc nhở gần đây. Vui lòng đợi 15 phút trước khi gửi lại.",
        .feedBillReminderAlreadyPaid: "Người này đã thanh toán phần của họ.",
        .feedBillReminderNoTargets: "Hiện không có ai phù hợp để nhắc nhở.",
        .feedBillReminderRateLimited: "Đã đạt giới hạn nhắc nhở trong ngày. Hãy thử lại vào ngày mai.",
        .feedBillReminderSentSingle: "Đã gửi nhắc nhở tới %@",
        .feedBillReminderSentMultiple: "Đã gửi nhắc nhở tới %d/%d người",
        .feedPaymentPay: "Trả tiền",
        .feedPaymentPending: "Đợi duyệt",
        .feedPaymentPaid: "Đã trả",
        .feedPaymentStatusPaid: "Bạn đã trả",
        .feedPaymentStatusSubmitEvidence: "Nộp ảnh chuyển khoản",
        .feedPaymentStatusResubmitEvidence: "Nộp lại ảnh chuyển khoản",
        .feedPaymentStatusPendingApproval: "Chờ xác nhận thanh toán",
        .feedPaymentStatusHintUnpaid: "Bạn chưa trả tiền cho %@.",
        .feedPaymentStatusHintResubmit: "Ảnh chuyển khoản bị từ chối.",
        .feedPaymentStatusHintPending: "Bạn đã nộp ảnh chuyển khoản cho %@. Đang chờ xác nhận thanh toán.",
        .feedPaymentStatusHintPaid: "Bạn đã trả tiền cho %@. Cảm ơn bạn!",
        .feedPaymentEvidenceTitle: "Gửi bằng chứng thanh toán",
        .feedPaymentEvidenceHint: "Tải ảnh chuyển khoản và gửi cho %@",
        .feedPaymentEvidenceMessagePlaceholder: "Lời nhắn (tuỳ chọn)",
        .feedPaymentEvidencePickPhoto: "Chọn ảnh chuyển khoản",
        .feedPaymentEvidenceSubmit: "Gửi",
        .feedPaymentEvidenceAttachmentRequired: "Vui lòng đính kèm bằng chứng chuyển khoản",
        .feedPaymentEvidenceBadge: "Bằng chứng thanh toán",
        .feedPaymentEvidenceApprove: "Duyệt",
        .feedPaymentEvidenceReject: "Từ chối",
        .feedPaymentEvidenceRejectReasonPlaceholder: "Lý do từ chối",
        .feedPaymentEvidenceStatusApproved: "Được chấp nhận",
        .feedPaymentEvidenceStatusRejected: "Bị từ chối",
        .feedPaymentEvidenceModerationApproved: "Đã duyệt",
        .feedPaymentEvidenceModerationRejected: "Đã từ chối",
        .splickBotProfileTagline: "Chuyên gia thu nợ · Chứng nhận alley neon",
        .splickBotProfileBio: "10 năm kinh nghiệm đòi bạn bè trả tiền cafe, trà sữa và bill cuối tuần. Phương châm: \"Nợ thì trả, không trả thì @tag liên tục.\" Đã thu hồi 99,9% các khoản dưới 50k — 50k còn lại đang ngồi đàm phán với ly trà sữa.",
        .splickBotStatReminders: "Lần nhắc nợ",
        .splickBotStatRecovery: "Tỷ lệ thu hồi",
        .splickBotStatExperience: "Kinh nghiệm",
        .splickBotStatRecoveryValue: "99.9%",
        .splickBotStatExperienceValue: "10 năm",
        .feedReactionsTitle: "Cảm xúc",
        .feedReactionsCount: "%d cảm xúc",
        .feedReactionsMore: "+%d người bày tỏ cảm xúc khác",
        .feedCreateTitle: "Đăng bài",
        .feedCreatePosting: "Đang đăng...",
        .feedCreateAddMedia: "Thêm media",
        .feedCreateMediaLimit: "Tối đa 5 ảnh và 3 video",
        .feedCreateCaption: "Caption",
        .feedCreateTagFriends: "Gắn thẻ bạn bè",
        .feedCreateTagFriendsHint: "Gắn thẻ bạn bè để chia bill cùng người khác.",
        .feedCreateFriendsNotFound: "Không tìm thấy bạn bè",
        .feedCreateLocation: "Vị trí",
        .feedCreateTotalAmount: "Tổng tiền",
        .feedCreateCurrencySymbol: "đ",
        .feedMentionSuggestions: "Gợi ý bạn bè",
        .feedEmojiPickerTitle: "Chọn emoji",
        .feedEmojiPickerQuickBarTitle: "Thanh nhanh",
        .feedEmojiPickerQuickBarHint: "Chạm một ô rồi chọn emoji bên dưới để gán. Chạm emoji trực tiếp để gửi cảm xúc.",
        .feedEmojiPickerAllTitle: "Tất cả emoji",
        .feedEmojiPickerHint: "Bàn phím emoji của iPhone sẽ hiện khi bạn chạm vào ô trên.",
        .feedEmojiPickerCustomTabTitle: "Của nhóm",
        .feedCustomEmojiAddAction: "Thêm",
        .feedCustomEmojiUploadTitle: "Emoji nhóm",
        .feedCustomEmojiUploadSectionTitle: "Tải emoji mới",
        .feedCustomEmojiChoosePhoto: "Chọn ảnh",
        .feedCustomEmojiShortcodePlaceholder: "Tên emoji (vd: cho_vay)",
        .feedCustomEmojiUploadAction: "Tải emoji lên",
        .feedCustomEmojiExistingTitle: "Emoji của nhóm",
        .feedCustomEmojiEmpty: "Chưa có emoji riêng. Hãy tải lên cho nhóm của bạn.",
        .stickersGifSearchPlaceholder: "Tìm kiếm trên KLIPY",
        .stickersTryAlso: "Thử thêm:",
        .stickersCategories: "Danh mục",
        .stickersTrendingTerms: "Đang hot",
        .stickersPopular: "Nhãn dán phổ biến",
        .stickersFavorites: "Yêu thích",
        .stickersEmoji: "Emoji",
        .stickersFavoritesEmpty: "Chưa có nhãn dán yêu thích. Chọn GIF để lưu vào đây.",
        .stickersRemoveFavorite: "Bỏ yêu thích",
        .stickersAddFavorite: "Thêm yêu thích",
        .stickersNoResultsTitle: "Không có nhãn dán",
        .feedProfileMessage: "Nhắn tin",
        .feedProfileAddFriend: "Thêm bạn",
        .profileLoading: "Đang tải hồ sơ…",
        .profileRetry: "Thử lại",
        .profileStatFriends: "Bạn bè",
        .profileStatPosts: "Bài viết",
        .profileStatGroups: "Nhóm",
        .profilePaymentManage: "Nhận tiền",
        .profilePaymentTitle: "QR thanh toán",
        .profilePaymentQrSection: "Ảnh mã QR",
        .profilePaymentBankSection: "Tài khoản ngân hàng",
        .profilePaymentAccountName: "Tên chủ tài khoản",
        .profilePaymentAccountNumber: "Số tài khoản",
        .profilePaymentBankName: "Ngân hàng",
        .profilePaymentSave: "Lưu",
        .profilePaymentDelete: "Xóa thông tin thanh toán",
        .profilePaymentDeleteConfirm: "Xóa mã QR và thông tin ngân hàng?",
        .profilePaymentUploadQr: "Tải ảnh QR lên",
        .profilePaymentFriendSection: "Thông tin nhận tiền",
        .profilePaymentEmptySelf: "Chưa có thông tin nhận tiền. Nhấn Nhận tiền để thêm QR hoặc tài khoản ngân hàng.",
        .profilePaymentEmptyFriend: "Bạn bè này chưa thiết lập thông tin nhận tiền.",
        .profilePaymentShare: "Chia sẻ",
        .profilePaymentSaveImage: "Lưu ảnh",
        .profilePaymentImageSaved: "Đã lưu ảnh vào Thư viện ảnh",
        .profilePaymentImageSaveFailed: "Không lưu được ảnh. Kiểm tra quyền Thư viện ảnh và thử lại.",

        // Friends
        .friendsTitle: "Bạn bè",
        .friendsListTitle: "Danh sách bạn bè",
        .friendsTabFriends: "Bạn bè",
        .friendsTabGroups: "Nhóm",
        .friendsIncomingRequests: "Lời mời kết bạn (%d)",
        .friendsOutgoingRequests: "Lời mời đã gửi (%d)",
        .friendsOutgoingRequestsPlain: "Lời mời đã gửi",
        .friendsBlockedUsers: "Người bị chặn",
        .friendsAddFriendTitle: "Thêm bạn",
        .friendsUsername: "Tên người dùng",
        .friendsMessageOptional: "Lời nhắn (tuỳ chọn)",
        .friendsJoinGroupTitle: "Tham gia nhóm",
        .friendsGroupInviteCode: "Mã mời nhóm",
        .friendsJoinGroupAction: "Tham gia nhóm",
        .friendsScanGroupQR: "Quét mã QR",
        .friendsRelationFriend: "Bạn bè",
        .friendsRelationSent: "Đã gửi",
        .friendsAccept: "Chấp nhận",
        .friendsAddFriendAction: "Kết bạn",
        .friendsRecallRequest: "Thu hồi",
        .friendsReject: "Từ chối",
        .friendsCancel: "Hủy",
        .friendsClose: "Đóng",
        .friendsMyQRTitle: "Mã QR của tôi",
        .friendsMyQRHint: "Bạn bè quét mã này để gửi lời mời kết bạn trên Splick.",
        .friendsMyQRRefresh: "Làm mới mã",
        .friendsMyQRShare: "Chia sẻ mã",
        .friendsMyQRGenerating: "Đang tạo mã QR...",
        .friendsMyQRFailed: "Không thể tạo mã QR",
        .friendsMyQRVersion: "Phiên bản mã %d",
        .friendsMyQRPreviewTitle: "Mã QR của tôi",
        .friendsMyQRPreviewHint: "Chạm để phóng to hoặc chia sẻ",
        .friendsScanQRAddFriend: "Quét mã QR",
        .friendsScanQRJoinGroup: "Quét mã nhóm",
        .friendsScanQRUnified: "Quét mã QR",
        .friendsCreateGroup: "Tạo nhóm",
        .friendsSearchPlaceholder: "Tìm tên, username hoặc mã nhóm",
        .friendsJoinGroupByCode: "Tham gia nhóm",
        .friendsScanSimulatorHint: "Simulator không có camera. Dùng máy thật để quét, hoặc chọn ảnh từ album bên dưới.",
        .friendsScanQRFromAlbum: "Quét QR từ ảnh trong album",
        .friendsScanQRFromAlbumFailed: "Không tìm thấy mã QR trong ảnh này.",
        .friendsScanManualHint: "Hoặc dán mã thủ công",
        .friendsScanUseCode: "Dùng mã này",
        .friendsIncomingTitle: "Lời mời kết bạn",
        .friendsIncomingLoading: "Đang tải lời mời...",
        .friendsIncomingEmptyTitle: "Không có lời mời",
        .friendsIncomingEmptyMessage: "Khi ai đó gửi lời mời kết bạn, bạn sẽ thấy ở đây.",
        .friendsOutgoingTitle: "Lời mời đã gửi",
        .friendsOutgoingLoading: "Đang tải lời mời đã gửi...",
        .friendsOutgoingEmptyTitle: "Chưa gửi lời mời",
        .friendsOutgoingEmptyMessage: "Lời mời bạn gửi sẽ hiện ở đây cho đến khi được chấp nhận hoặc bạn huỷ.",
        .friendsBlockedTitle: "Người bị chặn",
        .friendsBlockedLoading: "Đang tải danh sách chặn...",
        .friendsBlockedEmptyTitle: "Chưa chặn ai",
        .friendsBlockedEmptyMessage: "Người bạn chặn sẽ hiện ở đây. Bạn có thể bỏ chặn bất cứ lúc nào.",
        .friendsPeopleYouMayKnowTitle: "Người có thể quen",
        .friendsPeopleYouMayKnowLoading: "Đang tìm gợi ý...",
        .friendsPeopleYouMayKnowEmptyTitle: "Chưa có gợi ý",
        .friendsPeopleYouMayKnowEmptyMessage: "Tham gia nhóm hoặc mời bạn bè — chúng tôi sẽ gợi ý người từ các nhóm chung.",
        .friendsPeopleYouMayKnowSharedGroup: "Cùng nhóm · %@",
        .friendsUnblock: "Bỏ chặn",
        .friendsSetNickname: "Đặt biệt danh",
        .friendsRemoveFriend: "Xóa bạn",
        .friendsBlockUser: "Chặn người dùng",
        .friendsNicknameTitle: "Biệt danh",
        .friendsNicknamePlaceholder: "Biệt danh (chỉ bạn thấy)",
        .friendsRemoveFriendConfirmTitle: "Xóa bạn?",
        .friendsRemoveFriendConfirmAction: "Xóa bạn",
        .friendsBlockConfirmTitle: "Chặn người dùng này?",
        .friendsBlockConfirmAction: "Chặn",
        .friendsGroupPending: "Chờ duyệt (%d)",
        .friendsGroupMembers: "Thành viên (%d)",
        .friendsGroupMemberCount: "Nhóm %d thành viên",
        .friendsGroupInviteCodeLabel: "Mã mời: %@",

        // Expense
        .expenseTitle: "Chi tiêu",
        .expenseLoading: "Đang tải chi tiêu...",
        .expenseEmptyTitle: "Chưa có chi tiêu",
        .expenseEmptyMessage: "Tạo khoản chi chung đầu tiên để bắt đầu chia bill.",
        .expenseEmptyAction: "Thêm chi tiêu",
        .expenseFilteredEmptyTitle: "Không có chi tiêu phù hợp",
        .expenseFilteredEmptyMessage: "Thử đổi bộ lọc hoặc xoá bộ lọc.",
        .expenseYouAreOwed: "Người khác nợ bạn",
        .expenseYouOwe: "Bạn nợ người khác",
        .expenseOverviewOwedPeopleCount: "%d người nợ bạn",
        .expenseOverviewOwingPeopleCount: "Bạn nợ %d người",
        .expenseOverviewFilterHint: "Chạm để lọc danh sách chi tiêu",
        .expenseOverviewSectionTitle: "Tổng quan chi tiêu",
        .expenseOverviewExpandHint: "Chạm để mở rộng",
        .expenseOverviewCollapseHint: "Chạm để thu gọn",
        .expenseOverviewExpandedAccessibility: "Đang mở",
        .expenseOverviewCollapsedAccessibility: "Đang thu gọn",
        .expenseRecordsSectionTitle: "Lịch sử chi tiêu",
        .expenseRecordsSectionThisWeek: "( tuần qua )",
        .expenseRecordsSectionThisMonth: "( tháng qua )",
        .expenseRecordsSectionAllTime: "( tất cả )",
        .expenseRowCreatorLabel: "chủ xị",
        .expenseRowPaidByMe: "( tôi )",
        .expenseRowPayVerb: "Bạn trả",
        .expenseRowReceiveVerb: "Bạn nhận",
        .expenseRowShareVerb: "Bạn",
        .expenseRowOfConnector: "trên tổng",
        .expenseFilterPanelTitle: "Bộ lọc",
        .expenseFilterOpenAccessibility: "Mở bộ lọc chi tiêu",
        .expenseFilterPresetWeek: "Tuần qua",
        .expenseFilterPresetMonth: "Tháng qua",
        .expenseFilterPresetAll: "Tất cả",
        .expensePaidBy: "Trả bởi %@",
        .expenseCreatedAt: "Tạo %@",
        .expenseSettledAt: "Đã thanh toán %@",
        .expenseStatusPending: "Chờ",
        .expenseStatusPartial: "Một phần",
        .expenseStatusSettled: "Đã xong",
        .expenseFilterSearchCaption: "Tìm theo mô tả",
        .expenseFilterMore: "Thêm bộ lọc",
        .expenseFilterClear: "Xoá bộ lọc",
        .expenseFilterStatus: "Trạng thái",
        .expenseFilterFriends: "Bạn bè",
        .expenseFilterSearchFriends: "Tìm bạn bè",
        .expenseFilterNoFriends: "Không tìm thấy bạn bè",
        .expenseFilterDateRange: "Khoảng thời gian",
        .expenseFilterFrom: "Từ",
        .expenseFilterTo: "Đến",
        .expenseFilterAnyTime: "Bất kỳ lúc nào",
        .expenseFilterFromDate: "Từ ngày",
        .expenseFilterToDate: "Đến ngày",
        .expenseDebtAll: "Tất cả",
        .expenseDebtOweUnpaid: "Tôi nợ · chưa trả",
        .expenseDebtOwePaid: "Tôi nợ · đã trả",
        .expenseDebtOwedUnpaid: "Nợ tôi · chưa trả",
        .expenseDebtOwedPaid: "Nợ tôi · đã trả",
        .expenseOverviewOweUnpaidCount: "%d khoản",
        .expenseOverviewOwePaidCount: "%d khoản",
        .expenseOverviewOwedUnpaidCount: "%d khoản",
        .expenseOverviewOwedPaidCount: "%d khoản",
        .expenseOverviewUnpaid: "Chưa trả",
        .expenseOverviewPaid: "Đã trả",
        .expenseOverviewEmptyChart: "Không có nợ",
        .expenseRowDescOweUnpaidLead: "Bạn chưa trả cho ",
        .expenseRowDescOwePaidLead: "Bạn đã trả cho ",
        .expenseRowDescOwedUnpaidTail: " chưa trả cho bạn",
        .expenseRowDescOwedPaidTail: " đã trả cho bạn",
        .expenseRowDescNeutral: "Bạn đã tạo đơn chi tiêu",
        .expenseCreateTitle: "Chi tiêu mới",
        .expenseCreateHowMuch: "Bao nhiêu?",
        .expenseCreateDescription: "Chi cho việc gì?",
        .expenseCreateCategory: "Danh mục",
        .expenseCreateSplitType: "Cách chia",
        .expenseCreateAction: "Tạo chi tiêu",
        .expenseSplitEqual: "Chia đều",
        .expenseSplitExact: "Số tiền cố định",
        .expenseSplitPercentage: "Theo phần trăm",
        .expenseRowPaidAccessibility: "Đã trả",
        .expenseRowUnpaidAccessibility: "Chưa trả",

        // Notification
        .notificationTitle: "Thông báo",
        .notificationLoading: "Đang tải thông báo...",
        .notificationEmptyTitle: "Không có thông báo",
        .notificationEmptyMessage: "Bạn đã xem hết! Thông báo mới sẽ hiện ở đây.",
        .notificationReadAll: "Đọc tất cả",
        .notificationSectionToday: "Hôm nay",
        .notificationSectionYesterday: "Hôm qua",
        .notificationSectionPastWeek: "Tuần vừa qua",
        .notificationSectionPastMonth: "Tháng vừa qua",
        .notificationSectionPastYear: "Năm vừa qua",
        .notificationInboxTitle: "Hộp thư",
        .notificationInboxEmpty: "Chưa có thông báo",
        .notificationBellAccessibility: "Thông báo",

        // Tab
        .tabMessages: "Tin nhắn",

        // Messaging
        .messagingTitle: "Tin nhắn",
        .messagingLoading: "Đang tải tin nhắn...",
        .messagingEmptyTitle: "Chưa có cuộc trò chuyện",
        .messagingEmptyMessage: "Tìm bạn bè ở trên để bắt đầu nhắn tin.",
        .messagingNewConversation: "Tin nhắn mới",
        .messagingInputPlaceholder: "Nhắn tin...",
        .messagingSend: "Gửi",
        .messagingYou: "Bạn",
        .messagingChatLoading: "Đang tải tin nhắn...",
        .messagingChatEmptyTitle: "Chưa có tin nhắn",
        .messagingChatEmptyMessage: "Gửi lời chào nào!",
        .messagingSelectFriend: "Chọn bạn bè để nhắn tin",
        .messagingSearchPlaceholder: "Tìm tin nhắn và người dùng",
        .messagingSearchLoading: "Đang tìm...",
        .messagingSearchEmptyTitle: "Không tìm thấy kết quả",
        .messagingSearchEmptyMessage: "Thử tên, username hoặc nội dung tin nhắn khác.",
        .messagingFilterGroups: "Nhóm",
        .messagingFilterUsers: "Người dùng",
        .messagingFilterUnread: "Chưa đọc",
        .messagingFilterCloseFriends: "Bạn thân",
        .messagingFilterComingSoon: "Sắp ra mắt",
        .messagingFilterEmptyGroupsTitle: "Chưa có nhóm chat",
        .messagingFilterEmptyGroupsMessage: "Tạo nhóm hoặc bỏ lọc để xem tất cả cuộc trò chuyện.",
        .messagingFilterEmptyUsersTitle: "Chưa có chat cá nhân",
        .messagingFilterEmptyUsersMessage: "Bắt đầu tin nhắn mới hoặc bỏ lọc để xem tất cả cuộc trò chuyện.",
        .messagingFilterEmptyUnreadTitle: "Đã xem hết",
        .messagingFilterEmptyUnreadMessage: "Bạn không còn tin nhắn chưa đọc.",
        .messagingStartConversationError: "Không thể bắt đầu cuộc trò chuyện",
        .messagingBellAccessibility: "Thông báo",
        .messagingMessageButton: "Nhắn tin",
        .messagingCreateGroupTitle: "Tạo nhóm",
        .messagingGroupNamePlaceholder: "Tên nhóm",
        .messagingGroupMembersTitle: "Thành viên",
        .messagingGroupNoFriends: "Hãy thêm bạn bè trước khi tạo nhóm.",
        .messagingGroupChatRequiresMembers: "Chọn ít nhất 1 thành viên để mở chat nhóm.",
        .messagingLeaveGroup: "Rời nhóm",
        .messagingLeaveGroupConfirmTitle: "Rời khỏi nhóm này?",
        .messagingGroupChangeAvatar: "Đổi ảnh đại diện nhóm",
        .messagingGroupChangeAvatarHint: "Chọn ảnh mới cho nhóm.",
        .messagingGroupChangeAvatarLoadError: "Không tải được ảnh đã chọn.",
        .messagingGroupChangeName: "Đổi tên nhóm",
        .messagingGroupManageMembers: "Quản lý thành viên",
        .messagingGroupMembersLoading: "Đang tải thành viên…",
        .messagingGroupOwnerBadge: "Trưởng nhóm",
        .messagingGroupRemoveMember: "Xóa",
        .messagingTapToRetry: "Nhấn để gửi lại",
        .messagingReplyAction: "Trả lời",
        .messagingReplyingTo: "Đang trả lời",
        .messagingReplyCancelAccessibility: "Hủy trả lời",
        .messagingReplyPhoto: "Ảnh",
        .messagingReplyEmpty: "Tin nhắn",
        .messagingReplyUnknownSender: "Thành viên",
        .messagingChatMoreAccessibility: "Tùy chọn cuộc trò chuyện",
        .messagingChatBlockedMessage: "Bạn đã chặn người này.",
        .messagingChatNotFriendsBanner: "Bạn chưa kết bạn với người này.",
        .messagingChatRequestSentBanner: "Đã gửi lời mời kết bạn.",
        .messagingChatRequestReceivedBanner: "Người này muốn kết bạn với bạn.",

        // Common extras
        .commonClose: "Đóng",
        .commonOK: "OK",
        .commonCancel: "Hủy",
        .commonSave: "Lưu",
        .commonError: "Lỗi",
        .commonSuccess: "Thành công",
        .commonOr: "hoặc",
    ]
}
