enum StringsEn {
    static let values: [L10nKey: String] = [
        .commonDone: "Done",
        .commonCancel: "Cancel",
        .commonClear: "Clear",
        .commonTryAgain: "Try again",
        .commonErrorTitle: "Oops!",
        .commonReferenceId: "Reference ID",
        .commonBack: "Back",
        .commonClose: "Close",
        .commonOK: "OK",
        .commonError: "Error",

        .tabFeed: "Feeds",
        .tabExpenses: "Expenses",
        .tabFriends: "Friends",
        .tabCamera: "Camera",
        .tabNotifications: "Notifications",

        .profileTitle: "Profile",
        .profileEdit: "Edit profile",
        .profileChangePassword: "Change password",
        .profileDevicesSessions: "Devices & sessions",
        .sessionsTitle: "Devices & sessions",
        .sessionsSubtitle: "These devices are signed in to your account. Remove any you do not recognize.",
        .sessionsThisDevice: "This device",
        .sessionsSignOut: "Sign out",
        .sessionsSignOutAll: "Sign out all other devices",
        .sessionsSignedIn: "Signed in",
        .sessionsExpires: "Expires",
        .sessionsLocation: "Location",
        .sessionsUnknownLocation: "Location unavailable",
        .sessionsLoadFailed: "Could not load devices.",
        .sessionsRevokeFailed: "Could not sign out that device.",
        .sessionsRevokeAllFailed: "Could not sign out all devices.",
        .profileConnectedAccounts: "Connected accounts",
        .connectedAccountsProviderGoogle: "Google",
        .connectedAccountsProviderEmail: "Email & password",
        .connectedAccountsProviderPhone: "Phone",
        .connectedAccountsProviderFacebook: "Facebook",
        .connectedAccountsStatusLinked: "Connected",
        .connectedAccountsStatusNotLinked: "Not connected",
        .connectedAccountsLinkAccessibility: "Link %@",
        .connectedAccountsUnlinkAccessibility: "Unlink %@",
        .connectedAccountsPhoneSheetHint: "Enter your phone number. We will send a verification code by SMS.",
        .connectedAccountsPhoneField: "Phone number",
        .connectedAccountsSendCode: "Send verification code",
        .connectedAccountsConnectPhone: "Connect phone",
        .connectedAccountsConnectPhoneTitle: "Connect phone",
        .connectedAccountsEmailSheetPhoneOnlyHint: "Add an email and password to sign in without SMS.",
        .connectedAccountsEmailSheetHint: "Set a password for %@. We will email you a verification code.",
        .connectedAccountsEmailField: "Email",
        .connectedAccountsPasswordField: "Password",
        .connectedAccountsConfirmPasswordField: "Confirm password",
        .connectedAccountsConnectEmail: "Connect email",
        .connectedAccountsConnectEmailTitle: "Connect email",
        .connectedAccountsVerifyWith: "Verify with",
        .connectedAccountsVerifyPassword: "Password",
        .connectedAccountsVerifyEmailCode: "Email code",
        .connectedAccountsSendEmailCode: "Send code to email",
        .connectedAccountsUnlinkGoogle: "Unlink Google",
        .connectedAccountsUnlinkGoogleTitle: "Unlink Google",
        .connectedAccountsLoadFailed: "Could not load connected accounts.",
        .connectedAccountsGoogleUnavailable: "Google Sign-In is not available on this device.",
        .connectedAccountsGoogleLinked: "Google account linked.",
        .connectedAccountsGoogleLinkFailed: "Could not link Google account.",
        .connectedAccountsGoogleUnlinked: "Google account unlinked.",
        .connectedAccountsUnlinkFailed: "Could not unlink Google account.",
        .connectedAccountsPhoneRequired: "Enter a phone number.",
        .connectedAccountsCodeSentPhone: "Code sent to %@.",
        .connectedAccountsSendCodeFailed: "Could not send verification code.",
        .connectedAccountsPhoneLinked: "Phone number connected.",
        .connectedAccountsPhoneLinkFailed: "Could not connect phone number.",
        .connectedAccountsEmailRequired: "Enter an email address.",
        .connectedAccountsEmailLinked: "Email and password connected.",
        .connectedAccountsEmailLinkFailed: "Could not connect email.",
        .connectedAccountsPasswordTooShort: "Password must be at least %d characters.",
        .connectedAccountsUnlinkGoogleHint: "Verify your identity before unlinking Google from this account.",
        .profileDeactivateDelete: "Deactivate or delete account",
        .profileSignOut: "Sign Out",
        .profileLanguage: "Language",
        .profileLanguageVi: "Tiếng Việt",
        .profileLanguageEn: "English",
        .profileRefreshFailed: "Could not refresh profile.",
        .profileSettingsAccessibility: "Profile settings",
        .profileAvatarView: "View avatar",
        .profileAvatarEdit: "Change avatar",
        .profileAvatarDelete: "Use default avatar",
        .profileEditDisplayName: "Edit display name",
        .profileGroupAccount: "Account",
        .profileGroupPersonal: "Personal profile",
        .profileGroupApp: "App",
        .profileQrReceive: "Receive money QR",
        .profileCopyInviteLink: "Share invite link",
        .profileBirthday: "Date of birth",
        .profileBirthdayAgeError: "You must be at least 13 years old",
        .profileChangeUsername: "Change username",
        .profileUsernameTooShort: "Username must be at least 3 characters",
        .profileUsernameTooLong: "Username is too long",
        .profileUsernameInvalid: "Letters, numbers, _ and . only",
        .profileUsernameChecking: "Checking availability…",
        .profileNotifications: "Notifications",
        .profileTheme: "Theme",
        .profileAppIcon: "App icon",
        .profileWidget: "Widget",
        .profileGroupAbout: "About",
        .profileShareSplick: "Share Splick",
        .profileShareSplickMessage: "Join Splick — social network and shared expenses.",
        .profileRateSplick: "Rate Splick",
        .profileTermsOfService: "Terms of Service",
        .profilePrivacyPolicy: "Privacy Policy",
        .profileSupport: "Support",
        .legalTermsTitle: "Terms of Service",
        .legalPrivacyTitle: "Privacy Policy",
        .legalConsentPrefix: "By signing up, you agree to our",
        .legalConsentPrefixSignIn: "By signing in, you agree to our",
        .legalConsentRequiredError: "Please accept the Terms and Privacy Policy",
        .legalOpenInBrowser: "Open in browser",
        .legalDocumentLoadFailed: "Could not load this document.",
        .profileDeactivate: "Deactivate account",
        .profileDeleteAccount: "Delete account",
        .accountClosureDeactivateWarning: "Your account will be deactivated and you will be signed out on all devices. You will not be able to sign in again until support reactivates your account.",
        .accountClosureDeleteWarning: "This permanently removes your profile and signs you out on all devices. This action cannot be undone.",
        .accountClosureVerifiedHint: "Identity verified. You can complete this action below.",
        .accountClosureConfirmDeactivate: "Deactivate my account",
        .accountClosureConfirmDelete: "Delete my account permanently",
        .accountClosureVerifyFirst: "Verify your password before continuing.",
        .accountClosureDeactivateFailed: "Could not deactivate account.",
        .accountClosureDeleteFailed: "Could not delete account.",
        .profileComingSoon: "Coming soon",
        .profileComingSoonMessage: "This feature is not available yet.",
        .profileSave: "Save",
        .profileAvatarChangeHint: "Choose a new profile photo.",

        .changePasswordTitle: "Change password",
        .createPasswordTitle: "Create password",
        .createPasswordHint:
            "This account does not have a password yet. Verify your email with an OTP, then create a password so you can sign in with email.",
        .createPasswordSubmit: "Create password",
        .createPasswordVerifiedHint: "Verified. Create your password below.",
        .changePasswordVerifyWith: "Verify with",
        .changePasswordMethodCurrent: "Current password",
        .changePasswordMethodEmail: "Email code",
        .changePasswordCurrentPassword: "Current password",
        .changePasswordNewPassword: "New password",
        .changePasswordConfirmPassword: "Confirm password",
        .changePasswordVerifyContinue: "Verify and continue",
        .changePasswordUpdate: "Update password",
        .changePasswordSendCode: "Send code to email",
        .changePasswordCodeSent: "Code sent to %@. Check your inbox.",
        .changePasswordCurrentRequired: "Current password is required",
        .changePasswordInvalidCurrent: "Current password is incorrect",
        .changePasswordPasswordsMismatch: "Passwords do not match",
        .changePasswordWeakPassword: "Password does not meet requirements",
        .changePasswordOtpRequired: "Enter the 6-digit code",
        .changePasswordFailed: "Could not change password.",
        .changePasswordVerifiedHint: "Identity verified. Set your new password below.",
        .changePasswordEmailHint: "A verification code will be sent to your account email.",
        .changePasswordResendCode: "Resend code",
        .changePasswordResendIn: "Resend code in %d s",
        .authShowPassword: "Show password",
        .authHidePassword: "Hide password",

        .authWelcomeTitle: "Welcome to Splick",
        .authWelcomeSubtitle: "Manage expenses and connect with friends",
        .authEmail: "Email",
        .authIdentifier: "Email or phone number",
        .authPassword: "Password",
        .authConfirmPassword: "Confirm password",
        .authUsername: "Username",
        .authDisplayName: "Full name",
        .authDisplayNameOptional: "Full name (optional)",
        .authDateOfBirth: "Date of birth",
        .authDateOfBirthOptional: "Date of birth (optional)",
        .authDateOfBirthPlaceholder: "Select date of birth",
        .authContinue: "Continue",
        .authSignIn: "Sign In",
        .authSendCode: "Send code",
        .authSignUp: "Sign Up",
        .authCompleteProfileTitle: "Complete your profile",
        .authCompleteProfileSubtitle: "Add a name, birthday, and photo — or skip and do this later.",
        .authSetupLater: "Set up later",
        .authForgotPassword: "Forgot password?",
        .authContinueWithGoogle: "Continue with Google",
        .authSignInWithGoogle: "Sign in with Google",
        .authSignInWithApple: "Sign in with Apple",
        .authSignInWithFacebook: "Sign in with Facebook",
        .authSignInFailedGeneric: "Couldn't sign in. Try again?",
        .authFacebookComingSoon: "Facebook sign-in is coming soon.",
        .authResetPasswordTitle: "Reset password",
        .authResetPasswordSubtitle: "Enter the email or phone number for your account. We will send a verification code.",
        .authForgotPasswordPhoneUnsupported: "Password reset via phone is not available yet. Use your email address.",
        .authResetCodeRequested: "If an account exists for this email, a code was sent. Check your inbox.",
        .authValidationInvalidEmail: "Please enter a valid email",
        .authValidationInvalidPhone: "Use international format, e.g. +84901234567",
        .authUseDifferentIdentifier: "Use a different email or phone",
        .authVerifyPhoneTitle: "Enter verification code",
        .authVerifyPhoneSubtitle: "We sent a 6-digit code via SMS to %@.",
        .authVerifyEmailTitle: "Enter verification code",
        .authVerifyEmailSubtitle: "We sent a 6-digit code to %@.",
        .authOtpEmailHint: "Can't find it? Check your spam or junk folder.",
        .authOtpPhoneHint: "The SMS may take up to a minute to arrive.",
        .authOtpPhoneHintDebug: "Code sent via SMS. Check auth-service logs for [MockTwilio].",
        .authOtpSmsCodeRequired: "Enter the 6-digit code from SMS.",
        .authNoAccount: "Don't have an account?",
        .authHaveAccount: "Already have an account?",

        .errorNetworkNoConnection: "Looks like you're offline. Check your wifi or data and try again.",
        .errorNetworkServerUnreachable: "Can't reach the server right now. Hang tight and try again.",
        .errorNetworkServerUnreachableDebug: "Cannot reach the API server. In Terminal, run: make -C splick-mobile-ios stubs",
        .errorNetworkTimeout: "That took too long. Mind giving it another go?",
        .errorNetworkServer: "Something's a little off. Give it another try!",
        .errorNetworkDecoding: "Got a weird response. Let's try that again.",
        .errorNetworkInvalidURL: "That request didn't look right. Try again?",
        .errorNetworkUnauthorized: "Your session expired. Log in again to keep going.",
        .errorNetworkForbidden: "You don't have access to do that.",
        .errorMediaForbiddenGroupAvatar: "Only group members can change the group avatar.",
        .errorNetworkNotFound: "We couldn't find what you're looking for.",
        .errorNetworkRateLimited: "Whoa, slow down a sec — then try again.",
        .errorNetworkUnexpected: "Something unexpected happened. Try again?",

        .errorAuthInvalidCredentials: "Invalid email or password.",
        .errorAuthTokenExpired: "Your session has expired. Please log in again.",
        .errorAuthRefreshFailed: "Failed to refresh session.",
        .errorAuthAccountLocked: "Your account has been locked.",
        .errorAuthAccountInactive: "This account has been deactivated.",
        .errorAuthCannotUnlinkLast: "Keep at least one sign-in method on your account.",
        .errorAuthGoogleAlreadyLinked: "This Google account is already linked to another user.",
        .errorAuthProviderAlreadyLinked: "This sign-in method is already connected.",
        .errorAuthOtpRateLimited: "Too many verification attempts. Please wait a few minutes before requesting a new code.",
        .errorAuthRegistrationFailed: "Registration failed: %@",
        .errorAuthEmailExists: "An account with this email already exists. Sign in instead.",
        .errorAuthEmailUseGoogle: "This account uses Google sign-in. Tap Continue with Google on the login screen.",
        .errorAuthPhoneExists: "This phone number already has an account. Sign in with SMS instead.",
        .errorAuthUsernameExists: "That username is taken. Choose another.",
        .errorAuthInvalidOtpDefault: "Invalid or expired verification code.",
        .errorAuthInvalidOtpPrompt: "Enter the 6-digit code from your email.",
        .errorAuthEmailDeliveryFailed: "Couldn't send that email. Try again later!",
        .notificationSettingsStatusSection: "Status",
        .notificationSettingsActionSection: "Actions",
        .notificationSettingsPermissionLabel: "System permission",
        .notificationSettingsDeviceRegistrationLabel: "Backend registration",
        .notificationSettingsPermissionAllowed: "Allowed",
        .notificationSettingsPermissionDenied: "Denied",
        .notificationSettingsPermissionNotDetermined: "Not requested",
        .notificationSettingsPermissionUnknown: "Unknown",
        .notificationSettingsRegistrationSynced: "Synced",
        .notificationSettingsRegistrationPending: "Pending sync",
        .notificationSettingsRegistrationUnavailable: "No device token yet",
        .notificationSettingsEnableAction: "Enable notifications",
        .notificationSettingsOpenSystemSettingsAction: "Open system settings",
        .notificationSettingsSoundSection: "Notification sound",
        .notificationSettingsDescription: "Splick uses APNs to deliver real-time alerts. Allow notifications and keep a valid session to receive them on this device.",
    ]
}
