enum StringsFeatureVi {
    static let values: [L10nKey: String] = [
        // Feed
        .feedTitle: "Tin",
        .feedLoading: "Đang tải bảng tin...",
        .feedEmptyTitle: "Chưa có bài đăng",
        .feedEmptyMessage: "Chia sẻ khoảnh khắc với bạn bè để bắt đầu!",
        .feedEmptyAction: "Chụp ảnh",
        .feedEndReachedTitle: "Hết tin rồi đó",
        .feedEndReachedMessage: "Bạn đã lướt sạch feed. Đi đời thật một chút — tin mới sẽ chờ bạn quay lại.",
        .feedPhotoAlbumAccessibility: "Album ảnh",
        .feedAlbumTitle: "Album",
        .feedAlbumLoading: "Đang tải album...",
        .feedAlbumEmptyTitle: "Chưa có ảnh",
        .feedAlbumEmptyMessage: "Ảnh từ bài đăng của bạn sẽ hiện ở đây.",

        // Streak
        .feedStreakTitle: "Chuỗi",
        .feedStreakCurrentStreak: "Chuỗi hiện tại",
        .feedStreakDays: "ngày liên tiếp",
        .feedStreakEmptyDay: "Không có ảnh",
        .feedStreakNoPhotosToday: "Đăng ảnh hôm nay để giữ chuỗi!",
        .feedStreakQuoteZero: "Chuỗi 0 ngày — máy ảnh đang xin nghỉ phép có lương.",
        .feedStreakQuoteGrowing: "Mới lót đường thôi, đừng để chiếc tủ lạnh vượt streak bạn.",
        .feedStreakQuoteSolid: "Streak ngon lành — thuật toán chưa kịp hiểu bạn đang làm gì.",
        .feedStreakQuoteLegend: "Huyền thoại thật sự. NASA gọi mà bạn bận chụp ảnh.",
        .feedStreakLoading: "Đang tải chuỗi...",
        .feedStreakError: "Không tải được chuỗi",
        .feedStreakEndOfHistory: "Đã hết",
        .feedFilterTitle: "Bộ lọc",
        .feedFilterNoFriends: "Bạn chưa có bạn bè",
        .feedFilterFriendsNotFound: "Không tìm thấy bạn bè",
        .feedFilterByFriends: "Lọc theo bạn bè",
        .feedFilterNoGroups: "Bạn chưa tham gia nhóm nào",
        .feedFilterByGroups: "Lọc theo nhóm",
        .feedPostCommentsTitle: "Bình luận",
        .feedPostCommentsHeader: "Bình luận",
        .feedPostCommentsEmpty: "Chưa có bình luận. Hãy là người đầu tiên!",
        .feedPostCommentsEmptyEvidence: "Chưa có bằng chứng thanh toán.",
        .feedPostCommentsLoadMore: "Xem thêm bình luận",
        .feedPostCommentsFilterComments: "Bình luận",
        .feedPostCommentsFilterEvidence: "Bằng chứng",
        .feedPostCommentsFilterAll: "Tất cả",
        .feedPostViewAllComments: "Xem tất cả %d bình luận",
        .feedPostWriteComment: "Viết bình luận...",
        .feedPostLoadFailed: "Chưa tải được bài viết. Thử lại phát nhé!",
        .feedPostUnavailableMessage: "Bài viết không còn khả dụng. Có thể đã bị xoá hoặc bạn không còn quyền xem.",
        .feedCompanionsEmpty: "Không tìm thấy người đi cùng",
        .feedCompanionsTitle: "Cùng với (%d)",
        .feedCompanionsSummary: "Cùng với %@",
        .feedCompanionsWith: "Cùng với",
        .feedCompanionsAndOthers: " và +%d người khác",
        .feedCheckInAt: "Check-in tại %@",
        .feedViewersTitle: "Đã xem (%d)",
        .feedBillSplitTitle: "Chia bill",
        .feedBillRemindAll: "Nhắc tất cả (%d)",
        .feedBillRemindTitle: "Nhắc nhở",
        .feedBillRemindAllTitle: "Nhắc tất cả",
        .feedBillRemindAllMessage: "Gửi nhắc tới %d người chưa thanh toán",
        .feedBillPaidAccessibility: "Đã thanh toán",
        .feedBillRemindUserAccessibility: "Nhắc %@",
        .feedBillPaidCount: "%d/%d đã trả",
        .feedBillTotalLabel: "Tổng",
        .feedBillSettled: "Đã tất toán",
        .feedBillUnpaidAccessibility: "Chưa thanh toán",
        .feedBillReminderMessageLabel: "Lời nhắn",
        .feedBillReminderSuggestAnother: "Gợi ý lời nhắn khác",
        .feedBillReminderSuggest1: "Bạn ơi, nhớ chuyển phần bill của bạn nhé! 🙏",
        .feedBillReminderSuggest2: "Nhắc nhẹ: bill hôm nay chưa thấy bạn thanh toán đâu 😅",
        .feedBillReminderSuggest3: "Hello! Giúp mình settle bill nha, cảm ơn bạn!",
        .feedBillReminderSuggest4: "Bill đang chờ bạn — chuyển khi rảnh giúp mình nhé!",
        .feedBillReminderSuggest5: "Team ơi, ai chưa chuyển bill nhớ làm giúp mình nha!",
        .feedBillReminderCooldown: "Vừa gửi nhắc nhở gần đây. Vui lòng đợi 15 phút trước khi gửi lại.",
        .feedBillReminderAlreadyPaid: "Người này đã thanh toán phần của họ.",
        .feedBillReminderNoTargets: "Hiện không có ai phù hợp để nhắc nhở.",
        .feedBillReminderRateLimited: "Đã đạt giới hạn nhắc nhở trong ngày. Hãy thử lại vào ngày mai.",
        .feedBillReminderSentSingle: "Đã gửi nhắc nhở tới %@",
        .feedBillReminderSentMultiple: "Đã gửi nhắc nhở tới %d/%d người",
        .feedPaymentPay: "Trả tiền",
        .feedPaymentPending: "Đợi duyệt",
        .feedPaymentPaid: "Đã trả",
        .feedPaymentStatusPaid: "Đã thanh toán",
        .feedPaymentStatusSubmitEvidence: "Upload ảnh chuyển khoản",
        .feedPaymentStatusResubmitEvidence: "Upload lại ảnh chuyển khoản",
        .feedPaymentStatusPendingApproval: "Đang chờ duyệt",
        .feedPaymentStatusHintUnpaid: "Chọn ảnh và nộp để chủ xị duyệt ảnh chuyển khoản.",
        .feedPaymentStatusHintResubmit: "Ồ nooo, ảnh của bạn bị chủ xị từ chối rồi, hãy upload lại.",
        .feedPaymentStatusHintPending: "Ảnh chuyển khoản của bạn đang chờ chủ xị xác nhận.",
        .feedPaymentStatusHintPaid: "Tuyệt vời, khoản thanh toán của bạn đã được chủ xị xác nhận thành công.",
        .feedPaymentEvidenceTitle: "Upload ảnh chuyển khoản",
        .feedPaymentEvidenceHint: "Gửi tối đa 3 ảnh chuyển khoản cho %@. Bạn có thể thêm lời nhắn nếu cần.",
        .feedPaymentEvidencePhotosLabel: "Ảnh chuyển khoản",
        .feedPaymentEvidenceMessagePlaceholder: "Lời nhắn (tuỳ chọn)",
        .feedPaymentEvidencePickPhoto: "Chọn ảnh chuyển khoản",
        .feedPaymentEvidenceSubmit: "Gửi",
        .feedPaymentEvidenceAttachmentRequired: "Vui lòng chọn ít nhất 1 ảnh chuyển khoản.",
        .feedPaymentEvidenceBadge: "Bằng chứng thanh toán",
        .feedPaymentEvidenceApprove: "Duyệt",
        .feedPaymentEvidenceReject: "Từ chối",
        .feedPaymentEvidenceRejectReasonPlaceholder: "Lý do từ chối",
        .feedPaymentEvidenceStatusApproved: "Được chấp nhận",
        .feedPaymentEvidenceStatusRejected: "Bị từ chối",
        .feedPaymentEvidenceModerationApproved: "Đã duyệt",
        .feedPaymentEvidenceModerationRejected: "Đã từ chối",
        .splickBotProfileTagline: "Chuyên gia thu nợ · Chứng nhận alley neon",
        .splickBotProfileBio: "10 năm kinh nghiệm đòi bạn bè trả tiền cafe, trà sữa và bill cuối tuần. Phương châm: \"Nợ thì trả, không trả thì @tag liên tục.\" Đã thu hồi 99,9% các khoản dưới 50k — 50k còn lại đang ngồi đàm phán với ly trà sữa.",
        .splickBotStatReminders: "Lần nhắc nợ",
        .splickBotStatRecovery: "Tỷ lệ thu hồi",
        .splickBotStatExperience: "Kinh nghiệm",
        .splickBotStatRecoveryValue: "99.9%",
        .splickBotStatExperienceValue: "10 năm",
        .feedReactionsTitle: "Cảm xúc",
        .feedReactionsCount: "%d cảm xúc",
        .feedReactionsMore: "+%d người bày tỏ cảm xúc khác",
        .feedReactionsNone: "Chưa có cảm xúc",
        .feedCreateTitle: "Đăng bài",
        .feedCreatePosting: "Đang đăng...",
        .feedCreateAddMedia: "Thêm media",
        .feedCreateMediaLimit: "Tối đa 5 ảnh và 3 video",
        .feedCreateCaption: "Caption",
        .feedCreateTagFriends: "Gắn thẻ bạn bè",
        .feedCreateTagFriendsHint: "Gắn thẻ bạn bè để chia bill cùng người khác.",
        .feedCreateFriendsNotFound: "Không tìm thấy bạn bè",
        .feedCreateLocation: "Vị trí",
        .feedCreateTotalAmount: "Tổng tiền",
        .feedCreateCurrencySymbol: "đ",
        .feedMentionSuggestions: "Gợi ý bạn bè",
        .feedEmojiPickerTitle: "Chọn emoji",
        .feedEmojiPickerQuickBarTitle: "Thanh nhanh",
        .feedEmojiPickerQuickBarHint: "Chạm một ô rồi chọn emoji bên dưới để gán. Chạm emoji trực tiếp để gửi cảm xúc.",
        .feedEmojiPickerAllTitle: "Tất cả emoji",
        .feedEmojiPickerHint: "Bàn phím emoji của iPhone sẽ hiện khi bạn chạm vào ô trên.",
        .feedEmojiPickerCustomTabTitle: "Của nhóm",
        .feedCustomEmojiAddAction: "Thêm",
        .feedCustomEmojiUploadTitle: "Emoji nhóm",
        .feedCustomEmojiUploadSectionTitle: "Tải emoji mới",
        .feedCustomEmojiChoosePhoto: "Chọn ảnh",
        .feedCustomEmojiShortcodePlaceholder: "Tên emoji (vd: cho_vay)",
        .feedCustomEmojiUploadAction: "Tải emoji lên",
        .feedCustomEmojiExistingTitle: "Emoji của nhóm",
        .feedCustomEmojiEmpty: "Chưa có emoji riêng. Hãy tải lên cho nhóm của bạn.",
        .stickersGifSearchPlaceholder: "Tìm kiếm trên KLIPY",
        .stickersTryAlso: "Thử thêm:",
        .stickersCategories: "Danh mục",
        .stickersTrendingTerms: "Đang hot",
        .stickersPopular: "Nhãn dán phổ biến",
        .stickersFavorites: "Yêu thích",
        .stickersEmoji: "Emoji",
        .stickersSearch: "Tìm",
        .stickersCustomPack: "Custom",
        .stickersQuickAccess: "Truy cập nhanh",
        .stickersHashtags: "Hashtag",
        .stickersFavoritesEmpty: "Chưa có nhãn dán yêu thích. Chọn GIF để lưu vào đây.",
        .stickersRemoveFavorite: "Bỏ yêu thích",
        .stickersAddFavorite: "Thêm yêu thích",
        .stickersNoResultsTitle: "Không có nhãn dán",
        .feedProfileMessage: "Nhắn tin",
        .feedProfileAddFriend: "Thêm bạn",
        .profileLoading: "Đang tải hồ sơ…",
        .profileRetry: "Thử lại xem nào",
        .profilePostsLoading: "Đang tải bài viết…",
        .profilePostsTitle: "Bài viết",
        .profilePostsEmptyTitle: "Chưa có bài viết",
        .profilePostsEmptyMessage: "Các bài viết được chia sẻ sẽ xuất hiện tại đây.",
        .postPreviewAccessibility: "Xem trước bài viết",
        .profileStatFriends: "Bạn bè",
        .profileStatPosts: "Bài viết",
        .profileStatGroups: "Nhóm",
        .profilePaymentManage: "Nhận tiền",
        .profilePaymentTitle: "QR thanh toán",
        .profilePaymentQrSection: "Ảnh mã QR",
        .profilePaymentBankSection: "Tài khoản ngân hàng",
        .profilePaymentAccountName: "Tên chủ tài khoản",
        .profilePaymentAccountNumber: "Số tài khoản",
        .profilePaymentBankName: "Ngân hàng",
        .profilePaymentSave: "Lưu",
        .profilePaymentDelete: "Xóa thông tin thanh toán",
        .profilePaymentDeleteConfirm: "Xóa mã QR và thông tin ngân hàng?",
        .profilePaymentUploadQr: "Tải ảnh QR lên",
        .profilePaymentFriendSection: "Thông tin nhận tiền",
        .profilePaymentEmptySelf: "Chưa có thông tin nhận tiền. Nhấn Nhận tiền để thêm QR hoặc tài khoản ngân hàng.",
        .profilePaymentEmptyFriend: "Bạn bè này chưa thiết lập thông tin nhận tiền.",
        .profilePaymentShare: "Chia sẻ",
        .profilePaymentSaveImage: "Lưu ảnh",
        .profilePaymentImageSaved: "Đã lưu ảnh vào Thư viện ảnh",
        .profilePaymentImageSaveFailed: "Không lưu được ảnh. Kiểm tra quyền Thư viện ảnh và thử lại.",

        // Friends
        .friendsTitle: "Bạn bè",
        .friendsListTitle: "Danh sách bạn bè",
        .friendsTabFriends: "Bạn bè",
        .friendsTabGroups: "Nhóm",
        .friendsIncomingRequests: "Lời mời kết bạn (%d)",
        .friendsOutgoingRequests: "Lời mời đã gửi (%d)",
        .friendsOutgoingRequestsPlain: "Lời mời đã gửi",
        .friendsBlockedUsers: "Người bị chặn",
        .friendsAddFriendTitle: "Thêm bạn",
        .friendsUsername: "Tên người dùng",
        .friendsMessageOptional: "Lời nhắn (tuỳ chọn)",
        .friendsJoinGroupTitle: "Tham gia nhóm",
        .friendsGroupInviteCode: "Mã mời nhóm",
        .friendsJoinGroupAction: "Tham gia nhóm",
        .friendsScanGroupQR: "Quét mã QR",
        .friendsRelationFriend: "Bạn bè",
        .friendsRelationSent: "Đã gửi",
        .friendsAccept: "Chấp nhận",
        .friendsAddFriendAction: "Kết bạn",
        .friendsRecallRequest: "Thu hồi",
        .friendsReject: "Từ chối",
        .friendsCancel: "Hủy",
        .friendsClose: "Đóng",
        .friendsMyQRTitle: "Mã QR của tôi",
        .friendsMyQRHint: "Bạn bè quét mã này để gửi lời mời kết bạn trên Splick.",
        .friendsMyQRRefresh: "Làm mới mã",
        .friendsMyQRShare: "Chia sẻ mã",
        .friendsMyQRGenerating: "Đang tạo mã QR...",
        .friendsMyQRFailed: "Không thể tạo mã QR",
        .friendsMyQRVersion: "Phiên bản mã %d",
        .friendsMyQRPreviewTitle: "Mã QR của tôi",
        .friendsMyQRPreviewHint: "Chạm để phóng to hoặc chia sẻ",
        .friendsScanQRAddFriend: "Quét mã QR",
        .friendsScanQRJoinGroup: "Quét mã nhóm",
        .friendsScanQRUnified: "Quét mã QR",
        .friendsCreateGroup: "Tạo nhóm",
        .friendsSearchPlaceholder: "Tìm tên, username hoặc mã nhóm",
        .friendsJoinGroupByCode: "Tham gia nhóm",
        .friendsScanSimulatorHint: "Simulator không có camera. Dùng máy thật để quét, hoặc chọn ảnh từ album bên dưới.",
        .friendsScanQRFromAlbum: "Quét QR từ ảnh trong album",
        .friendsScanQRFromAlbumFailed: "Không tìm thấy mã QR trong ảnh này.",
        .friendsScanManualHint: "Hoặc dán mã thủ công",
        .friendsScanUseCode: "Dùng mã này",
        .friendsIncomingTitle: "Lời mời kết bạn",
        .friendsIncomingLoading: "Đang tải lời mời...",
        .friendsIncomingEmptyTitle: "Không có lời mời",
        .friendsIncomingEmptyMessage: "Khi ai đó gửi lời mời kết bạn, bạn sẽ thấy ở đây.",
        .friendsOutgoingTitle: "Lời mời đã gửi",
        .friendsOutgoingLoading: "Đang tải lời mời đã gửi...",
        .friendsOutgoingEmptyTitle: "Chưa gửi lời mời",
        .friendsOutgoingEmptyMessage: "Lời mời bạn gửi sẽ hiện ở đây cho đến khi được chấp nhận hoặc bạn huỷ.",
        .friendsBlockedTitle: "Người bị chặn",
        .friendsBlockedLoading: "Đang tải danh sách chặn...",
        .friendsBlockedEmptyTitle: "Chưa chặn ai",
        .friendsBlockedEmptyMessage: "Người bạn chặn sẽ hiện ở đây. Bạn có thể bỏ chặn bất cứ lúc nào.",
        .friendsPeopleYouMayKnowTitle: "Người có thể quen",
        .friendsPeopleYouMayKnowLoading: "Đang tìm gợi ý...",
        .friendsPeopleYouMayKnowEmptyTitle: "Chưa có gợi ý",
        .friendsPeopleYouMayKnowEmptyMessage: "Tham gia nhóm hoặc mời bạn bè — chúng tôi sẽ gợi ý người từ các nhóm chung.",
        .friendsPeopleYouMayKnowSharedGroup: "Cùng nhóm · %@",
        .friendsUnblock: "Bỏ chặn",
        .friendsSetNickname: "Đặt biệt danh",
        .friendsRemoveFriend: "Xóa bạn",
        .friendsBlockUser: "Chặn người dùng",
        .friendsNicknameTitle: "Biệt danh",
        .friendsNicknamePlaceholder: "Biệt danh (chỉ bạn thấy)",
        .friendsRemoveFriendConfirmTitle: "Xóa bạn?",
        .friendsRemoveFriendConfirmAction: "Xóa bạn",
        .friendsBlockConfirmTitle: "Chặn người dùng này?",
        .friendsBlockConfirmAction: "Chặn",
        .friendsGroupPending: "Chờ duyệt (%d)",
        .friendsGroupMembers: "Thành viên (%d)",
        .friendsGroupMemberCount: "Nhóm %d thành viên",
        .friendsGroupInviteCodeLabel: "Mã mời: %@",

        // Expense
        .expenseTitle: "Chi tiêu",
        .expenseLoading: "Đang tải chi tiêu...",
        .expenseEmptyTitle: "Chưa có chi tiêu",
        .expenseEmptyMessage: "Tạo khoản chi chung đầu tiên để bắt đầu chia bill.",
        .expenseEmptyAction: "Thêm chi tiêu",
        .expenseFilteredEmptyTitle: "Không có chi tiêu phù hợp",
        .expenseFilteredEmptyMessage: "Thử đổi bộ lọc hoặc xoá bộ lọc.",
        .expenseYouAreOwed: "Người khác nợ bạn",
        .expenseYouOwe: "Bạn nợ người khác",
        .expenseOverviewOwedPeopleCount: "%d người nợ bạn",
        .expenseOverviewOwingPeopleCount: "Bạn nợ %d người",
        .expenseOverviewFilterHint: "Chạm để lọc danh sách chi tiêu",
        .expenseOverviewSectionTitle: "Tổng quan chi tiêu",
        .expenseOverviewExpandHint: "Chạm để mở rộng",
        .expenseOverviewCollapseHint: "Chạm để thu gọn",
        .expenseOverviewExpandedAccessibility: "Đang mở",
        .expenseOverviewCollapsedAccessibility: "Đang thu gọn",
        .expenseRecordsSectionTitle: "Lịch sử chi tiêu",
        .expenseRecordsSectionThisWeek: "( tuần này )",
        .expenseRecordsSectionThisMonth: "( tháng này )",
        .expenseRecordsSectionAllTime: "( tất cả )",
        .expenseRowCreatorLabel: "chủ xị",
        .expenseRowPaidByMe: "( tôi )",
        .expenseRowPayVerb: "Bạn trả",
        .expenseRowReceiveVerb: "Bạn nhận",
        .expenseRowShareVerb: "Bạn",
        .expenseRowOfConnector: "trên tổng",
        .expenseFilterPanelTitle: "Bộ lọc",
        .expenseFilterOpenAccessibility: "Mở bộ lọc chi tiêu",
        .expenseFilterPresetWeek: "Tuần này",
        .expenseFilterPresetMonth: "Tháng này",
        .expenseFilterPresetAll: "Tất cả",
        .expensePaidBy: "Trả bởi %@",
        .expenseCreatedAt: "Tạo %@",
        .expenseSettledAt: "Đã thanh toán %@",
        .expenseStatusPending: "Chờ",
        .expenseStatusPartial: "Một phần",
        .expenseStatusSettled: "Đã xong",
        .expenseFilterSearchCaption: "Tìm theo mô tả",
        .expenseFilterMore: "Thêm bộ lọc",
        .expenseFilterClear: "Xoá bộ lọc",
        .expenseFilterStatus: "Trạng thái",
        .expenseFilterFriends: "Bạn bè",
        .expenseFilterSearchFriends: "Tìm bạn bè",
        .expenseFilterNoFriends: "Không tìm thấy bạn bè",
        .expenseFilterDateRange: "Khoảng thời gian",
        .expenseFilterFrom: "Từ",
        .expenseFilterTo: "Đến",
        .expenseFilterAnyTime: "Bất kỳ lúc nào",
        .expenseFilterFromDate: "Từ ngày",
        .expenseFilterToDate: "Đến ngày",
        .expenseDebtAll: "Tất cả",
        .expenseDebtOweUnpaid: "Tôi nợ · chưa trả",
        .expenseDebtOwePaid: "Tôi nợ · đã trả",
        .expenseDebtOwedUnpaid: "Nợ tôi · chưa trả",
        .expenseDebtOwedPaid: "Nợ tôi · đã trả",
        .expenseOverviewOweUnpaidCount: "%d khoản",
        .expenseOverviewOwePaidCount: "%d khoản",
        .expenseOverviewOwedUnpaidCount: "%d khoản",
        .expenseOverviewOwedPaidCount: "%d khoản",
        .expenseOverviewUnpaid: "Chưa trả",
        .expenseOverviewPaid: "Đã trả",
        .expenseOverviewEmptyChart: "Không có nợ",
        .expenseRowDescOweUnpaidLead: "Bạn chưa trả cho ",
        .expenseRowDescOwePaidLead: "Bạn đã trả cho ",
        .expenseRowDescOwedUnpaidTail: " chưa trả cho bạn",
        .expenseRowDescOwedPaidTail: " đã trả cho bạn",
        .expenseRowDescNeutral: "Bạn đã tạo đơn chi tiêu",
        .expenseCreateTitle: "Chi tiêu mới",
        .expenseCreateHowMuch: "Bao nhiêu?",
        .expenseCreateDescription: "Chi cho việc gì?",
        .expenseCreateCategory: "Danh mục",
        .expenseCreateSplitType: "Cách chia",
        .expenseCreateAction: "Tạo chi tiêu",
        .expenseSplitEqual: "Chia đều",
        .expenseSplitExact: "Số tiền cố định",
        .expenseSplitPercentage: "Theo phần trăm",
        .expenseRowPaidAccessibility: "Đã trả",
        .expenseRowUnpaidAccessibility: "Chưa trả",
        .expenseModeAll: "Tất cả chi tiêu",
        .expenseModeHistory: "Lịch sử",
        .expenseModeOverview: "Tổng quan",
        .expenseModeFriends: "Bạn bè",
        .expenseOverviewIncome: "Thu",
        .expenseOverviewExpenditure: "Chi",
        .expenseOverviewThisMonth: "Tháng này",
        .expenseOverviewChartTitle: "12 tháng gần nhất",
        .expenseOverviewDebtSectionTitle: "Nợ đang còn",
        .expenseFriendsTitle: "Chi tiêu theo bạn bè",
        .expenseFriendsLoading: "Đang tải bạn bè...",
        .expenseFriendsEmptyTitle: "Chưa có số dư bạn bè",
        .expenseFriendsEmptyMessage: "Các khoản chi chung với bạn bè sẽ xuất hiện tại đây.",
        .expenseFriendYouOwe: "Bạn nợ",
        .expenseFriendOwesYou: "Nợ bạn",
        .expenseFriendSettled: "Đã thanh toán",
        .expenseFriendDetailTitle: "Chi tiêu với bạn bè",
        .expenseFriendSummary: "Tổng kết công nợ",
        .expenseFriendNetAmount: "Số tiền ròng",
        .expenseFriendExpenseCount: "%d khoản chi",
        .expenseFriendSplitCount: "%d phần chưa trả",
        .expenseFriendWaiting: "Đang chờ bạn của bạn thanh toán",
        .expenseFriendQuickSettle: "Thanh toán số dư ròng",
        .expenseFriendLoadMore: "Tải thêm",
        .expenseBulkTitle: "Thanh toán số dư",
        .expenseBulkEvidence: "Bằng chứng thanh toán",
        .expenseBulkChooseEvidence: "Chọn ảnh hoặc ảnh chụp màn hình",
        .expenseBulkNote: "Thêm ghi chú (không bắt buộc)",
        .expenseBulkSubmit: "Gửi để phê duyệt",
        .expenseBulkUploading: "Đang tải bằng chứng...",
        .expenseBulkSubmitting: "Đang gửi thanh toán...",
        .expenseBulkPending: "Đang chờ phê duyệt",
        .expenseBulkSuccess: "Đã gửi thanh toán để phê duyệt.",
        .expenseBulkEvidenceRequired: "Chọn bằng chứng thanh toán trước khi gửi.",
        .expenseBulkApprove: "Phê duyệt",
        .expenseBulkReject: "Từ chối",
        .expenseBulkRejectReason: "Lý do (không bắt buộc)",

        // Notification
        .notificationTitle: "Thông báo",
        .notificationLoading: "Đang tải thông báo...",
        .notificationEmptyTitle: "Không có thông báo",
        .notificationEmptyMessage: "Bạn đã xem hết! Thông báo mới sẽ hiện ở đây.",
        .notificationReadAll: "Đọc tất cả",
        .notificationSectionToday: "Hôm nay",
        .notificationSectionYesterday: "Hôm qua",
        .notificationSectionPastWeek: "Tuần vừa qua",
        .notificationSectionPastMonth: "Tháng vừa qua",
        .notificationSectionPastYear: "Năm vừa qua",
        .notificationInboxTitle: "Hộp thư",
        .notificationInboxEmpty: "Chưa có thông báo",
        .notificationBellAccessibility: "Thông báo",

        // Tab
        .tabMessages: "Tin nhắn",

        // Messaging
        .messagingTitle: "Tin nhắn",
        .messagingLoading: "Đang tải tin nhắn...",
        .messagingEmptyTitle: "Chưa có cuộc trò chuyện",
        .messagingEmptyMessage: "Tìm bạn bè ở trên để bắt đầu nhắn tin.",
        .messagingNewConversation: "Tin nhắn mới",
        .messagingInputPlaceholder: "Nhắn tin...",
        .messagingSend: "Gửi",
        .messagingYou: "Bạn",
        .messagingChatLoading: "Đang tải tin nhắn...",
        .messagingChatEmptyTitle: "Chưa có tin nhắn",
        .messagingChatEmptyMessage: "Gửi lời chào nào!",
        .messagingConversationPeekEmpty: "Chưa có tin nhắn để xem trước.",
        .messagingConversationPeekError: "Không thể tải bản xem trước.",
        .messagingConversationPeekA11y: "Xem trước cuộc trò chuyện",
        .messagingSelectFriend: "Chọn bạn bè để nhắn tin",
        .messagingSearchPlaceholder: "Tìm tin nhắn và người dùng",
        .messagingSearchLoading: "Đang tìm...",
        .messagingSearchEmptyTitle: "Không tìm thấy kết quả",
        .messagingSearchEmptyMessage: "Thử tên, username hoặc nội dung tin nhắn khác.",
        .messagingFilterGroups: "Nhóm",
        .messagingFilterUsers: "Người dùng",
        .messagingFilterUnread: "Chưa đọc",
        .messagingFilterCloseFriends: "Bạn thân",
        .messagingFilterComingSoon: "Sắp ra mắt",
        .messagingFilterEmptyGroupsTitle: "Chưa có nhóm chat",
        .messagingFilterEmptyGroupsMessage: "Tạo nhóm hoặc bỏ lọc để xem tất cả cuộc trò chuyện.",
        .messagingFilterEmptyUsersTitle: "Chưa có chat cá nhân",
        .messagingFilterEmptyUsersMessage: "Bắt đầu tin nhắn mới hoặc bỏ lọc để xem tất cả cuộc trò chuyện.",
        .messagingFilterEmptyUnreadTitle: "Đã xem hết",
        .messagingFilterEmptyUnreadMessage: "Bạn không còn tin nhắn chưa đọc.",
        .messagingStartConversationError: "Không thể bắt đầu cuộc trò chuyện",
        .messagingBellAccessibility: "Thông báo",
        .messagingMessageButton: "Nhắn tin",
        .messagingCreateGroupTitle: "Tạo nhóm",
        .messagingGroupNamePlaceholder: "Tên nhóm",
        .messagingGroupMembersTitle: "Thành viên",
        .messagingGroupNoFriends: "Hãy thêm bạn bè trước khi tạo nhóm.",
        .messagingGroupChatRequiresMembers: "Chọn ít nhất 1 thành viên để mở chat nhóm.",
        .messagingLeaveGroup: "Rời nhóm",
        .messagingLeaveGroupConfirmTitle: "Rời khỏi nhóm này?",
        .messagingGroupChangeAvatar: "Đổi ảnh đại diện nhóm",
        .messagingGroupChangeAvatarHint: "Chọn ảnh mới cho nhóm.",
        .messagingGroupChangeAvatarLoadError: "Không tải được ảnh đã chọn.",
        .messagingGroupChangeName: "Đổi tên nhóm",
        .messagingGroupManageMembers: "Quản lý thành viên",
        .messagingGroupMembersLoading: "Đang tải thành viên…",
        .messagingGroupOwnerBadge: "Trưởng nhóm",
        .messagingGroupRemoveMember: "Xóa",
        .messagingTapToRetry: "Nhấn để gửi lại",
        .messagingReplyAction: "Trả lời",
        .messagingReplyingTo: "Đang trả lời",
        .messagingReplyCancelAccessibility: "Hủy trả lời",
        .messagingReplyPhoto: "Ảnh",
        .messagingReplyEmpty: "Tin nhắn",
        .messagingReplyUnknownSender: "Thành viên",
        .messagingConversationSentEmoji: "đã gửi emoji",
        .messagingConversationSentImage: "đã gửi 1 ảnh",
        .messagingConversationSentImages: "đã gửi %d ảnh",
        .messagingChatMoreAccessibility: "Tùy chọn cuộc trò chuyện",
        .messagingChatBlockedMessage: "Bạn đã chặn người này.",
        .messagingChatNotFriendsBanner: "Bạn chưa kết bạn với người này.",
        .messagingChatRequestSentBanner: "Đã gửi lời mời kết bạn.",
        .messagingChatRequestReceivedBanner: "Người này muốn kết bạn với bạn.",
        .messagingChatUndoRequest: "Hoàn tác",
        .messagingCopyAction: "Sao chép",
        .messagingDetailsAction: "Chi tiết",
        .messagingMessageDetailsTitle: "Thông tin tin nhắn",
        .messagingMessageDetailsSentAt: "Đã gửi",
        .messagingMessageDetailsReactions: "Cảm xúc",
        .messagingMessageDetailsNoReactions: "Chưa có cảm xúc",
        .messagingMessageDetailsNoContent: "Không có nội dung chữ",

        // Common extras
        .commonClose: "Đóng",
        .commonOK: "OK",
        .commonCancel: "Hủy",
        .commonSave: "Lưu",
        .commonError: "Lỗi",
        .commonSuccess: "Thành công",
        .commonOr: "hoặc",
        .commonMe: "Tôi",
        .commonLoading: "Đang tải...",
        .commonShare: "Chia sẻ",
        .commonNotice: "Thông báo",

        // Messaging compose
        .messagingComposeSearchPlaceholder: "Tìm người dùng hoặc nhóm...",
        .messagingSearchResults: "Kết quả tìm kiếm",
        .messagingComposeDefaultGroupName: "Nhóm chat",
        .messagingImageUploadFailed: "Chưa tải được ảnh lên. Thử lại phát nhé!",
        .messagingReactionEmojiLimit: "Mỗi tin nhắn chỉ được dùng tối đa 5 loại emoji.",

        // Create post / audience
        .feedCreatePostAction: "Đăng",
        .feedCreatePostFailedTitle: "Không thể đăng",
        .feedCreateEditMediaA11y: "Xem và chỉnh sửa ảnh",
        .feedCreateTakePhoto: "Chụp ảnh",
        .feedCreatePickLibrary: "Chọn từ thư viện",
        .feedCreatePickVideo: "Chọn video",
        .feedCreateCaptionPlaceholder: "Viết gì đó về khoảnh khắc này...",
        .feedCreateMoreOptions: "Tùy chọn khác",
        .feedCreateBillCompanionsHint: "Chạm để chọn những người sẽ cùng chia bill với bạn.",
        .feedCreateMomentCompanionsHint: "Chạm để chọn những người có trong khoảnh khắc này.",
        .feedCreateBillWith: "Chia bill cùng với",
        .feedCreateMomentWith: "Khoảnh khắc cùng với",
        .feedCreateLocationHint: "Chạm để thêm địa điểm hoặc nơi check-in.",
        .feedCreateAutoReminder: "Nhắc nhở tự động hàng ngày",
        .feedCreateSearchFriendsGroups: "Tìm bạn bè hoặc nhóm...",
        .feedCreateSearchFriends: "Tìm bạn bè...",
        .feedCreateLocationPlaceholder: "Quán, địa điểm, thành phố...",
        .feedCreateLocationNearby: "Gần bạn",
        .feedCreateLocationSearchResults: "Kết quả tìm kiếm",
        .feedCreateLocationUseTyped: "Dùng “%@”",
        .feedCreateLocationEnableGps: "Bật vị trí để xem địa điểm gần bạn.",
        .feedCreateEqualSplitPreview: "%@ ÷ %d người = %@ / người",
        .feedCreateNeedMedia: "Chọn ít nhất một ảnh hoặc video.",
        .feedCreateBillInvalid: "Kiểm tra lại thông tin chia bill.",
        .feedCreateBillNeedPeople: "Chọn ít nhất một người để chia bill.",
        .feedCreateRetryFailed: "Chưa đăng được bài. Thử lại sau nhé!",
        .feedAudienceTitle: "Ai có thể xem",
        .feedAudienceSection: "Quyền xem",
        .feedAudienceGroups: "Nhóm",
        .feedAudienceGroupsCount: "%d nhóm",
        .feedAudienceUsers: "Người dùng cụ thể",
        .feedAudienceUsersCount: "%d người dùng",
        .feedAudienceFriendsExcept: "Bạn bè ngoại trừ",
        .feedAudienceFriendsExceptCount: "Bạn bè ngoại trừ %d người",
        .feedAudienceFriendsSubtitle: "Chỉ bạn bè của bạn có thể xem bài viết này.",
        .feedAudienceGroupsSubtitle: "Chỉ thành viên trong các nhóm bạn chọn mới xem được.",
        .feedAudienceUsersSubtitle: "Chỉ những người bạn chọn mới xem được bài viết.",
        .feedAudienceExceptSubtitle: "Bạn bè vẫn xem được, trừ những người bạn loại ra.",
        .feedAudiencePickGroups: "Chọn nhóm",
        .feedAudiencePickUsers: "Chọn bạn bè cụ thể",
        .feedAudienceExcludeFriends: "Loại trừ bạn bè",
        .feedAudienceSelected: "Đã chọn",
        .feedAudienceSearchGroups: "Tìm nhóm...",
        .feedAudienceGroupsNotFound: "Không tìm thấy nhóm phù hợp.",
        .feedAudienceFriendsNotFound: "Không tìm thấy bạn bè phù hợp.",
        .feedAudienceSearchExcept: "Tìm bạn bè cần loại trừ...",
        .feedAudienceExceptHint: "Hiển thị sẵn 10 người bạn đầu tiên để bạn loại trừ nhanh.",
        .feedAudienceUsersHint: "Hiển thị sẵn 10 người bạn đầu tiên để chọn nhanh người xem.",
        .feedAudienceNeedGroup: "Chọn ít nhất một nhóm.",
        .feedAudienceNeedUser: "Chọn ít nhất một người dùng cụ thể.",
        .feedAudienceNeedExcept: "Chọn ít nhất một người để loại khỏi danh sách bạn bè.",
        .friendsMemberCount: "%d thành viên",

        // Feed interactions / errors
        .feedPostDelete: "Xóa bài",
        .feedPostDeleteBlockedViews: "Không thể xóa (đã có %d lượt xem)",
        .feedPostDeleteBlockedEvidence: "Không thể xóa (đã có chứng từ thanh toán)",
        .feedPostReport: "Báo cáo",
        .feedPostHide: "Ẩn",
        .feedCommentShowMoreReplies: "Xem thêm %d phản hồi",
        .feedCommentEdited: "· Đã chỉnh sửa",
        .feedCommentRoleAuthor: "Tác giả",
        .feedCommentRoleTagged: "Được gắn thẻ",
        .feedCommentRoleBillHost: "Chủ xị",
        .feedCommentRoleBillPaid: "Đã chuyển tiền",
        .feedCommentRoleBillPendingApproval: "Đã chuyển chờ duyệt",
        .feedCommentRoleBillUnpaid: "Chưa trả tiền",
        .feedCommentRoleBillUnpaidDays: "%d ngày chưa trả",
        .feedCommentDeleted: "Bình luận đã bị xóa",
        .feedCommentReplyingTo: "Đang trả lời ",
        .feedCommentReplyPlaceholder: "Trả lời %@...",
        .feedCommentEmpty: "Nội dung bình luận hoặc ảnh đính kèm không được để trống.",
        .feedMediaCopyImage: "Sao chép ảnh",
        .feedMediaCopied: "Đã sao chép ảnh",
        .timeCompactSeconds: "%d giây",
        .timeCompactMinutes: "%d phút",
        .timeCompactHours: "%d giờ",
        .timeCompactDays: "%d ngày",
        .timeCompactWeeks: "%d tuần",
        .timeCompactMonths: "%d tháng",
        .timeCompactYears: "%d năm",
        .feedUploadFailed: "Đăng thất bại",
        .feedUploadUploading: "Đang tải lên...",
        .feedRefreshFailed: "Chưa làm mới được feed. Thử lại sau nhé!",
        .feedPostStillUploading: "Bài viết đang được đăng.",
        .feedReactionEmojiLimit: "Mỗi bài bạn chỉ được dùng tối đa 5 loại emoji.",
        .feedErrorAccountUnknown: "Không xác định được tài khoản.",
        .feedErrorAccountRefresh: "Không xác định được tài khoản. Hãy thử kéo refresh tab Feed.",
        .feedPostNotFound: "Không tìm thấy bài viết.",
        .feedPostDeleteHasViewers: "Không thể xóa vì đã có người xem bài viết.",
        .feedPostDeleteHasEvidence: "Không thể xóa vì đã có chứng từ thanh toán.",
        .feedAlbumSearchCaption: "Tìm theo caption",
        .feedAlbumPickFriend: "Chọn bạn bè",
        .feedAlbumPickGroup: "Chọn nhóm",
        .feedAlbumPickPeople: "Bạn bè và nhóm",
        .feedAlbumFilterPeople: "Bạn bè và nhóm",
        .feedAlbumSelectedCount: "Đã chọn %d",
        .feedAlbumPeopleEmpty: "Chưa có bạn bè hoặc nhóm",
        .feedAlbumClearFilters: "Xóa bộ lọc",
        .feedAlbumAllFriends: "Tất cả bạn bè",
        .feedAlbumAllGroups: "Tất cả nhóm",

        // Media
        .mediaCameraUnavailable: "Camera không khả dụng",
        .mediaCameraUnavailableHint: "Bạn vẫn có thể chọn ảnh từ thư viện để tiếp tục.",
        .mediaFilterNone: "Gốc",
        .mediaFilterCinematic: "Điện ảnh",
        .mediaFilterVintage: "Cổ điển",
        .mediaFilterVivid: "Rực rỡ",
        .mediaFilterBeauty: "Làm đẹp",
        .mediaFilterAR: "AR",
        .mediaFilterIntensity: "Cường độ",
        .mediaFilterARGlasses: "Kính",
        .mediaFilterARSparkle: "Lấp lánh",
        .mediaFilterARUnsupported: "Thiết bị không có TrueDepth — dùng overlay Vision.",
        .mediaPickFromLibrary: "Chọn từ thư viện ảnh",
        .mediaPreviewTitle: "Xem trước",
        .mediaUsePhoto: "Dùng ảnh này",
        .mediaRetake: "Chụp lại",
        .mediaEdit: "Chỉnh sửa",
        .mediaLibraryTitle: "Thư viện ảnh",
        .mediaConfirmSelectionA11y: "Xác nhận chọn ảnh",
        .mediaSelectedCount: "Đã chọn %d/%d",
        .mediaAddToPostHint: "Bấm ✓ để thêm vào bài viết",
        .mediaAdd: "Thêm",
        .mediaLibraryLoading: "Đang tải thư viện...",
        .mediaLibraryLimitedAccess: "Bạn đang cấp quyền truy cập một phần thư viện.",
        .mediaLibraryEmptyTitle: "Không có ảnh trong thư viện",
        .mediaLibraryEmptyMessage: "Chụp ảnh mới hoặc thêm ảnh vào thư viện.",
        .mediaLibraryPermissionTitle: "Cần quyền truy cập Thư viện ảnh",
        .mediaLibraryPermissionMessage: "Bật quyền trong Cài đặt để chọn ảnh đăng bài.",
        .mediaLoadingSelected: "Đang tải ảnh đã chọn...",
        .mediaTextPlaceholder: "Nhập chữ...",
        .mediaTextDefault: "Nhập chữ",
        .mediaToolCrop: "Cắt",
        .mediaToolDraw: "Vẽ",
        .mediaToolText: "Chữ",
        .mediaToolSticker: "Sticker",
        .mediaTypePhoto: "Ảnh",
        .mediaTypeVideo: "Video",
        .mediaStickerTabWidget: "Widget",
        .mediaStickerTabIcon: "Icon",
        .mediaStickerTabEmoji: "Emoji",
        .mediaStickerTabGif: "GIF",
        .mediaWidgetWeather: "Thời tiết",
        .mediaWidgetClock: "Giờ",
        .mediaWidgetCalendar: "Lịch",
        .mediaWidgetMusic: "Nhạc",
        .mediaWidgetBattery: "Pin",
        .mediaWidgetSteps: "Bước chân",
        .mediaWidgetLocation: "Vị trí",
        .mediaWidgetNote: "Ghi chú",
        .mediaWidgetCountdown: "Đếm ngược",
        .mediaWidgetMood: "Tâm trạng",
        .mediaWidgetQuote: "Trích dẫn",
        .mediaWidgetPhoto: "Ảnh",
        .mediaWidgetNetwork: "Mạng",
        .mediaWidgetReminder: "Nhắc nhở",
        .mediaWidgetStorage: "Bộ nhớ",
        .mediaIconCategoryPopular: "Phổ biến",
        .mediaIconCategoryPeople: "Người",
        .mediaIconCategoryNature: "Thiên nhiên",
        .mediaIconCategoryFood: "Đồ ăn",
        .mediaIconCategoryTravel: "Du lịch",
        .mediaIconCategoryObjects: "Đồ vật",
        .mediaIconCategorySymbols: "Biểu tượng",
        .mediaIconCategoryShapes: "Hình dạng",
        .mediaIconCategoryWeather: "Thời tiết",
        .mediaIconCategorySports: "Thể thao",
        .mediaIconCategoryTech: "Công nghệ",
        .mediaIconCategoryArrows: "Mũi tên",
        .mediaIconCategoryCommunication: "Liên lạc",
        .mediaIconCategoryDevices: "Thiết bị",
        .mediaIconCategoryTransport: "Di chuyển",
        .mediaIconCategoryMedia: "Media",
        .mediaIconCategoryCommerce: "Mua sắm",
        .mediaIconCategoryHealth: "Sức khỏe",
        .mediaEmojiCategoryRecent: "Gần đây",
        .mediaEmojiCategorySmileys: "Cảm xúc",
        .mediaEmojiCategoryPeople: "Người",
        .mediaEmojiCategoryAnimals: "Động vật",
        .mediaEmojiCategoryFood: "Đồ ăn",
        .mediaEmojiCategoryTravel: "Du lịch",
        .mediaEmojiCategoryActivities: "Hoạt động",
        .mediaEmojiCategoryObjects: "Đồ vật",
        .mediaEmojiCategorySymbols: "Biểu tượng",
        .mediaEmojiCategoryFlags: "Cờ",

        // Friends extras
        .friendsSearchEmptyMessage: "Thử tên hoặc username khác.",
        .friendsDirectoryEmptyTitle: "Chưa có bạn bè hoặc nhóm",
        .friendsDirectoryEmptyMessage: "Tìm theo tên hoặc username, quét QR, hoặc tạo nhóm.",
        .friendsGenericError: "Ối, có gì đó chưa ổn.",
        .friendsRequestNotFoundIncoming: "Không tìm thấy lời mời kết bạn. Mở danh sách lời mời đến để làm mới.",
        .friendsRequestNotFoundOutgoing: "Không tìm thấy lời mời kết bạn. Mở danh sách đã gửi để làm mới.",
        .friendsAddUsernamePlaceholder: "vd: namtran",
        .friendsAddMessagePlaceholder: "Xin chào...",
        .friendsAddUsernameRequired: "Nhập username.",
        .friendsAddSuccess: "Đã thêm %@.",
        .friendsJoinCodePlaceholder: "vd: roommates-q7",
        .friendsJoinCodeRequired: "Nhập mã mời nhóm.",
        .friendsJoinSuccess: "Đã tham gia %@.",
        .friendsGroupName: "Tên nhóm",
        .friendsGroupNamePlaceholder: "VD: Chuyến Đà Lạt",
        .friendsGroupDescriptionOptional: "Mô tả (tuỳ chọn)",
        .friendsGroupDescription: "Mô tả",
        .friendsGroupDescriptionPlaceholder: "Mô tả ngắn về nhóm",
        .friendsGroupAvatar: "Ảnh đại diện nhóm",
        .friendsGroupPickPhoto: "Chọn ảnh",
        .friendsGroupNoFriendsToInvite: "Chưa có bạn bè để mời.",
        .friendsImageLoadFailed: "Không tải được ảnh.",
        .friendsGroupNameRequired: "Nhập tên nhóm.",
        .friendsGroupAvatarUploadFailed: "Không tải được ảnh đại diện.",
        .friendsInviteSelectedFailed: "Không mời được thành viên đã chọn.",
        .friendsInvitePartialSkipped: "Một số thành viên đã được bỏ qua.",
        .friendsInviteFailed: "Không mời được thành viên.",
        .friendsGroupCreated: "Đã tạo nhóm %@.",
        .friendsLeaveGroupConfirmTitle: "Rời nhóm?",
        .friendsDeleteGroupConfirmTitle: "Xóa nhóm?",
        .friendsDeleteGroup: "Xóa nhóm",
        .friendsDeleteGroupMessage: "Hành động này không thể hoàn tác. Bạn có chắc muốn xóa nhóm này?",
        .friendsApproveMember: "Duyệt",
        .friendsGroupQR: "Mã QR",
        .friendsGroupCode: "Mã nhóm",
        .friendsTransferOwnership: "Chuyển quyền",
        .friendsGroupCodeCopied: "Đã sao chép mã nhóm.",
        .friendsMemberOwnerMe: "(Trưởng Nhóm, tôi)",
        .friendsMemberOwner: "(Trưởng Nhóm)",
        .friendsMemberMe: "(tôi)",
        .friendsMemberApproved: "Đã duyệt %@",
        .friendsMemberRejected: "Đã từ chối %@",
        .friendsCannotRemoveOwner: "Không thể xóa chủ nhóm",
        .friendsMemberRemoved: "Đã xóa %@ khỏi nhóm",
        .friendsTransferBeforeLeave: "Chuyển quyền chủ nhóm trước khi rời nhóm",
        .friendsGroupQRSecureTitle: "Mã QR nhóm (bảo mật)",
        .friendsGroupQRExpires: "Hết hạn: %@",
        .friendsGroupQRHint: "Bạn bè quét mã để tham gia nhóm.",
        .friendsGroupQRTitle: "Mã QR nhóm",
        .friendsGroupQRGenerating: "Đang tạo mã QR...",
        .friendsGroupQRFailed: "Không thể tạo mã QR",
        .friendsGroupQRSaveFailed: "Không thể lưu ảnh mã QR.",
        .friendsGroupQRSaveNoPermission: "Không có quyền lưu ảnh vào thư viện.",
        .friendsGroupQRSaved: "Đã lưu mã QR vào thư viện ảnh.",
        .friendsInviteSearchUsers: "Tìm người dùng",
        .friendsInviteHint: "Nhập username để mời vào nhóm. Chỉ bạn bè mới được thêm thành công.",
        .friendsAddMembersTitle: "Thêm thành viên",
        .friendsInviteAction: "Mời",
        .friendsInviteUsernamePlaceholder: "Tìm theo username",
        .friendsInviteNotFoundTitle: "Không tìm thấy",
        .friendsInviteNotFoundMessage: "Thử username khác hoặc người này đã trong nhóm.",
        .friendsInviteNeedSelection: "Chọn ít nhất một người.",
        .friendsInviteSuccessCount: "Đã mời %d người vào nhóm.",
        .friendsInviteFailedReason: "Không thể mời (có thể chưa kết bạn).",
        .friendsInviteNone: "Không có ai được mời.",
        .friendsTransferNoMembersTitle: "Không có thành viên",
        .friendsTransferNoMembersMessage: "Cần ít nhất một thành viên khác để chuyển quyền chủ nhóm.",
        .friendsTransferTitle: "Chuyển quyền chủ nhóm",
        .friendsTransferAction: "Chuyển",
        .friendsEditGroupTitle: "Chỉnh sửa nhóm",
        .friendsGroupRemoveMemberAction: "Xóa khỏi nhóm",
        .friendsGroupMemberActionsA11y: "Thao tác thành viên",

        // Auth extras
        .authLoginTagline: "Click moments, Split bills, Keep relations.",
        .authCreateAccountTitle: "Tạo tài khoản",
        .authRegisterSubtitle: "Tham gia cùng bạn bè trên Splick",
        .authPasswordsMismatch: "Mật khẩu không khớp",
        .authDisplayNameRequired: "Cần nhập tên",
        .authDisplayNameTooLong: "Tên quá dài",
        .authVerifyIdentifierFailed: "Không thể xác minh email hoặc số điện thoại.",
        .authGoogleNotConfigured: "Google Sign-In chưa được cấu hình.",
        .authAppleUnavailable: "Đăng nhập bằng Apple không khả dụng.",
        .authIdentifierRequired: "Cần email hoặc số điện thoại",
        .authPasswordRequired: "Cần mật khẩu",
        .authOtpSentEmail: "Đã gửi mã xác minh. Kiểm tra email của bạn.",
        .authOtpSentPhone: "Đã gửi mã xác minh tới điện thoại của bạn.",
        .authSendCodeFailedRetry: "Chưa gửi được mã xác minh. Thử lại phát nhé!",
        .authOtpEmailCodeRequired: "Nhập mã 6 số từ email của bạn",
        .authResetSendFailed: "Không gửi được mã đặt lại",
        .authResetVerifyFailed: "Không xác minh được mã",
        .authResetFailed: "Không đặt lại được mật khẩu",
        .authPasswordRequirementsIntro: "Mật khẩu của bạn cần đáp ứng tất cả điều kiện sau:",
        .authPasswordRequirementsTitle: "Dùng mật khẩu mạnh",
        .authPasswordRuleMinLength: "Ít nhất %d ký tự",
        .authPasswordRuleUppercase: "Một chữ hoa (A–Z)",
        .authPasswordRuleLowercase: "Một chữ thường (a–z)",
        .authPasswordRuleDigit: "Một chữ số (0–9)",
        .authPasswordRuleSpecial: "Một ký tự đặc biệt (!@#$%…)",
        .feedShareFallbackCaption: "Xem bài viết trên Splick",
        .stickersGifPreviewA11y: "Xem trước GIF",
        .profileAvatarLoadFailed: "Không tải được ảnh đã chọn.",
        .profileEditNothingEntered: "Nhập tên hiển thị hoặc chọn ảnh.",
        .profileEditNothingToUpdate: "Không có gì để cập nhật.",

        // Stickers extras
        .stickersSplickCustom: "Splick Custom",
        .stickersGroupCustomEmpty: "Nhóm chưa có sticker tùy chỉnh.",
        .stickersSearchFailedHint: "Thử từ khóa khác hoặc kiểm tra KLIPY_API_KEY.",
        .stickersAddEmojiTitle: "Thêm Emoji",
        .stickersEmojiCropTitle: "Căn vùng emoji",
        .stickersEmojiCropHint: "Kéo để canh, chụm để phóng.",
        .stickersEmojiName: "Tên emoji",
        .stickersEmojiNameHint: "Dấu cách sẽ tự đổi thành _ khi lưu.",
        .stickersEmojiNamePreview: "Tên sẽ được lưu là :%@:",
        .stickersUpload: "Tải lên",
        .stickersYourEmoji: "Emoji của bạn",
        .stickersUploadYourEmoji: "Tải emoji của bạn",
        .stickersPersonalEmojiHint: "Emoji bạn tải lên là emoji cá nhân và dùng được trên các cuộc trò chuyện.",
        .stickersPersonalEmojiEmpty: "Bạn chưa có emoji cá nhân nào.",
        .stickersEmojiNotFound: "Không tìm thấy emoji phù hợp.",
        .stickersEmojiSearch: "Tìm emoji",
        .stickersEmojiSourceA11y: "Nguồn emoji",
        .stickersUploadUnavailable: "Tính năng tải emoji hiện chưa sẵn sàng.",
        .stickersOpenImageFailed: "Không thể mở ảnh đã chọn.",
        .stickersGifDoubleTapSend: "Chạm đúp để gửi",

        // Expense create / categories
        .expenseCreateFailed: "Không tạo được chi tiêu",
        .expenseDescriptionRequired: "Cần nhập mô tả",
        .expenseAmountInvalid: "Nhập số tiền hợp lệ",
        .expenseNeedParticipant: "Chọn ít nhất một người tham gia",
        .expenseCategoryFood: "Đồ ăn & uống",
        .expenseCategoryTransport: "Di chuyển",
        .expenseCategoryHousing: "Nhà ở",
        .expenseCategoryEntertainment: "Giải trí",
        .expenseCategoryShopping: "Mua sắm",
        .expenseCategoryUtilities: "Tiện ích",
        .expenseCategoryTravel: "Du lịch",
        .expenseCategoryGeneral: "Chung",

        // Onboarding / widget
        .onboardingSlide1Title: "Click để lưu khoảnh khắc",
        .onboardingSlide2Title: "Chia bill cùng nhau",
        .onboardingSlide3Title: "Giữ mối quan hệ bạn bè",
        .onboardingCtaHint: "Chạm hoặc vuốt để bắt đầu",
        .onboardingTagline: "Click moments, Split bills, Keep relationship",
        .widgetNoMessages: "Không có tin nhắn",
        .widgetMessagePhoto: "📷 Ảnh",
    ]
}
