enum StringsFeatureEn {
    static let values: [L10nKey: String] = [
        // Feed
        .feedTitle: "Feeds",
        .feedLoading: "Loading your feed...",
        .feedEmptyTitle: "No Posts Yet",
        .feedEmptyMessage: "Share a moment with your friends to get started!",
        .feedEmptyAction: "Take a Photo",
        .feedEndReachedTitle: "You're all caught up",
        .feedEndReachedMessage: "Every post in the feed has been judged. Go touch grass — we'll save more chaos for later.",
        .feedPhotoAlbumAccessibility: "Photo album",
        .feedAlbumTitle: "Collection",
        .feedAlbumLoading: "Loading album...",
        .feedAlbumEmptyTitle: "No photos yet",
        .feedAlbumEmptyMessage: "Photos from your posts will appear here.",

        // Streak
        .feedStreakTitle: "Streak",
        .feedStreakCurrentStreak: "Current streak",
        .feedStreakDays: "days in a row",
        .feedStreakEmptyDay: "No photo",
        .feedStreakNoPhotosToday: "Post a photo today to keep your streak!",
        .feedStreakQuoteZero: "Zero-day streak — your camera requested paid leave.",
        .feedStreakQuoteGrowing: "Just warming up. Don't let your fridge out-streak you.",
        .feedStreakQuoteSolid: "Solid streak — the algorithm still hasn't figured you out.",
        .feedStreakQuoteLegend: "True legend. NASA called but you were busy taking photos.",
        .feedStreakLoading: "Loading streak...",
        .feedStreakError: "Failed to load streak",
        .feedStreakEndOfHistory: "You've reached the end",
        .feedFilterTitle: "Filters",
        .feedFilterNoFriends: "You have no friends yet",
        .feedFilterFriendsNotFound: "No friends found",
        .feedFilterByFriends: "Filter by friends",
        .feedFilterNoGroups: "You haven't joined any groups",
        .feedFilterByGroups: "Filter by groups",
        .feedPostCommentsTitle: "Comments",
        .feedPostCommentsHeader: "Comments",
        .feedPostCommentsEmpty: "No comments yet. Be the first!",
        .feedPostCommentsEmptyEvidence: "No payment evidence yet.",
        .feedPostCommentsLoadMore: "Load more comments",
        .feedPostCommentsFilterComments: "Comments",
        .feedPostCommentsFilterEvidence: "Evidence",
        .feedPostCommentsFilterAll: "All",
        .feedPostViewAllComments: "View all %d comments",
        .feedPostWriteComment: "Write a comment...",
        .feedPostLoadFailed: "Couldn't load this post. Try again?",
        .feedPostUnavailableMessage: "This post is no longer available. It may have been deleted or you no longer have access.",
        .feedCompanionsEmpty: "No companions found",
        .feedCompanionsTitle: "Out with (%d)",
        .feedCompanionsSummary: "Out with %@",
        .feedCompanionsWith: "Out with",
        .feedCompanionsAndOthers: " and %d others",
        .feedCheckInAt: "Checked in at %@",
        .feedViewersTitle: "Viewed by (%d)",
        .feedBillSplitTitle: "Bill split",
        .feedBillRemindAll: "Remind all (%d)",
        .feedBillRemindTitle: "Reminder",
        .feedBillRemindAllTitle: "Remind all",
        .feedBillRemindAllMessage: "Send a reminder to %d people who haven't paid",
        .feedBillPaidAccessibility: "Paid",
        .feedBillRemindUserAccessibility: "Remind %@",
        .feedBillPaidCount: "%d/%d paid",
        .feedBillTotalLabel: "Total",
        .feedBillSettled: "Settled",
        .feedBillUnpaidAccessibility: "Unpaid",
        .feedBillReminderMessageLabel: "Message",
        .feedBillReminderSuggestAnother: "Suggest another message",
        .feedBillReminderSuggest1: "Hey, don't forget to send your share of the bill! 🙏",
        .feedBillReminderSuggest2: "Friendly reminder: I haven't seen your payment for today's bill yet 😅",
        .feedBillReminderSuggest3: "Hello! Please help settle the bill when you can — thanks!",
        .feedBillReminderSuggest4: "The bill is waiting on you — transfer whenever you're free!",
        .feedBillReminderSuggest5: "Team: if you haven't paid the bill yet, please do when you can!",
        .feedBillReminderCooldown: "A reminder was sent recently. Please wait 15 minutes before sending again.",
        .feedBillReminderAlreadyPaid: "This person has already paid their share.",
        .feedBillReminderNoTargets: "No one is eligible for a reminder right now.",
        .feedBillReminderRateLimited: "Daily reminder limit reached. Try again tomorrow.",
        .feedBillReminderSentSingle: "Reminder sent to %@",
        .feedBillReminderSentMultiple: "Reminder sent to %d/%d people",
        .feedPaymentPay: "Pay",
        .feedPaymentPending: "Pending",
        .feedPaymentPaid: "Paid",
        .feedPaymentStatusPaid: "Paid",
        .feedPaymentStatusSubmitEvidence: "Upload transfer screenshot",
        .feedPaymentStatusResubmitEvidence: "Re-upload transfer screenshot",
        .feedPaymentStatusPendingApproval: "Pending approval",
        .feedPaymentStatusHintUnpaid: "Pick a screenshot and submit it for the bill owner to approve.",
        .feedPaymentStatusHintResubmit: "Oh no — your screenshot was rejected. Please upload again.",
        .feedPaymentStatusHintPending: "Your transfer screenshot is waiting for the bill owner to confirm.",
        .feedPaymentStatusHintPaid: "Great — your payment has been confirmed by the bill owner.",
        .feedPaymentEvidenceTitle: "Upload transfer screenshot",
        .feedPaymentEvidenceHint: "Send transfer screenshots to %@ — up to 3 photos.",
        .feedPaymentEvidencePhotosLabel: "Transfer screenshots",
        .feedPaymentEvidenceMessagePlaceholder: "Add a note (optional)",
        .feedPaymentEvidencePickPhoto: "Choose transfer screenshot",
        .feedPaymentEvidenceAddPhoto: "Add photo",
        .feedPaymentEvidenceSubmit: "Submit",
        .feedPaymentEvidenceAttachmentRequired: "Please select at least one transfer screenshot.",
        .feedPaymentEvidenceBadge: "Payment proof",
        .feedPaymentEvidenceApprove: "Approve",
        .feedPaymentEvidenceReject: "Reject",
        .feedPaymentEvidenceRejectReasonPlaceholder: "Reason for rejection",
        .feedPaymentEvidenceStatusApproved: "Accepted",
        .feedPaymentEvidenceStatusRejected: "Declined",
        .feedPaymentEvidenceModerationApproved: "Approved",
        .feedPaymentEvidenceModerationRejected: "Rejected",
        .splickBotProfileTagline: "Professional debt collector · Neon alley certified",
        .splickBotProfileBio: "10 years chasing friends for coffee, boba, and weekend bills. Motto: \"Pay up or get @mentioned forever.\" 99.9% recovery rate on debts under $2 — the last $2 is still negotiating with a boba cup.",
        .splickBotStatReminders: "Reminders sent",
        .splickBotStatRecovery: "Recovery rate",
        .splickBotStatExperience: "Experience",
        .splickBotStatRecoveryValue: "99.9%",
        .splickBotStatExperienceValue: "10 yrs",
        .feedReactionsTitle: "Reactions",
        .feedReactionsCount: "%d reactions",
        .feedReactionsMore: "+%d others",
        .feedReactionsNone: "No reactions yet",
        .feedCreateTitle: "New post",
        .feedCreatePosting: "Posting...",
        .feedCreateAddMedia: "Add media",
        .feedCreateMediaLimit: "Up to 5 photos and 3 videos",
        .feedCreateCaption: "Caption",
        .feedCreateTagFriends: "Tag friends",
        .feedCreateTagFriendsHint: "Tag friends to split the bill with others.",
        .feedCreateFriendsNotFound: "No friends found",
        .feedCreateLocation: "Location",
        .feedCreateTotalAmount: "Total amount",
        .feedCreateCurrencySymbol: "₫",
        .feedMentionSuggestions: "Friend suggestions",
        .feedEmojiPickerTitle: "Choose emoji",
        .feedEmojiPickerQuickBarTitle: "Quick bar",
        .feedEmojiPickerQuickBarHint: "Tap a slot, then pick an emoji below to assign. Tap an emoji to react instantly.",
        .feedEmojiPickerAllTitle: "All emojis",
        .feedEmojiPickerHint: "The iPhone emoji keyboard appears when you tap the field above.",
        .feedEmojiPickerCustomTabTitle: "Group",
        .feedCustomEmojiAddAction: "Add",
        .feedCustomEmojiUploadTitle: "Group emoji",
        .feedCustomEmojiUploadSectionTitle: "Upload new emoji",
        .feedCustomEmojiChoosePhoto: "Choose photo",
        .feedCustomEmojiShortcodePlaceholder: "Shortcode (e.g. cho_vay)",
        .feedCustomEmojiUploadAction: "Upload emoji",
        .feedCustomEmojiExistingTitle: "Group emojis",
        .feedCustomEmojiEmpty: "No custom emojis yet. Upload one for your group.",
        .stickersGifSearchPlaceholder: "Search KLIPY",
        .stickersTryAlso: "Try also:",
        .stickersCategories: "Categories",
        .stickersTrendingTerms: "Trending",
        .stickersPopular: "Popular stickers",
        .stickersFavorites: "Favorites",
        .stickersEmoji: "Emoji",
        .stickersSearch: "Search",
        .stickersCustomPack: "Custom",
        .stickersQuickAccess: "Quick access",
        .stickersHashtags: "Hashtags",
        .stickersFavoritesEmpty: "No favorite stickers yet. Tap a GIF to save it here.",
        .stickersRemoveFavorite: "Remove from favorites",
        .stickersAddFavorite: "Add to favorites",
        .stickersNoResultsTitle: "No stickers",
        .feedProfileMessage: "Message",
        .feedProfileAddFriend: "Add friend",
        .profileLoading: "Loading profile…",
        .profileRetry: "Try again",
        .profilePostsLoading: "Loading posts…",
        .profilePostsTitle: "Posts",
        .profilePostsEmptyTitle: "No posts yet",
        .profilePostsEmptyMessage: "Posts shared by this person will appear here.",
        .postPreviewAccessibility: "Post preview",
        .profileStatFriends: "Friends",
        .profileStatPosts: "Posts",
        .profileStatGroups: "Groups",
        .profilePaymentManage: "Receive money",
        .profilePaymentTitle: "Payment QR",
        .profilePaymentQrSection: "QR code image",
        .profilePaymentBankSection: "Bank account",
        .profilePaymentAccountName: "Account holder name",
        .profilePaymentAccountNumber: "Account number",
        .profilePaymentBankName: "Bank",
        .profilePaymentSave: "Save",
        .profilePaymentDelete: "Remove payment info",
        .profilePaymentDeleteConfirm: "Remove your payment QR and bank details?",
        .profilePaymentUploadQr: "Upload QR image",
        .profilePaymentFriendSection: "Receive money",
        .profilePaymentEmptySelf: "No payment info yet. Tap Receive money to add your QR or bank details.",
        .profilePaymentEmptyFriend: "This friend hasn't added payment info yet.",
        .profilePaymentShare: "Share",
        .profilePaymentSaveImage: "Save image",
        .profilePaymentImageSaved: "Image saved to Photos",
        .profilePaymentImageSaveFailed: "Couldn't save image. Check Photos permission and try again.",

        // Friends
        .friendsTitle: "Friends",
        .friendsListTitle: "Friends list",
        .friendsTabFriends: "Friends",
        .friendsTabGroups: "Groups",
        .friendsIncomingRequests: "Friend requests (%d)",
        .friendsOutgoingRequests: "Sent requests (%d)",
        .friendsOutgoingRequestsPlain: "Sent requests",
        .friendsBlockedUsers: "Blocked users",
        .friendsAddFriendTitle: "Add friend",
        .friendsUsername: "Username",
        .friendsMessageOptional: "Message (optional)",
        .friendsJoinGroupTitle: "Join group",
        .friendsGroupInviteCode: "Group invite code",
        .friendsJoinGroupAction: "Join group",
        .friendsScanGroupQR: "Scan QR code",
        .friendsRelationFriend: "Friends",
        .friendsRelationSent: "Sent",
        .friendsAccept: "Accept",
        .friendsAddFriendAction: "Add friend",
        .friendsRecallRequest: "Recall",
        .friendsReject: "Reject",
        .friendsCancel: "Cancel",
        .friendsClose: "Close",
        .friendsMyQRTitle: "My QR code",
        .friendsMyQRHint: "Friends scan this code to send you a friend request on Splick.",
        .friendsMyQRRefresh: "Refresh code",
        .friendsMyQRShare: "Share code",
        .friendsMyQRGenerating: "Generating QR code...",
        .friendsMyQRFailed: "Could not generate QR code",
        .friendsMyQRVersion: "Code version %d",
        .friendsMyQRPreviewTitle: "My QR code",
        .friendsMyQRPreviewHint: "Tap to enlarge or share",
        .friendsScanQRAddFriend: "Scan QR code",
        .friendsScanQRJoinGroup: "Scan group code",
        .friendsScanQRUnified: "Scan QR code",
        .friendsCreateGroup: "Create group",
        .friendsSearchPlaceholder: "Search name, username, or group code",
        .friendsJoinGroupByCode: "Join group",
        .friendsScanSimulatorHint: "The Simulator has no camera. Use a real device to scan, or pick a photo from your album below.",
        .friendsScanQRFromAlbum: "Scan QR from photo album",
        .friendsScanQRFromAlbumFailed: "No QR code was found in this photo.",
        .friendsScanManualHint: "Or paste a code manually",
        .friendsScanUseCode: "Use this code",
        .friendsIncomingTitle: "Friend requests",
        .friendsIncomingLoading: "Loading requests...",
        .friendsIncomingEmptyTitle: "No pending requests",
        .friendsIncomingEmptyMessage: "When someone sends you a friend request, it will appear here.",
        .friendsOutgoingTitle: "Sent requests",
        .friendsOutgoingLoading: "Loading sent requests...",
        .friendsOutgoingEmptyTitle: "No sent requests",
        .friendsOutgoingEmptyMessage: "Friend requests you send will appear here until they accept or you cancel.",
        .friendsBlockedTitle: "Blocked users",
        .friendsBlockedLoading: "Loading blocked users...",
        .friendsBlockedEmptyTitle: "No blocked users",
        .friendsBlockedEmptyMessage: "Users you block will appear here. You can unblock them anytime.",
        .friendsPeopleYouMayKnowTitle: "People you may know",
        .friendsPeopleYouMayKnowLoading: "Finding suggestions...",
        .friendsPeopleYouMayKnowEmptyTitle: "No suggestions right now",
        .friendsPeopleYouMayKnowEmptyMessage: "Join a group or invite friends — we'll suggest people from shared groups.",
        .friendsPeopleYouMayKnowSharedGroup: "Same group · %@",
        .friendsUnblock: "Unblock",
        .friendsSetNickname: "Set nickname",
        .friendsRemoveFriend: "Remove friend",
        .friendsBlockUser: "Block user",
        .friendsNicknameTitle: "Nickname",
        .friendsNicknamePlaceholder: "Nickname (only you see this)",
        .friendsRemoveFriendConfirmTitle: "Remove friend?",
        .friendsRemoveFriendConfirmAction: "Remove friend",
        .friendsBlockConfirmTitle: "Block this user?",
        .friendsBlockConfirmAction: "Block",
        .friendsGroupPending: "Pending approval (%d)",
        .friendsGroupMembers: "Members (%d)",
        .friendsGroupMemberCount: "Group · %d members",
        .friendsGroupInviteCodeLabel: "Invite code: %@",

        // Expense
        .expenseTitle: "Expenses",
        .expenseLoading: "Loading expenses...",
        .expenseEmptyTitle: "No Expenses",
        .expenseEmptyMessage: "Create your first shared expense to start splitting bills.",
        .expenseEmptyAction: "Add Expense",
        .expenseFilteredEmptyTitle: "No matching expenses",
        .expenseFilteredEmptyMessage: "Try changing filters or clearing them.",
        .expenseYouAreOwed: "Others owe you",
        .expenseYouOwe: "You owe others",
        .expenseOverviewOwedPeopleCount: "%d people owe you",
        .expenseOverviewOwingPeopleCount: "You owe %d people",
        .expenseOverviewFilterHint: "Tap to filter the expense list",
        .expenseOverviewSectionTitle: "Expense overview",
        .expenseOverviewExpandHint: "Tap to expand",
        .expenseOverviewCollapseHint: "Tap to collapse",
        .expenseOverviewExpandedAccessibility: "Expanded",
        .expenseOverviewCollapsedAccessibility: "Collapsed",
        .expenseRecordsSectionTitle: "Expense history",
        .expenseRecordsSectionThisWeek: "( this week )",
        .expenseRecordsSectionThisMonth: "( this month )",
        .expenseRecordsSectionAllTime: "( all time )",
        .expenseRowCreatorLabel: "host",
        .expenseRowPaidByMe: "( me )",
        .expenseRowPayVerb: "You pay",
        .expenseRowReceiveVerb: "You receive",
        .expenseRowShareVerb: "You",
        .expenseRowOfConnector: "of total",
        .expenseFilterPanelTitle: "Filters",
        .expenseFilterOpenAccessibility: "Open expense filters",
        .expenseFilterPresetWeek: "This week",
        .expenseFilterPresetMonth: "This month",
        .expenseFilterPresetAll: "All time",
        .expensePaidBy: "Paid by %@",
        .expenseCreatedAt: "Created %@",
        .expenseSettledAt: "Settled %@",
        .expenseStatusPending: "Pending",
        .expenseStatusPartial: "Partial",
        .expenseStatusSettled: "Settled",
        .expenseFilterSearchCaption: "Search by caption",
        .expenseFilterMore: "More filters",
        .expenseFilterClear: "Clear filters",
        .expenseFilterStatus: "Status",
        .expenseFilterFriends: "Friends",
        .expenseFilterSearchFriends: "Search friends",
        .expenseFilterNoFriends: "No friends found",
        .expenseFilterDateRange: "Date range",
        .expenseFilterFrom: "From",
        .expenseFilterTo: "To",
        .expenseFilterAnyTime: "Any time",
        .expenseFilterFromDate: "From date",
        .expenseFilterToDate: "To date",
        .expenseDebtAll: "All",
        .expenseDebtOweUnpaid: "I owe · unpaid",
        .expenseDebtOwePaid: "I owe · paid",
        .expenseDebtOwedUnpaid: "Owed to me · unpaid",
        .expenseDebtOwedPaid: "Owed to me · paid",
        .expenseOverviewOweUnpaidCount: "%d expenses",
        .expenseOverviewOwePaidCount: "%d expenses",
        .expenseOverviewOwedUnpaidCount: "%d expenses",
        .expenseOverviewOwedPaidCount: "%d expenses",
        .expenseOverviewUnpaid: "Unpaid",
        .expenseOverviewPaid: "Paid",
        .expenseOverviewEmptyChart: "No debts",
        .expenseRowDescOweUnpaidLead: "You haven't paid ",
        .expenseRowDescOwePaidLead: "You paid ",
        .expenseRowDescOwedUnpaidTail: " still owe you",
        .expenseRowDescOwedPaidTail: " paid you",
        .expenseRowDescNeutral: "You created this expense",
        .expenseCreateTitle: "New Expense",
        .expenseCreateHowMuch: "How much?",
        .expenseCreateDescription: "What's this for?",
        .expenseCreateCategory: "Category",
        .expenseCreateSplitType: "Split Type",
        .expenseCreateAction: "Create Expense",
        .expenseSplitEqual: "Split Equally",
        .expenseSplitExact: "Exact Amounts",
        .expenseSplitPercentage: "By Percentage",
        .expenseRowPaidAccessibility: "Paid",
        .expenseRowUnpaidAccessibility: "Not paid yet",
        .expenseModeAll: "All Expenses",
        .expenseModeHistory: "History",
        .expenseModeOverview: "Overview",
        .expenseModeFriends: "Friends",
        .expenseOverviewIncome: "Income",
        .expenseOverviewExpenditure: "Expenditure",
        .expenseOverviewThisMonth: "This month",
        .expenseOverviewTodayTitle: "Today's overview",
        .expenseOverviewTodayBalanced: "No balance today",
        .expenseOverviewChartTitle: "Last 12 months",
        .expenseOverviewDebtSectionTitle: "Outstanding debts",
        .expenseFriendsTitle: "Expenses by friend",
        .expenseFriendsLoading: "Loading friends...",
        .expenseFriendsEmptyTitle: "No friend balances",
        .expenseFriendsEmptyMessage: "Shared expenses with friends will appear here.",
        .expenseFriendYouOwe: "You owe",
        .expenseFriendOwesYou: "Owes you",
        .expenseFriendSettled: "Settled up",
        .expenseFriendDetailTitle: "Friend expenses",
        .expenseFriendSummary: "Net summary",
        .expenseFriendNetAmount: "Net amount",
        .expenseFriendExpenseCount: "%d expenses",
        .expenseFriendSplitCount: "%d unpaid splits",
        .expenseFriendWaiting: "Waiting for your friend to settle",
        .expenseFriendQuickSettle: "Settle net balance",
        .expenseFriendLoadMore: "Load more",
        .expenseBulkTitle: "Settle balance",
        .expenseBulkEvidence: "Payment evidence",
        .expenseBulkChooseEvidence: "Choose image or screenshot",
        .expenseBulkNote: "Add a note (optional)",
        .expenseBulkSubmit: "Submit for approval",
        .expenseBulkUploading: "Uploading evidence...",
        .expenseBulkSubmitting: "Submitting settlement...",
        .expenseBulkPending: "Pending approval",
        .expenseBulkSuccess: "Settlement submitted for approval.",
        .expenseBulkEvidenceRequired: "Choose payment evidence before submitting.",
        .expenseBulkApprove: "Approve",
        .expenseBulkReject: "Reject",
        .expenseBulkRejectReason: "Reason (optional)",

        // Notification
        .notificationTitle: "Notifications",
        .notificationLoading: "Loading notifications...",
        .notificationEmptyTitle: "No Notifications",
        .notificationEmptyMessage: "You're all caught up! Notifications will appear here.",
        .notificationFilterAll: "All",
        .notificationFilterExpenses: "Expenses",
        .notificationFilterFriends: "Friends",
        .notificationFilterPosts: "Posts",
        .notificationFilterEmptyTitle: "No matching notifications",
        .notificationFilterEmptyMessage: "Try another filter or check back later.",
        .notificationReadAll: "Read All",
        .notificationFriendRequestAccepted: "Accepted",
        .notificationFriendRequestRejected: "Declined",
        .notificationSectionToday: "Today",
        .notificationSectionYesterday: "Yesterday",
        .notificationSectionPastWeek: "Past week",
        .notificationSectionPastMonth: "Past month",
        .notificationSectionPastYear: "Past year",
        .notificationInboxTitle: "Inbox",
        .notificationInboxEmpty: "No notifications yet",
        .notificationBellAccessibility: "Notifications",

        // Tab
        .tabMessages: "Messages",

        // Messaging
        .messagingTitle: "Messages",
        .messagingLoading: "Loading messages...",
        .messagingEmptyTitle: "No Conversations",
        .messagingEmptyMessage: "Search for a friend above to start chatting.",
        .messagingNewConversation: "New Message",
        .messagingInputPlaceholder: "Message...",
        .messagingSend: "Send",
        .messagingYou: "You",
        .messagingChatLoading: "Loading messages...",
        .messagingChatEmptyTitle: "No messages yet",
        .messagingChatEmptyMessage: "Say hello!",
        .messagingConversationPeekEmpty: "No messages to preview.",
        .messagingConversationPeekError: "Couldn’t load this preview.",
        .messagingConversationPeekA11y: "Conversation preview",
        .messagingSelectFriend: "Select a friend to message",
        .messagingSearchPlaceholder: "Search messages and people",
        .messagingSearchLoading: "Searching...",
        .messagingSearchEmptyTitle: "No results found",
        .messagingSearchEmptyMessage: "Try another name, username, or message.",
        .messagingFilterGroups: "Groups",
        .messagingFilterUsers: "People",
        .messagingFilterUnread: "Unread",
        .messagingFilterCloseFriends: "Close friends",
        .messagingFilterComingSoon: "Coming soon",
        .messagingFilterEmptyGroupsTitle: "No group chats",
        .messagingFilterEmptyGroupsMessage: "Create a group or clear the filter to see all conversations.",
        .messagingFilterEmptyUsersTitle: "No direct chats",
        .messagingFilterEmptyUsersMessage: "Start a new message or clear the filter to see all conversations.",
        .messagingFilterEmptyUnreadTitle: "All caught up",
        .messagingFilterEmptyUnreadMessage: "You have no unread conversations right now.",
        .messagingStartConversationError: "Unable to start conversation",
        .messagingBellAccessibility: "Notifications",
        .messagingMessageButton: "Message",
        .messagingCreateGroupTitle: "Create group",
        .messagingGroupNamePlaceholder: "Group name",
        .messagingGroupMembersTitle: "Members",
        .messagingGroupNoFriends: "Add friends first to create a group.",
        .messagingGroupChatRequiresMembers: "Select at least one member to open the group chat.",
        .messagingLeaveGroup: "Leave group",
        .messagingLeaveGroupConfirmTitle: "Leave this group?",
        .messagingGroupChangeAvatar: "Change group photo",
        .messagingGroupChangeAvatarHint: "Choose a new photo for the group.",
        .messagingGroupChangeAvatarLoadError: "Couldn't load the selected photo.",
        .messagingGroupChangeName: "Change group name",
        .messagingGroupManageMembers: "Manage members",
        .messagingGroupMembersLoading: "Loading members…",
        .messagingGroupOwnerBadge: "Owner",
        .messagingGroupRemoveMember: "Remove",
        .messagingTapToRetry: "Tap to retry",
        .messagingReplyAction: "Reply",
        .messagingReplyingTo: "Replying to",
        .messagingReplyCancelAccessibility: "Cancel reply",
        .messagingReplyPhoto: "Photo",
        .messagingReplyEmpty: "Message",
        .messagingReplyUnknownSender: "Member",
        .messagingConversationSentEmoji: "sent an emoji",
        .messagingConversationSentImage: "sent 1 photo",
        .messagingConversationSentImages: "sent %d photos",
        .messagingChatMoreAccessibility: "Conversation options",
        .messagingChatSearchMessages: "Search messages",
        .messagingChatSearchPlaceholder: "Search in conversation",
        .messagingChatSearchHint: "Enter at least 2 characters to search.",
        .messagingChatMuteNotifications: "Mute notifications",
        .messagingChatNotificationSounds: "Notifications and sounds",
        .messagingChatNotificationsToggle: "Notifications",
        .messagingChatNotificationBell: "Notification sound",
        .messagingChatNotificationSoundDefault: "Default",
        .messagingChatNotificationSoundNote: "Note",
        .messagingChatNotificationSoundChime: "Chime",
        .messagingChatNotificationSoundPop: "Pop",
        .messagingChatNotificationSoundSilent: "Silent",
        .messagingChatDeleteConversation: "Delete chat",
        .messagingChatDeleteConversationConfirmTitle: "Delete this chat?",
        .messagingChatDeleteConversationConfirmMessage: "The chat will be removed from your inbox. New messages will make it appear again.",
        .messagingChatBlockedMessage: "You blocked this user.",
        .messagingChatNotFriendsBanner: "You're not friends with this person.",
        .messagingChatRequestSentBanner: "Friend request sent.",
        .messagingChatRequestReceivedBanner: "This person wants to be your friend.",
        .messagingChatUndoRequest: "Undo",
        .messagingChatTyping: "Composing...",
        .messagingChatTypingNamed: "%@ is composing...",
        .messagingChatTypingTwo: "%@ and %@ are composing...",
        .messagingChatTypingOthers: "%@, %@, and others are composing...",
        .messagingCopyAction: "Copy",
        .messagingDetailsAction: "Details",
        .messagingMessageDetailsTitle: "Message info",
        .messagingMessageDetailsSentAt: "Sent",
        .messagingMessageDetailsReactions: "Reactions",
        .messagingMessageDetailsNoReactions: "No reactions yet",
        .messagingMessageDetailsNoContent: "No text content",

        // Common extras
        .commonClose: "Close",
        .commonOK: "OK",
        .commonCancel: "Cancel",
        .commonSave: "Save",
        .commonError: "Error",
        .commonSuccess: "Success",
        .commonOr: "or",
        .commonMe: "Me",
        .commonLoading: "Loading...",
        .commonShare: "Share",
        .commonNotice: "Notice",

        // Messaging compose
        .messagingComposeSearchPlaceholder: "Search people or groups...",
        .messagingSearchResults: "Search results",
        .messagingComposeDefaultGroupName: "Group chat",
        .messagingImageUploadFailed: "Couldn't upload that photo. Try again?",
        .messagingReactionEmojiLimit: "You can use up to 5 emoji types per message.",

        // Create post / audience
        .feedCreatePostAction: "Post",
        .feedCreatePostFailedTitle: "Couldn't post",
        .feedCreateEditMediaA11y: "View and edit photo",
        .feedCreateTakePhoto: "Take photo",
        .feedCreatePickLibrary: "Choose from library",
        .feedCreatePickVideo: "Choose video",
        .feedCreateCaptionPlaceholder: "Write something about this moment...",
        .feedCreateMoreOptions: "More options",
        .feedCreateBillCompanionsHint: "Tap to choose who will split the bill with you.",
        .feedCreateMomentCompanionsHint: "Tap to choose who was in this moment.",
        .feedCreateBillWith: "Split bill with",
        .feedCreateMomentWith: "Moment with",
        .feedCreateLocationHint: "Tap to add a place or check-in.",
        .feedCreateAutoReminder: "Daily automatic reminders",
        .feedCreateSearchFriendsGroups: "Search friends or groups...",
        .feedCreateSearchFriends: "Search friends...",
        .feedCreateLocationPlaceholder: "Cafe, place, city...",
        .feedCreateLocationNearby: "Nearby",
        .feedCreateLocationSearchResults: "Search results",
        .feedCreateLocationUseTyped: "Use “%@”",
        .feedCreateLocationEnableGps: "Turn on location to see places near you.",
        .feedCreateEqualSplitPreview: "%@ ÷ %d people = %@ / person",
        .feedCreateNeedMedia: "Select at least one photo or video.",
        .feedCreateBillInvalid: "Please check the bill split details.",
        .feedCreateBillNeedPeople: "Select at least one person to split the bill with.",
        .feedCreateRetryFailed: "Couldn't post that. Try again in a bit!",
        .feedAudienceTitle: "Who can see this",
        .feedAudienceSection: "Visibility",
        .feedAudienceGroups: "Groups",
        .feedAudienceGroupsCount: "%d groups",
        .feedAudienceUsers: "Specific people",
        .feedAudienceUsersCount: "%d people",
        .feedAudienceFriendsExcept: "Friends except",
        .feedAudienceFriendsExceptCount: "Friends except %d people",
        .feedAudienceFriendsSubtitle: "Only your friends can see this post.",
        .feedAudienceGroupsSubtitle: "Only members of the groups you choose can see it.",
        .feedAudienceUsersSubtitle: "Only the people you choose can see this post.",
        .feedAudienceExceptSubtitle: "Friends can see it, except people you exclude.",
        .feedAudiencePickGroups: "Select groups",
        .feedAudiencePickUsers: "Select specific friends",
        .feedAudienceExcludeFriends: "Exclude friends",
        .feedAudienceSelected: "Selected",
        .feedAudienceSearchGroups: "Search groups...",
        .feedAudienceGroupsNotFound: "No matching groups found.",
        .feedAudienceFriendsNotFound: "No matching friends found.",
        .feedAudienceSearchExcept: "Search friends to exclude...",
        .feedAudienceExceptHint: "Showing your first 10 friends for quick exclusion.",
        .feedAudienceUsersHint: "Showing your first 10 friends for quick selection.",
        .feedAudienceNeedGroup: "Select at least one group.",
        .feedAudienceNeedUser: "Select at least one specific person.",
        .feedAudienceNeedExcept: "Select at least one person to exclude from friends.",
        .friendsMemberCount: "%d members",

        // Feed interactions / errors
        .feedPostDelete: "Delete post",
        .feedPostDeleteBlockedViews: "Can't delete (already has %d views)",
        .feedPostDeleteBlockedEvidence: "Can't delete (payment proof already submitted)",
        .feedPostReport: "Report",
        .feedPostEdit: "Edit",
        .feedPostEdited: "Edited",
        .feedPostEditHistory: "Edit history",
        .feedPostEditHistoryEmpty: "No previous versions.",
        .feedCommentShowMoreReplies: "View %d more replies",
        .feedCommentEdited: "· Edited",
        .feedCommentRoleAuthor: "Author",
        .feedCommentRoleTagged: "Tagged",
        .feedCommentRoleBillHost: "Host",
        .feedCommentRoleBillPaid: "Paid",
        .feedCommentRoleBillPendingApproval: "Pending approval",
        .feedCommentRoleBillUnpaid: "Unpaid",
        .feedCommentRoleBillUnpaidDays: "%d days unpaid",
        .feedCommentDeleted: "Comment deleted",
        .feedCommentReplyingTo: "Replying to ",
        .feedCommentReplyPlaceholder: "Reply to %@...",
        .feedCommentEmpty: "Comment text or attachment can't be empty.",
        .feedMediaCopyImage: "Copy image",
        .feedMediaCopied: "Image copied",
        .timeCompactSeconds: "%ds",
        .timeCompactMinutes: "%dm",
        .timeCompactHours: "%dh",
        .timeCompactDays: "%dd",
        .timeCompactWeeks: "%dw",
        .timeCompactMonths: "%dmo",
        .timeCompactYears: "%dy",
        .feedUploadFailed: "Upload failed",
        .feedUploadUploading: "Uploading...",
        .feedRefreshFailed: "Couldn't refresh the feed. Try again later!",
        .feedPostStillUploading: "This post is still being uploaded.",
        .feedReactionEmojiLimit: "You can use up to 5 emoji types per post.",
        .feedErrorAccountUnknown: "Couldn't identify your account.",
        .feedErrorAccountRefresh: "Couldn't identify your account. Pull to refresh the Feed tab.",
        .feedPostNotFound: "Post not found.",
        .feedPostDeleteHasViewers: "Can't delete because someone has already viewed this post.",
        .feedPostDeleteHasEvidence: "Can't delete because payment proof has already been submitted.",
        .feedAlbumSearchCaption: "Search by caption",
        .feedAlbumPickFriend: "Select friends",
        .feedAlbumPickGroup: "Select groups",
        .feedAlbumPickPeople: "Friends & groups",
        .feedAlbumFilterPeople: "Friends and groups",
        .feedAlbumSelectedCount: "%d selected",
        .feedAlbumPeopleEmpty: "No friends or groups yet",
        .feedAlbumClearFilters: "Clear filters",
        .feedAlbumAllFriends: "All friends",
        .feedAlbumAllGroups: "All groups",

        // Media
        .mediaCameraUnavailable: "Camera unavailable",
        .mediaCameraUnavailableHint: "You can still choose photos from your library to continue.",
        .mediaFilterNone: "Original",
        .mediaFilterCinematic: "Cinematic",
        .mediaFilterVintage: "Vintage",
        .mediaFilterVivid: "Vivid",
        .mediaFilterFade: "Fade",
        .mediaFilterBlackAndWhite: "B&W",
        .mediaFilterWarm: "Warm",
        .mediaFilterCool: "Cool",
        .mediaFilterBeauty: "Beauty",
        .mediaFilterAR: "AR",
        .mediaFilterIntensity: "Intensity",
        .mediaFilterARGlasses: "Glasses",
        .mediaFilterARSparkle: "Sparkle",
        .mediaFilterARUnsupported: "AR face tracking needs a TrueDepth camera. Showing a Vision overlay instead.",
        .mediaPickFromLibrary: "Choose from photo library",
        .mediaPreviewTitle: "Preview",
        .mediaUsePhoto: "Use this photo",
        .mediaRetake: "Retake",
        .mediaEdit: "Edit",
        .mediaLibraryTitle: "Photo library",
        .mediaConfirmSelectionA11y: "Confirm photo selection",
        .mediaSelectedCount: "Selected %d/%d",
        .mediaAddToPostHint: "Tap ✓ to add to your post",
        .mediaAdd: "Add",
        .mediaLibraryLoading: "Loading library...",
        .mediaLibraryLimitedAccess: "You currently have limited library access.",
        .mediaLibraryEmptyTitle: "No photos in library",
        .mediaLibraryEmptyMessage: "Take a new photo or add photos to your library.",
        .mediaLibraryPermissionTitle: "Photo library access needed",
        .mediaLibraryPermissionMessage: "Enable access in Settings to choose photos for your post.",
        .mediaLoadingSelected: "Loading selected photos...",
        .mediaTextPlaceholder: "Enter text...",
        .mediaTextDefault: "Enter text",
        .mediaToolCrop: "Crop",
        .mediaToolRotate: "Rotate",
        .mediaToolFilter: "Filter",
        .mediaToolAdjust: "Adjust",
        .mediaToolDraw: "Draw",
        .mediaToolText: "Text",
        .mediaToolSticker: "Sticker",
        .mediaToolAudio: "Audio",
        .mediaToolEffects: "Effects",
        .mediaToolMention: "Mention",
        .mediaToolDownload: "Download",
        .mediaToolMore: "More",
        .mediaEditorCaptionPlaceholder: "Add a caption…",
        .mediaEditorPostPill: "Post",
        .mediaEditorCloseFriendsPill: "Close Friends",
        .mediaEditorComingSoon: "Coming soon",
        .mediaEditorSavedToGallery: "Saved to gallery",
        .mediaEditorDiscardTitle: "Discard edits?",
        .mediaEditorDiscardMessage: "If you go back now, you will lose your edits.",
        .mediaCameraModePost: "POST",
        .mediaCameraModeStory: "STORY",
        .mediaCameraModeReels: "REELS",
        .mediaCameraToolText: "Create",
        .mediaCameraToolBoomerang: "Boomerang",
        .mediaCameraToolLayout: "Layout",
        .mediaCameraToolHandsFree: "Hands-free",
        .mediaCameraTimerSeconds: "%d s",
        .mediaLoadFailed: "Could not load photo.",
        .mediaCropReset: "Reset crop",
        .mediaCropOriginal: "Original",
        .mediaCropFree: "Free",
        .mediaAdjustBrightness: "Brightness",
        .mediaAdjustContrast: "Contrast",
        .mediaAdjustSaturation: "Saturation",
        .mediaAdjustExposure: "Exposure",
        .mediaTypePhoto: "Photo",
        .mediaTypeVideo: "Video",
        .mediaStickerTabWidget: "Widget",
        .mediaStickerTabIcon: "Icon",
        .mediaStickerTabEmoji: "Emoji",
        .mediaStickerTabGif: "GIF",
        .mediaWidgetWeather: "Weather",
        .mediaWidgetClock: "Clock",
        .mediaWidgetCalendar: "Calendar",
        .mediaWidgetMusic: "Music",
        .mediaWidgetBattery: "Battery",
        .mediaWidgetSteps: "Steps",
        .mediaWidgetLocation: "Location",
        .mediaWidgetNote: "Note",
        .mediaWidgetCountdown: "Countdown",
        .mediaWidgetMood: "Mood",
        .mediaWidgetQuote: "Quote",
        .mediaWidgetPhoto: "Photo",
        .mediaWidgetNetwork: "Network",
        .mediaWidgetReminder: "Reminder",
        .mediaWidgetStorage: "Storage",
        .mediaIconCategoryPopular: "Popular",
        .mediaIconCategoryPeople: "People",
        .mediaIconCategoryNature: "Nature",
        .mediaIconCategoryFood: "Food",
        .mediaIconCategoryTravel: "Travel",
        .mediaIconCategoryObjects: "Objects",
        .mediaIconCategorySymbols: "Symbols",
        .mediaIconCategoryShapes: "Shapes",
        .mediaIconCategoryWeather: "Weather",
        .mediaIconCategorySports: "Sports",
        .mediaIconCategoryTech: "Tech",
        .mediaIconCategoryArrows: "Arrows",
        .mediaIconCategoryCommunication: "Communication",
        .mediaIconCategoryDevices: "Devices",
        .mediaIconCategoryTransport: "Transport",
        .mediaIconCategoryMedia: "Media",
        .mediaIconCategoryCommerce: "Shopping",
        .mediaIconCategoryHealth: "Health",
        .mediaEmojiCategoryRecent: "Recent",
        .mediaEmojiCategorySmileys: "Smileys",
        .mediaEmojiCategoryPeople: "People",
        .mediaEmojiCategoryAnimals: "Animals",
        .mediaEmojiCategoryFood: "Food",
        .mediaEmojiCategoryTravel: "Travel",
        .mediaEmojiCategoryActivities: "Activities",
        .mediaEmojiCategoryObjects: "Objects",
        .mediaEmojiCategorySymbols: "Symbols",
        .mediaEmojiCategoryFlags: "Flags",

        // Friends extras
        .friendsSearchEmptyMessage: "Try another name or username.",
        .friendsDirectoryEmptyTitle: "No friends or groups yet",
        .friendsDirectoryEmptyMessage: "Search by name or username, scan QR, or create a group.",
        .friendsGenericError: "Something's off.",
        .friendsRequestNotFoundIncoming: "Friend request not found. Open incoming requests to refresh.",
        .friendsRequestNotFoundOutgoing: "Friend request not found. Open sent requests to refresh.",
        .friendsAddUsernamePlaceholder: "e.g. namtran",
        .friendsAddMessagePlaceholder: "Say hi...",
        .friendsAddUsernameRequired: "Enter a username.",
        .friendsAddSuccess: "Added %@.",
        .friendsJoinCodePlaceholder: "e.g. roommates-q7",
        .friendsJoinCodeRequired: "Enter a group invite code.",
        .friendsJoinSuccess: "Joined %@.",
        .friendsGroupName: "Group name",
        .friendsGroupNamePlaceholder: "e.g. Da Lat trip",
        .friendsGroupDescriptionOptional: "Description (optional)",
        .friendsGroupDescription: "Description",
        .friendsGroupDescriptionPlaceholder: "Short description of the group",
        .friendsGroupAvatar: "Group avatar",
        .friendsGroupPickPhoto: "Choose photo",
        .friendsGroupNoFriendsToInvite: "No friends to invite yet.",
        .friendsImageLoadFailed: "Couldn't load the image.",
        .friendsGroupNameRequired: "Enter a group name.",
        .friendsGroupAvatarUploadFailed: "Couldn't upload the group avatar.",
        .friendsInviteSelectedFailed: "Couldn't invite the selected members.",
        .friendsInvitePartialSkipped: "Some members were skipped.",
        .friendsInviteFailed: "Couldn't invite members.",
        .friendsGroupCreated: "Created group %@.",
        .friendsLeaveGroupConfirmTitle: "Leave group?",
        .friendsDeleteGroupConfirmTitle: "Delete group?",
        .friendsDeleteGroup: "Delete group",
        .friendsDeleteGroupMessage: "This action can't be undone. Are you sure you want to delete this group?",
        .friendsApproveMember: "Approve",
        .friendsGroupQR: "QR code",
        .friendsGroupCode: "Group code",
        .friendsTransferOwnership: "Transfer ownership",
        .friendsGroupCodeCopied: "Group code copied.",
        .friendsMemberOwnerMe: "(Owner, me)",
        .friendsMemberOwner: "(Owner)",
        .friendsMemberMe: "(me)",
        .friendsMemberApproved: "Approved %@",
        .friendsMemberRejected: "Rejected %@",
        .friendsCannotRemoveOwner: "Can't remove the group owner",
        .friendsMemberRemoved: "Removed %@ from the group",
        .friendsTransferBeforeLeave: "Transfer ownership before leaving the group",
        .friendsGroupQRSecureTitle: "Group QR (secure)",
        .friendsGroupQRExpires: "Expires: %@",
        .friendsGroupQRHint: "Friends can scan this code to join the group.",
        .friendsGroupQRTitle: "Group QR",
        .friendsGroupQRGenerating: "Generating QR code...",
        .friendsGroupQRFailed: "Couldn't generate QR code",
        .friendsGroupQRSaveFailed: "Couldn't save the QR image.",
        .friendsGroupQRSaveNoPermission: "No permission to save photos to the library.",
        .friendsGroupQRSaved: "QR code saved to your photo library.",
        .friendsInviteSearchUsers: "Find people",
        .friendsInviteHint: "Enter a username to invite. Only friends can be added successfully.",
        .friendsAddMembersTitle: "Add members",
        .friendsInviteAction: "Invite",
        .friendsInviteUsernamePlaceholder: "Search by username",
        .friendsInviteNotFoundTitle: "Not found",
        .friendsInviteNotFoundMessage: "Try another username, or this person is already in the group.",
        .friendsInviteNeedSelection: "Select at least one person.",
        .friendsInviteSuccessCount: "Invited %d people to the group.",
        .friendsInviteFailedReason: "Couldn't invite (they may not be friends yet).",
        .friendsInviteNone: "No one was invited.",
        .friendsTransferNoMembersTitle: "No members",
        .friendsTransferNoMembersMessage: "You need at least one other member to transfer ownership.",
        .friendsTransferTitle: "Transfer group ownership",
        .friendsTransferAction: "Transfer",
        .friendsEditGroupTitle: "Edit group",
        .friendsGroupRemoveMemberAction: "Remove from group",
        .friendsGroupMemberActionsA11y: "Member actions",

        // Auth extras
        .authLoginTagline: "Click moments, Split bills, Keep relations.",
        .authCreateAccountTitle: "Create Account",
        .authRegisterSubtitle: "Join your friends on Splick",
        .authPasswordsMismatch: "Passwords don't match",
        .authDisplayNameRequired: "Name is required",
        .authDisplayNameTooLong: "Name is too long",
        .authVerifyIdentifierFailed: "Couldn't verify your email or phone number.",
        .authGoogleNotConfigured: "Google Sign-In is not configured.",
        .authAppleUnavailable: "Sign in with Apple is not available.",
        .authIdentifierRequired: "Email or phone number is required",
        .authPasswordRequired: "Password is required",
        .authOtpSentEmail: "Verification code sent. Check your email.",
        .authOtpSentPhone: "Verification code sent to your phone.",
        .authSendCodeFailedRetry: "Couldn't send the code. Try again?",
        .authOtpEmailCodeRequired: "Enter the 6-digit code from your email",
        .authResetSendFailed: "Couldn't send reset code",
        .authResetVerifyFailed: "Couldn't verify code",
        .authResetFailed: "Couldn't reset password",
        .authPasswordRequirementsIntro: "Your password must meet all of the following:",
        .authPasswordRequirementsTitle: "Use a strong password",
        .authPasswordRuleMinLength: "At least %d characters",
        .authPasswordRuleUppercase: "One uppercase letter (A–Z)",
        .authPasswordRuleLowercase: "One lowercase letter (a–z)",
        .authPasswordRuleDigit: "One number (0–9)",
        .authPasswordRuleSpecial: "One special character (!@#$%…)",
        .feedShareFallbackCaption: "Check out this post on Splick",
        .stickersGifPreviewA11y: "GIF preview",
        .profileAvatarLoadFailed: "Couldn't load the selected photo.",
        .profileEditNothingEntered: "Enter a display name or choose a photo.",
        .profileEditNothingToUpdate: "Nothing to update.",

        // Stickers extras
        .stickersSplickCustom: "Splick Custom",
        .stickersGroupCustomEmpty: "This group has no custom stickers yet.",
        .stickersSearchFailedHint: "Try another keyword or check KLIPY_API_KEY.",
        .stickersAddEmojiTitle: "Add Emoji",
        .stickersEmojiCropTitle: "Crop emoji area",
        .stickersEmojiCropHint: "Drag to align, pinch to zoom.",
        .stickersEmojiRotateLeft: "Rotate left",
        .stickersEmojiRotateRight: "Rotate right",
        .stickersEmojiFlip: "Flip",
        .stickersEmojiName: "Emoji name",
        .stickersEmojiNameHint: "Spaces become _ when saved.",
        .stickersEmojiNamePreview: "Will be saved as :%@:",
        .stickersUpload: "Upload",
        .stickersYourEmoji: "Your emoji",
        .stickersUploadYourEmoji: "Upload your emoji",
        .stickersPersonalEmojiHint: "Emojis you upload are personal and available across chats.",
        .stickersPersonalEmojiEmpty: "You don't have any personal emoji yet.",
        .stickersEmojiNotFound: "No matching emoji found.",
        .stickersEmojiSearch: "Search emoji",
        .stickersEmojiSourceA11y: "Emoji source",
        .stickersUploadUnavailable: "Emoji upload isn't available yet.",
        .stickersOpenImageFailed: "Couldn't open the selected image.",
        .stickersGifDoubleTapSend: "Double tap to send",

        // Expense create / categories
        .expenseCreateFailed: "Failed to create expense",
        .expenseDescriptionRequired: "Description is required",
        .expenseAmountInvalid: "Enter a valid amount",
        .expenseNeedParticipant: "Select at least one participant",
        .expenseCategoryFood: "Food & Drinks",
        .expenseCategoryTransport: "Transport",
        .expenseCategoryHousing: "Housing",
        .expenseCategoryEntertainment: "Entertainment",
        .expenseCategoryShopping: "Shopping",
        .expenseCategoryUtilities: "Utilities",
        .expenseCategoryTravel: "Travel",
        .expenseCategoryGeneral: "General",

        // Onboarding / widget
        .onboardingSlide1Title: "Click to capture the moments",
        .onboardingSlide2Title: "Split the bills together",
        .onboardingSlide3Title: "Keep friends relationship",
        .onboardingCtaHint: "Tap or swipe to get started",
        .onboardingTagline: "Click moments, Split bills, Keep relationship",
        .widgetNoMessages: "No messages",
        .widgetMessagePhoto: "📷 Photo",
    ]
}
