enum StringsFeatureVi {
    static let values: [L10nKey: String] = [
        // Feed
        .feedTitle: "Tin",
        .feedLoading: "Đang tải bảng tin...",
        .feedEmptyTitle: "Chưa có bài đăng",
        .feedEmptyMessage: "Chia sẻ khoảnh khắc với bạn bè để bắt đầu!",
        .feedEmptyAction: "Chụp ảnh",
        .feedEndReachedTitle: "Hết tin rồi đó",
        .feedEndReachedMessage: "Bạn đã lướt sạch feed. Đi đời thật một chút — tin mới sẽ chờ bạn quay lại.",
        .feedPhotoAlbumAccessibility: "Album ảnh",
        .feedAlbumTitle: "Album",
        .feedAlbumLoading: "Đang tải album...",
        .feedAlbumEmptyTitle: "Chưa có ảnh",
        .feedAlbumEmptyMessage: "Ảnh từ bài đăng của bạn sẽ hiện ở đây.",

        // Streak
        .feedStreakTitle: "Chuỗi",
        .feedStreakCurrentStreak: "Chuỗi hiện tại",
        .feedStreakDays: "ngày liên tiếp",
        .feedStreakEmptyDay: "Không có ảnh",
        .feedStreakNoPhotosToday: "Đăng ảnh hôm nay để giữ chuỗi!",
        .feedStreakQuoteZero: "Chuỗi 0 ngày — máy ảnh đang xin nghỉ phép có lương.",
        .feedStreakQuoteGrowing: "Mới lót đường thôi, đừng để chiếc tủ lạnh vượt streak bạn.",
        .feedStreakQuoteSolid: "Streak ngon lành — thuật toán chưa kịp hiểu bạn đang làm gì.",
        .feedStreakQuoteLegend: "Huyền thoại thật sự. NASA gọi mà bạn bận chụp ảnh.",
        .feedStreakLoading: "Đang tải chuỗi...",
        .feedStreakError: "Không tải được chuỗi",
        .feedFilterTitle: "Bộ lọc",
        .feedFilterNoFriends: "Bạn chưa có bạn bè",
        .feedFilterFriendsNotFound: "Không tìm thấy bạn bè",
        .feedFilterByFriends: "Lọc theo bạn bè",
        .feedFilterNoGroups: "Bạn chưa tham gia nhóm nào",
        .feedFilterByGroups: "Lọc theo nhóm",
        .feedPostCommentsTitle: "Bình luận",
        .feedPostCommentsHeader: "Bình luận",
        .feedPostCommentsEmpty: "Chưa có bình luận. Hãy là người đầu tiên!",
        .feedPostCommentsLoadMore: "Xem thêm bình luận",
        .feedPostViewAllComments: "Xem tất cả %d bình luận",
        .feedPostWriteComment: "Viết bình luận...",
        .feedCompanionsEmpty: "Không tìm thấy người đi cùng",
        .feedCompanionsTitle: "Đang ở cùng (%d)",
        .feedCompanionsSummary: "Đang ở cùng %@",
        .feedCheckInAt: "Check-in tại %@",
        .feedViewersTitle: "Đã xem (%d)",
        .feedBillSplitTitle: "Chia bill",
        .feedBillRemindAll: "Nhắc tất cả (%d)",
        .feedBillRemindTitle: "Nhắc nhở",
        .feedBillRemindAllTitle: "Nhắc tất cả",
        .feedBillRemindAllMessage: "Gửi nhắc tới %d người chưa thanh toán",
        .feedBillPaidAccessibility: "Đã thanh toán",
        .feedBillRemindUserAccessibility: "Nhắc %@",
        .feedBillPaidCount: "%d/%d đã trả",
        .feedBillSettled: "Đã tất toán",
        .feedBillReminderCooldown: "Vừa gửi nhắc nhở gần đây. Vui lòng đợi 15 phút trước khi gửi lại.",
        .feedBillReminderAlreadyPaid: "Người này đã thanh toán phần của họ.",
        .feedBillReminderNoTargets: "Hiện không có ai phù hợp để nhắc nhở.",
        .feedBillReminderRateLimited: "Đã đạt giới hạn nhắc nhở trong ngày. Hãy thử lại vào ngày mai.",
        .feedBillReminderSentSingle: "Đã gửi nhắc nhở tới %@",
        .feedBillReminderSentMultiple: "Đã gửi nhắc nhở tới %d/%d người",
        .splickBotProfileTagline: "Chuyên gia thu nợ · Chứng nhận alley neon",
        .splickBotProfileBio: "10 năm kinh nghiệm đòi bạn bè trả tiền cafe, trà sữa và bill cuối tuần. Phương châm: \"Nợ thì trả, không trả thì @tag liên tục.\" Đã thu hồi 99,9% các khoản dưới 50k — 50k còn lại đang ngồi đàm phán với ly trà sữa.",
        .splickBotStatReminders: "Lần nhắc nợ",
        .splickBotStatRecovery: "Tỷ lệ thu hồi",
        .splickBotStatExperience: "Kinh nghiệm",
        .splickBotStatRecoveryValue: "99.9%",
        .splickBotStatExperienceValue: "10 năm",
        .feedReactionsTitle: "Cảm xúc",
        .feedReactionsCount: "%d cảm xúc",
        .feedReactionsMore: "+%d người bày tỏ cảm xúc khác",
        .feedCreateTitle: "Đăng bài",
        .feedCreatePosting: "Đang đăng...",
        .feedCreateAddMedia: "Thêm media",
        .feedCreateMediaLimit: "Tối đa 5 ảnh và 3 video",
        .feedCreateCaption: "Caption",
        .feedCreateTagFriends: "Gắn thẻ bạn bè",
        .feedCreateTagFriendsHint: "Gắn thẻ bạn bè để chia bill cùng người khác.",
        .feedCreateFriendsNotFound: "Không tìm thấy bạn bè",
        .feedCreateLocation: "Vị trí",
        .feedCreateTotalAmount: "Tổng tiền",
        .feedCreateCurrencySymbol: "đ",
        .feedMentionSuggestions: "Gợi ý bạn bè",
        .feedEmojiPickerTitle: "Chọn emoji",
        .feedEmojiPickerQuickBarTitle: "Thanh nhanh",
        .feedEmojiPickerQuickBarHint: "Chạm một ô rồi chọn emoji bên dưới để gán. Chạm emoji trực tiếp để gửi cảm xúc.",
        .feedEmojiPickerAllTitle: "Tất cả emoji",
        .feedEmojiPickerHint: "Bàn phím emoji của iPhone sẽ hiện khi bạn chạm vào ô trên.",
        .feedEmojiPickerCustomTabTitle: "Của nhóm",
        .feedCustomEmojiAddAction: "Thêm",
        .feedCustomEmojiUploadTitle: "Emoji nhóm",
        .feedCustomEmojiUploadSectionTitle: "Tải emoji mới",
        .feedCustomEmojiChoosePhoto: "Chọn ảnh",
        .feedCustomEmojiShortcodePlaceholder: "Tên emoji (vd: cho_vay)",
        .feedCustomEmojiUploadAction: "Tải emoji lên",
        .feedCustomEmojiExistingTitle: "Emoji của nhóm",
        .feedCustomEmojiEmpty: "Chưa có emoji riêng. Hãy tải lên cho nhóm của bạn.",
        .feedProfileMessage: "Nhắn tin",
        .feedProfileAddFriend: "Thêm bạn",
        .profileLoading: "Đang tải hồ sơ…",
        .profileRetry: "Thử lại",
        .profileStatFriends: "Bạn bè",
        .profileStatPosts: "Bài viết",
        .profileStatGroups: "Nhóm",
        .profilePaymentManage: "Nhận tiền",
        .profilePaymentTitle: "QR thanh toán",
        .profilePaymentQrSection: "Ảnh mã QR",
        .profilePaymentBankSection: "Tài khoản ngân hàng",
        .profilePaymentAccountName: "Tên chủ tài khoản",
        .profilePaymentAccountNumber: "Số tài khoản",
        .profilePaymentBankName: "Ngân hàng",
        .profilePaymentSave: "Lưu",
        .profilePaymentDelete: "Xóa thông tin thanh toán",
        .profilePaymentDeleteConfirm: "Xóa mã QR và thông tin ngân hàng?",
        .profilePaymentUploadQr: "Tải ảnh QR lên",
        .profilePaymentFriendSection: "Thông tin nhận tiền",
        .profilePaymentEmptySelf: "Chưa có thông tin nhận tiền. Nhấn Nhận tiền để thêm QR hoặc tài khoản ngân hàng.",
        .profilePaymentEmptyFriend: "Bạn bè này chưa thiết lập thông tin nhận tiền.",

        // Friends
        .friendsTitle: "Bạn bè",
        .friendsTabFriends: "Bạn bè",
        .friendsTabGroups: "Nhóm",
        .friendsIncomingRequests: "Lời mời kết bạn (%d)",
        .friendsOutgoingRequests: "Lời mời đã gửi (%d)",
        .friendsOutgoingRequestsPlain: "Lời mời đã gửi",
        .friendsBlockedUsers: "Người bị chặn",
        .friendsAddFriendTitle: "Thêm bạn",
        .friendsUsername: "Tên người dùng",
        .friendsMessageOptional: "Lời nhắn (tuỳ chọn)",
        .friendsJoinGroupTitle: "Tham gia nhóm",
        .friendsGroupInviteCode: "Mã mời nhóm",
        .friendsJoinGroupAction: "Tham gia nhóm",
        .friendsScanGroupQR: "Quét mã QR",
        .friendsRelationFriend: "Bạn bè",
        .friendsRelationSent: "Đã gửi",
        .friendsAccept: "Chấp nhận",
        .friendsAddFriendAction: "Kết bạn",
        .friendsReject: "Từ chối",
        .friendsCancel: "Hủy",
        .friendsClose: "Đóng",
        .friendsMyQRTitle: "Mã QR của tôi",
        .friendsMyQRHint: "Bạn bè quét mã này để gửi lời mời kết bạn trên Splick.",
        .friendsMyQRRefresh: "Làm mới mã",
        .friendsMyQRShare: "Chia sẻ mã",
        .friendsMyQRGenerating: "Đang tạo mã QR...",
        .friendsMyQRFailed: "Không thể tạo mã QR",
        .friendsMyQRVersion: "Phiên bản mã %d",
        .friendsMyQRPreviewTitle: "Mã QR của tôi",
        .friendsMyQRPreviewHint: "Chạm để phóng to hoặc chia sẻ",
        .friendsScanQRAddFriend: "Quét mã QR",
        .friendsScanQRJoinGroup: "Quét mã nhóm",
        .friendsScanSimulatorHint: "Trên Simulator không có camera. Dán mã QR bên dưới hoặc dùng máy thật để quét.",
        .friendsScanManualHint: "Hoặc dán mã thủ công",
        .friendsScanUseCode: "Dùng mã này",
        .friendsIncomingTitle: "Lời mời kết bạn",
        .friendsIncomingLoading: "Đang tải lời mời...",
        .friendsIncomingEmptyTitle: "Không có lời mời",
        .friendsIncomingEmptyMessage: "Khi ai đó gửi lời mời kết bạn, bạn sẽ thấy ở đây.",
        .friendsOutgoingTitle: "Lời mời đã gửi",
        .friendsOutgoingLoading: "Đang tải lời mời đã gửi...",
        .friendsOutgoingEmptyTitle: "Chưa gửi lời mời",
        .friendsOutgoingEmptyMessage: "Lời mời bạn gửi sẽ hiện ở đây cho đến khi được chấp nhận hoặc bạn huỷ.",
        .friendsBlockedTitle: "Người bị chặn",
        .friendsBlockedLoading: "Đang tải danh sách chặn...",
        .friendsBlockedEmptyTitle: "Chưa chặn ai",
        .friendsBlockedEmptyMessage: "Người bạn chặn sẽ hiện ở đây. Bạn có thể bỏ chặn bất cứ lúc nào.",
        .friendsUnblock: "Bỏ chặn",
        .friendsSetNickname: "Đặt biệt danh",
        .friendsRemoveFriend: "Xóa bạn",
        .friendsBlockUser: "Chặn người dùng",
        .friendsNicknameTitle: "Biệt danh",
        .friendsNicknamePlaceholder: "Biệt danh (chỉ bạn thấy)",
        .friendsRemoveFriendConfirmTitle: "Xóa bạn?",
        .friendsRemoveFriendConfirmAction: "Xóa bạn",
        .friendsBlockConfirmTitle: "Chặn người dùng này?",
        .friendsBlockConfirmAction: "Chặn",
        .friendsGroupPending: "Chờ duyệt (%d)",
        .friendsGroupMembers: "Thành viên (%d)",
        .friendsGroupMemberCount: "%d thành viên",
        .friendsGroupInviteCodeLabel: "Mã mời: %@",

        // Expense
        .expenseTitle: "Chi tiêu",
        .expenseLoading: "Đang tải chi tiêu...",
        .expenseEmptyTitle: "Chưa có chi tiêu",
        .expenseEmptyMessage: "Tạo khoản chi chung đầu tiên để bắt đầu chia bill.",
        .expenseEmptyAction: "Thêm chi tiêu",
        .expenseFilteredEmptyTitle: "Không có chi tiêu phù hợp",
        .expenseFilteredEmptyMessage: "Thử đổi bộ lọc hoặc xoá bộ lọc.",
        .expenseYouAreOwed: "Bạn được nợ",
        .expenseYouOwe: "Bạn nợ",
        .expensePaidBy: "Trả bởi %@",
        .expenseCreatedAt: "Tạo %@",
        .expenseSettledAt: "Đã thanh toán %@",
        .expenseStatusPending: "Chờ",
        .expenseStatusPartial: "Một phần",
        .expenseStatusSettled: "Đã xong",
        .expenseFilterSearchCaption: "Tìm theo mô tả",
        .expenseFilterMore: "Thêm bộ lọc",
        .expenseFilterClear: "Xoá bộ lọc",
        .expenseFilterStatus: "Trạng thái",
        .expenseFilterUser: "Người dùng",
        .expenseFilterSearchUser: "Tìm người dùng",
        .expenseFilterNoUsers: "Không tìm thấy người dùng",
        .expenseFilterDateRange: "Khoảng thời gian",
        .expenseFilterFrom: "Từ",
        .expenseFilterTo: "Đến",
        .expenseFilterAnyTime: "Bất kỳ lúc nào",
        .expenseFilterFromDate: "Từ ngày",
        .expenseFilterToDate: "Đến ngày",
        .expenseDebtAll: "Tất cả",
        .expenseDebtOwe: "Tôi nợ",
        .expenseDebtOwed: "Nợ tôi",
        .expenseCreateTitle: "Chi tiêu mới",
        .expenseCreateHowMuch: "Bao nhiêu?",
        .expenseCreateDescription: "Chi cho việc gì?",
        .expenseCreateCategory: "Danh mục",
        .expenseCreateSplitType: "Cách chia",
        .expenseCreateAction: "Tạo chi tiêu",
        .expenseSplitEqual: "Chia đều",
        .expenseSplitExact: "Số tiền cố định",
        .expenseSplitPercentage: "Theo phần trăm",

        // Notification
        .notificationTitle: "Thông báo",
        .notificationLoading: "Đang tải thông báo...",
        .notificationEmptyTitle: "Không có thông báo",
        .notificationEmptyMessage: "Bạn đã xem hết! Thông báo mới sẽ hiện ở đây.",
        .notificationReadAll: "Đọc tất cả",
        .notificationInboxTitle: "Hộp thư",
        .notificationInboxEmpty: "Chưa có thông báo",
        .notificationBellAccessibility: "Thông báo",

        // Tab
        .tabMessages: "Tin nhắn",

        // Messaging
        .messagingTitle: "Tin nhắn",
        .messagingLoading: "Đang tải tin nhắn...",
        .messagingEmptyTitle: "Chưa có cuộc trò chuyện",
        .messagingEmptyMessage: "Tìm bạn bè ở trên để bắt đầu nhắn tin.",
        .messagingNewConversation: "Tin nhắn mới",
        .messagingInputPlaceholder: "Nhắn tin...",
        .messagingSend: "Gửi",
        .messagingYou: "Bạn",
        .messagingChatLoading: "Đang tải tin nhắn...",
        .messagingChatEmptyTitle: "Chưa có tin nhắn",
        .messagingChatEmptyMessage: "Gửi lời chào nào!",
        .messagingSelectFriend: "Chọn bạn bè để nhắn tin",
        .messagingSearchPlaceholder: "Tìm tin nhắn và người dùng",
        .messagingSearchLoading: "Đang tìm...",
        .messagingSearchEmptyTitle: "Không tìm thấy kết quả",
        .messagingSearchEmptyMessage: "Thử tên, username hoặc nội dung tin nhắn khác.",
        .messagingStartConversationError: "Không thể bắt đầu cuộc trò chuyện",
        .messagingBellAccessibility: "Thông báo",
        .messagingMessageButton: "Nhắn tin",

        // Common extras
        .commonClose: "Đóng",
        .commonOK: "OK",
        .commonCancel: "Hủy",
        .commonSave: "Lưu",
        .commonError: "Lỗi",
        .commonSuccess: "Thành công",
        .commonOr: "hoặc",
    ]
}
