import Foundation
import SplickDomain

struct SystemEmojiEntry: Identifiable {
    let emoji: String
    let keywords: [String]

    var id: String { emoji }
}

enum EmojiCatalog {
    static let systemEntries: [SystemEmojiEntry] = [
        .init(emoji: "❤️", keywords: ["heart", "love", "tim", "yeu"]),
        .init(emoji: "🧡", keywords: ["orange heart", "heart", "cam", "tim"]),
        .init(emoji: "💛", keywords: ["yellow heart", "heart", "vang", "tim"]),
        .init(emoji: "💚", keywords: ["green heart", "heart", "xanh", "tim"]),
        .init(emoji: "💙", keywords: ["blue heart", "heart", "duong", "tim"]),
        .init(emoji: "💜", keywords: ["purple heart", "heart", "tim", "tim"]),
        .init(emoji: "🖤", keywords: ["black heart", "heart", "den", "tim"]),
        .init(emoji: "🤍", keywords: ["white heart", "heart", "trang", "tim"]),
        .init(emoji: "😂", keywords: ["laugh", "funny", "haha", "cuoi"]),
        .init(emoji: "🤣", keywords: ["rolling laugh", "funny", "haha", "cuoi"]),
        .init(emoji: "😊", keywords: ["smile", "happy", "cuoi", "vui"]),
        .init(emoji: "😍", keywords: ["love eyes", "heart eyes", "me", "thich"]),
        .init(emoji: "🥰", keywords: ["love", "cute", "de thuong", "om tim"]),
        .init(emoji: "😘", keywords: ["kiss", "hon"]),
        .init(emoji: "😎", keywords: ["cool", "ngau", "kinh"]),
        .init(emoji: "🤩", keywords: ["star eyes", "wow", "sao", "thich"]),
        .init(emoji: "😮", keywords: ["surprised", "wow", "ngo ngang"]),
        .init(emoji: "😲", keywords: ["shocked", "wow", "bat ngo"]),
        .init(emoji: "😢", keywords: ["sad", "cry", "buon"]),
        .init(emoji: "😭", keywords: ["cry", "khoc", "buon"]),
        .init(emoji: "😡", keywords: ["angry", "mad", "gian"]),
        .init(emoji: "🤬", keywords: ["angry", "swear", "gian"]),
        .init(emoji: "👏", keywords: ["clap", "vo tay"]),
        .init(emoji: "🙌", keywords: ["raise hands", "yay", "tung ho"]),
        .init(emoji: "🔥", keywords: ["fire", "hot", "lua", "chat"]),
        .init(emoji: "💯", keywords: ["100", "perfect", "chuan"]),
        .init(emoji: "✨", keywords: ["sparkles", "shine", "lung linh"]),
        .init(emoji: "🎉", keywords: ["party", "celebrate", "chuc mung"]),
        .init(emoji: "👍", keywords: ["thumbs up", "like", "ok"]),
        .init(emoji: "👎", keywords: ["thumbs down", "dislike", "khong"]),
        .init(emoji: "🙏", keywords: ["pray", "thanks", "cam on"]),
        .init(emoji: "💪", keywords: ["strong", "muscle", "manh"]),
        .init(emoji: "😴", keywords: ["sleep", "tired", "ngu"]),
        .init(emoji: "🤔", keywords: ["thinking", "hmm", "nghi"]),
        .init(emoji: "😬", keywords: ["awkward", "grimace", "ngai"]),
        .init(emoji: "🥳", keywords: ["party", "birthday", "an mung"]),
        .init(emoji: "🤯", keywords: ["mind blown", "shock", "soc"]),
        .init(emoji: "😱", keywords: ["scream", "fear", "so"]),
        .init(emoji: "💀", keywords: ["dead", "skull", "hai huoc"]),
        .init(emoji: "🫶", keywords: ["heart hands", "love", "tim tay"]),
        .init(emoji: "😀", keywords: ["grinning", "smile", "happy", "cuoi"]),
        .init(emoji: "😁", keywords: ["beaming", "smile", "happy", "rang ro"]),
        .init(emoji: "😅", keywords: ["sweat smile", "relief", "hehe", "toat mo hoi"]),
        .init(emoji: "😉", keywords: ["wink", "nhay mat"]),
        .init(emoji: "🙃", keywords: ["upside down", "playful", "lon nguoc"]),
        .init(emoji: "😋", keywords: ["yummy", "delicious", "ngon"]),
        .init(emoji: "😜", keywords: ["playful", "tongue", "dua", "treu"]),
        .init(emoji: "🥺", keywords: ["pleading", "cute", "xin xo", "nai ni"]),
        .init(emoji: "😇", keywords: ["angel", "halo", "thien than"]),
        .init(emoji: "🤗", keywords: ["hug", "om"]),
        .init(emoji: "🫡", keywords: ["salute", "chao"]),
        .init(emoji: "🤭", keywords: ["giggle", "oops", "cuoi che mieng"]),
        .init(emoji: "🫠", keywords: ["melting", "tan chay"]),
        .init(emoji: "🥲", keywords: ["tear smile", "cam dong", "vua cuoi vua khoc"]),
        .init(emoji: "😤", keywords: ["triumph", "huff", "phan khich", "tuc"]),
        .init(emoji: "🥱", keywords: ["yawn", "sleepy", "ngap"]),
        .init(emoji: "🤐", keywords: ["zipper mouth", "secret", "im lang"]),
        .init(emoji: "🥴", keywords: ["woozy", "dizzy", "xay xam"]),
        .init(emoji: "🤢", keywords: ["sick", "nausea", "buon non"]),
        .init(emoji: "🤮", keywords: ["vomit", "oi"]),
        .init(emoji: "🤒", keywords: ["sick", "thermometer", "om"]),
        .init(emoji: "🤕", keywords: ["bandage", "injured", "bi thuong"]),
        .init(emoji: "🥵", keywords: ["hot face", "nong"]),
        .init(emoji: "🥶", keywords: ["cold face", "lanh"]),
        .init(emoji: "😈", keywords: ["devil", "evil", "quy"]),
        .init(emoji: "👻", keywords: ["ghost", "ma"]),
        .init(emoji: "🤡", keywords: ["clown", "he"]),
        .init(emoji: "💩", keywords: ["poop", "shit", "phan"]),
        .init(emoji: "🙈", keywords: ["see no evil", "monkey", "che mat"]),
        .init(emoji: "🙉", keywords: ["hear no evil", "monkey", "che tai"]),
        .init(emoji: "🙊", keywords: ["speak no evil", "monkey", "che mieng"]),
        .init(emoji: "👋", keywords: ["wave", "hello", "xin chao"]),
        .init(emoji: "🤝", keywords: ["handshake", "deal", "bat tay"]),
        .init(emoji: "👌", keywords: ["ok hand", "ok"]),
        .init(emoji: "✌️", keywords: ["peace", "victory", "hoa binh"]),
        .init(emoji: "🤞", keywords: ["crossed fingers", "hope", "may man"]),
        .init(emoji: "🤟", keywords: ["love you", "rock", "yeu"]),
        .init(emoji: "🫰", keywords: ["finger heart", "heart", "tim"]),
        .init(emoji: "👈", keywords: ["point left", "trai"]),
        .init(emoji: "👉", keywords: ["point right", "phai"]),
        .init(emoji: "👆", keywords: ["point up", "len"]),
        .init(emoji: "👇", keywords: ["point down", "xuong"]),
        .init(emoji: "💅", keywords: ["nail polish", "slay", "son mong"]),
        .init(emoji: "🫵", keywords: ["point at you", "ban"]),
        .init(emoji: "🤲", keywords: ["palms up", "offer", "ban tay"]),
        .init(emoji: "🙋", keywords: ["raise hand", "gio tay"]),
        .init(emoji: "🙆", keywords: ["ok gesture", "dong y"]),
        .init(emoji: "🙅", keywords: ["no gesture", "khong"]),
        .init(emoji: "💃", keywords: ["dance", "nhay"]),
        .init(emoji: "🕺", keywords: ["man dance", "nhay"]),
        .init(emoji: "🏃", keywords: ["run", "chay"]),
        .init(emoji: "🚶", keywords: ["walk", "di bo"]),
        .init(emoji: "🧎", keywords: ["kneel", "quy"]),
        .init(emoji: "🎈", keywords: ["balloon", "bong bay"]),
        .init(emoji: "🎁", keywords: ["gift", "present", "qua tang"]),
        .init(emoji: "🪩", keywords: ["disco ball", "party", "vu truong"]),
        .init(emoji: "🎊", keywords: ["confetti", "celebrate", "chuc mung"]),
        .init(emoji: "🏆", keywords: ["trophy", "cup", "giai"]),
        .init(emoji: "🥇", keywords: ["gold medal", "first", "huy chuong vang"]),
        .init(emoji: "🌈", keywords: ["rainbow", "cau vong"]),
        .init(emoji: "☀️", keywords: ["sun", "nang", "mat troi"]),
        .init(emoji: "⛅", keywords: ["cloud sun", "weather", "may"]),
        .init(emoji: "🌧️", keywords: ["rain", "mua"]),
        .init(emoji: "⛈️", keywords: ["storm", "bao", "sam set"]),
        .init(emoji: "❄️", keywords: ["snow", "tuyet"]),
        .init(emoji: "☕", keywords: ["coffee", "ca phe"]),
        .init(emoji: "🍵", keywords: ["tea", "tra"]),
        .init(emoji: "🍕", keywords: ["pizza"]),
        .init(emoji: "🍔", keywords: ["burger", "hamburger"]),
        .init(emoji: "🍟", keywords: ["fries", "khoai tay chien"]),
        .init(emoji: "🍜", keywords: ["noodles", "mi"]),
        .init(emoji: "🍣", keywords: ["sushi"]),
        .init(emoji: "🍩", keywords: ["donut", "banh"]),
        .init(emoji: "🍪", keywords: ["cookie", "banh quy"]),
        .init(emoji: "🍰", keywords: ["cake", "banh ngot"]),
        .init(emoji: "🎂", keywords: ["birthday cake", "sinh nhat"]),
        .init(emoji: "🍓", keywords: ["strawberry", "dau tay"]),
        .init(emoji: "🍉", keywords: ["watermelon", "dua hau"]),
        .init(emoji: "🍇", keywords: ["grapes", "nho"]),
        .init(emoji: "🍎", keywords: ["apple", "tao"]),
        .init(emoji: "🥑", keywords: ["avocado", "bo"]),
        .init(emoji: "🌶️", keywords: ["chili", "spicy", "ot"]),
        .init(emoji: "🍀", keywords: ["clover", "luck", "co 4 la"]),
        .init(emoji: "🌹", keywords: ["rose", "hoa hong"]),
        .init(emoji: "🌻", keywords: ["sunflower", "hoa huong duong"]),
        .init(emoji: "🌴", keywords: ["palm tree", "dua", "cay"]),
        .init(emoji: "🐶", keywords: ["dog", "cho"]),
        .init(emoji: "🐱", keywords: ["cat", "meo"]),
        .init(emoji: "🐼", keywords: ["panda", "gau truc"]),
        .init(emoji: "🦄", keywords: ["unicorn", "ky lan"]),
        .init(emoji: "🐸", keywords: ["frog", "ech"]),
        .init(emoji: "🐥", keywords: ["chick", "ga con"]),
        .init(emoji: "🦋", keywords: ["butterfly", "buom"]),
        .init(emoji: "🐝", keywords: ["bee", "ong"]),
        .init(emoji: "🚀", keywords: ["rocket", "ten lua"]),
        .init(emoji: "🎮", keywords: ["game", "gaming", "choi game"]),
        .init(emoji: "🎧", keywords: ["headphones", "music", "tai nghe"]),
        .init(emoji: "📸", keywords: ["camera", "photo", "chup anh"]),
        .init(emoji: "💡", keywords: ["idea", "light", "y tuong"]),
        .init(emoji: "📚", keywords: ["books", "study", "sach"]),
        .init(emoji: "😃", keywords: ["smile", "happy", "cuoi", "vui"]),
        .init(emoji: "😄", keywords: ["big smile", "happy", "cuoi"]),
        .init(emoji: "🙂", keywords: ["slight smile", "smile", "mim cuoi"]),
        .init(emoji: "😌", keywords: ["relieved", "calm", "nhe nhom"]),
        .init(emoji: "😏", keywords: ["smirk", "tease", "nhech"]),
        .init(emoji: "😔", keywords: ["sad", "thinking", "buon"]),
        .init(emoji: "😞", keywords: ["disappointed", "buon", "that vong"]),
        .init(emoji: "😟", keywords: ["worried", "lo lang"]),
        .init(emoji: "😕", keywords: ["confused", "boi roi"]),
        .init(emoji: "🫤", keywords: ["meh", "unsure", "chan"]),
        .init(emoji: "😳", keywords: ["flushed", "embarrassed", "ngai"]),
        .init(emoji: "🥹", keywords: ["teary eyes", "emotional", "xuc dong"]),
        .init(emoji: "🤠", keywords: ["cowboy", "cao boi", "ngau"]),
        .init(emoji: "🥸", keywords: ["disguise", "fake moustache", "cai trang"]),
        .init(emoji: "😶‍🌫️", keywords: ["face in clouds", "lost", "mo ho"]),
        .init(emoji: "🐰", keywords: ["rabbit", "tho"]),
        .init(emoji: "🦊", keywords: ["fox", "cao"]),
        .init(emoji: "🐻", keywords: ["bear", "gau"]),
        .init(emoji: "🐨", keywords: ["koala"]),
        .init(emoji: "🐯", keywords: ["tiger", "ho"]),
        .init(emoji: "🦁", keywords: ["lion", "su tu"]),
        .init(emoji: "🐮", keywords: ["cow", "bo"]),
        .init(emoji: "🐷", keywords: ["pig", "heo"]),
        .init(emoji: "🐵", keywords: ["monkey", "khi"]),
        .init(emoji: "🐔", keywords: ["chicken", "ga"]),
        .init(emoji: "🐧", keywords: ["penguin"]),
        .init(emoji: "🐢", keywords: ["turtle", "rua"]),
        .init(emoji: "🐙", keywords: ["octopus", "bach tuoc"]),
        .init(emoji: "🦀", keywords: ["crab", "cua"]),
        .init(emoji: "🐳", keywords: ["whale", "ca voi"]),
        .init(emoji: "📱", keywords: ["phone", "mobile", "dien thoai"]),
        .init(emoji: "💻", keywords: ["laptop", "computer", "may tinh"]),
        .init(emoji: "⌚", keywords: ["watch", "dong ho"]),
        .init(emoji: "🎥", keywords: ["movie", "video", "quay phim"]),
        .init(emoji: "📷", keywords: ["camera", "may anh"]),
        .init(emoji: "🎤", keywords: ["microphone", "sing", "hat"]),
        .init(emoji: "🎹", keywords: ["piano", "keyboard"]),
        .init(emoji: "🎸", keywords: ["guitar"]),
        .init(emoji: "🥁", keywords: ["drum", "trong"]),
        .init(emoji: "🎨", keywords: ["art", "paint", "ve"]),
        .init(emoji: "🧩", keywords: ["puzzle", "ghep hinh"]),
        .init(emoji: "♟️", keywords: ["chess", "co vua"]),
        .init(emoji: "🛒", keywords: ["cart", "shopping", "gio hang"]),
        .init(emoji: "🔒", keywords: ["lock", "khoa"]),
        .init(emoji: "🔑", keywords: ["key", "chia khoa"]),
        .init(emoji: "🧸", keywords: ["teddy", "gau bong"]),
        .init(emoji: "🍿", keywords: ["popcorn"]),
        .init(emoji: "🍫", keywords: ["chocolate", "socola"]),
        .init(emoji: "🍬", keywords: ["candy", "keo"]),
        .init(emoji: "🍭", keywords: ["lollipop", "keo mut"]),
        .init(emoji: "🥨", keywords: ["pretzel", "banh xoan"]),
        .init(emoji: "🧀", keywords: ["cheese", "pho mai"]),
        .init(emoji: "🍞", keywords: ["bread", "banh mi"]),
        .init(emoji: "🥐", keywords: ["croissant"]),
        .init(emoji: "🥞", keywords: ["pancakes", "banh pancake"]),
        .init(emoji: "🥓", keywords: ["bacon", "thit xong khoi"]),
        .init(emoji: "🍗", keywords: ["chicken leg", "dui ga"]),
        .init(emoji: "🌮", keywords: ["taco"]),
        .init(emoji: "🌯", keywords: ["burrito"]),
        .init(emoji: "🍦", keywords: ["ice cream", "kem"]),
        .init(emoji: "🥤", keywords: ["drink", "nuoc ngot"]),
        .init(emoji: "🧋", keywords: ["bubble tea", "tra sua"]),
        .init(emoji: "🍺", keywords: ["beer", "bia"]),
        .init(emoji: "🥂", keywords: ["cheers", "champagne", "chuc mung"]),
        .init(emoji: "🌙", keywords: ["moon", "trang"]),
        .init(emoji: "⭐", keywords: ["star", "sao"]),
        .init(emoji: "🌟", keywords: ["glowing star", "bright", "toa sang"]),
        .init(emoji: "🌺", keywords: ["hibiscus", "hoa"]),
        .init(emoji: "🌼", keywords: ["blossom", "hoa"]),
        .init(emoji: "🍁", keywords: ["maple leaf", "la phong"]),
        .init(emoji: "🌊", keywords: ["wave", "sea", "song bien"]),
        .init(emoji: "⚽", keywords: ["football", "soccer", "bong da"]),
        .init(emoji: "🏀", keywords: ["basketball", "bong ro"]),
        .init(emoji: "🏈", keywords: ["american football"]),
        .init(emoji: "⚾", keywords: ["baseball"]),
        .init(emoji: "🎾", keywords: ["tennis"]),
        .init(emoji: "🏐", keywords: ["volleyball", "bong chuyen"]),
        .init(emoji: "🏓", keywords: ["ping pong", "bong ban"]),
        .init(emoji: "🥊", keywords: ["boxing", "dam boc"]),
        .init(emoji: "🏋️", keywords: ["weightlifting", "tap ta"]),
        .init(emoji: "🚗", keywords: ["car", "xe hoi"]),
        .init(emoji: "🚕", keywords: ["taxi"]),
        .init(emoji: "🚌", keywords: ["bus", "xe buyt"]),
        .init(emoji: "🚲", keywords: ["bike", "xe dap"]),
        .init(emoji: "✈️", keywords: ["plane", "may bay"]),
        .init(emoji: "🚤", keywords: ["speedboat", "cano"]),
        .init(emoji: "🗺️", keywords: ["map", "ban do"]),
        .init(emoji: "🏝️", keywords: ["island", "dao"]),
        .init(emoji: "🏕️", keywords: ["camping", "cam trai"]),
        .init(emoji: "🏰", keywords: ["castle", "lau dai"]),
        .init(emoji: "✅", keywords: ["check", "done", "hoan tat"]),
        .init(emoji: "❌", keywords: ["cross", "wrong", "sai"]),
        .init(emoji: "⚠️", keywords: ["warning", "canh bao"]),
        .init(emoji: "❓", keywords: ["question", "hoi"]),
        .init(emoji: "❗", keywords: ["exclamation", "alert"]),
        .init(emoji: "💬", keywords: ["chat", "comment", "tin nhan"]),
        .init(emoji: "💤", keywords: ["sleep", "zzz", "buon ngu"]),
        .init(emoji: "🛎️", keywords: ["bell", "service", "chuong"]),
        .init(emoji: "🧠", keywords: ["brain", "smart", "nao"]),
        .init(emoji: "🎯", keywords: ["target", "goal", "muc tieu"]),
    ]
}
