#!/usr/bin/env bash
# Generate Splick.xcodeproj/project.pbxproj from project.yml (XcodeGen).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

LOCAL_YML="$ROOT/project.local.yml"
LOCAL_EXAMPLE="$ROOT/project.local.yml.example"

ensure_local_signing() {
  if [[ -f "$LOCAL_YML" ]]; then
    return
  fi

  local team_id="${DEVELOPMENT_TEAM:-}"
  if [[ -z "$team_id" ]]; then
    team_id="$(
      security find-certificate -c "Apple Development" -p 2>/dev/null \
        | openssl x509 -noout -subject 2>/dev/null \
        | sed -n 's/.*OU=\([^/]*\).*/\1/p' \
        | head -1
    )"
  fi

  if [[ -z "$team_id" ]]; then
    echo "WARN: No project.local.yml and no Apple Development cert found." >&2
    echo "      cp project.local.yml.example project.local.yml and set DEVELOPMENT_TEAM." >&2
    echo "      Device builds require a team; Simulator may still work." >&2
    return
  fi

  cat >"$LOCAL_YML" <<EOF
# Auto-generated by scripts/generate-xcodeproj.sh — do not commit
settings:
  base:
    DEVELOPMENT_TEAM: ${team_id}
EOF
  echo "→ Wrote ${LOCAL_YML} (DEVELOPMENT_TEAM=${team_id})"
}

ensure_local_signing

XCODEGEN_VERSION="${XCODEGEN_VERSION:-2.44.1}"
CACHE_DIR="${XCODEGEN_CACHE_DIR:-$HOME/.cache/splick-xcodegen}"
INSTALL_DIR="$CACHE_DIR/xcodegen-$XCODEGEN_VERSION"
XCODEGEN_BIN="$INSTALL_DIR/xcodegen/bin/xcodegen"

install_xcodegen() {
  if command -v xcodegen >/dev/null 2>&1; then
    echo "→ Using xcodegen from PATH: $(command -v xcodegen)"
    xcodegen generate
    return
  fi

  if [[ ! -x "$XCODEGEN_BIN" ]]; then
    echo "→ Installing XcodeGen $XCODEGEN_VERSION to $INSTALL_DIR"
    mkdir -p "$CACHE_DIR"
    tmp="$(mktemp -d)"
    curl -fsSL "https://github.com/yonaskolb/XcodeGen/releases/download/${XCODEGEN_VERSION}/xcodegen.zip" \
      -o "$tmp/xcodegen.zip"
    unzip -qo "$tmp/xcodegen.zip" -d "$INSTALL_DIR"
    rm -rf "$tmp"
  fi

  echo "→ Generating Splick.xcodeproj"
  "$XCODEGEN_BIN" generate
}

install_xcodegen

if [[ ! -f "$ROOT/Splick.xcodeproj/project.pbxproj" ]]; then
  echo "ERROR: project.pbxproj was not created"
  exit 1
fi

echo "OK: $ROOT/Splick.xcodeproj/project.pbxproj"
