#!/usr/bin/env bash
# Read .env and generate Config/Secrets.xcconfig for Xcode build settings / Info.plist substitution.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"
OUT="$ROOT/Config/Secrets.xcconfig"

python3 - "$ENV_FILE" "$OUT" "$ROOT/.env.example" "$ROOT/project.local.yml" <<'PY'
import sys
from pathlib import Path

env_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])
example_path = Path(sys.argv[3])
local_yml_path = Path(sys.argv[4])

KEYS = (
    "DEVELOPMENT_TEAM",
    "GID_CLIENT_ID",
    "GOOGLE_URL_SCHEME",
    "KLIPY_API_KEY",
)


def parse_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def parse_project_local(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if stripped.startswith("DEVELOPMENT_TEAM:"):
            values["DEVELOPMENT_TEAM"] = stripped.split(":", 1)[1].strip().strip('"').strip("'")
        if stripped.startswith("KLIPY_API_KEY:"):
            values["KLIPY_API_KEY"] = stripped.split(":", 1)[1].strip().strip('"').strip("'")
    return values


def derive_google_url_scheme(client_id: str) -> str:
    suffix = ".apps.googleusercontent.com"
    if client_id.endswith(suffix):
        prefix = client_id[: -len(suffix)]
        if prefix:
            return f"com.googleusercontent.apps.{prefix}"
    return ""


values = parse_dotenv(env_path)
fallback = parse_project_local(local_yml_path)
for key in KEYS:
    if not values.get(key) and fallback.get(key):
        values[key] = fallback[key]

if values.get("GID_CLIENT_ID") and not values.get("GOOGLE_URL_SCHEME"):
    values["GOOGLE_URL_SCHEME"] = derive_google_url_scheme(values["GID_CLIENT_ID"])

out_path.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "// Generated by scripts/load-env.sh — do not edit",
    f"// Source: {env_path.name if env_path.is_file() else 'defaults'}",
]
for key in KEYS:
    lines.append(f"{key} = {values.get(key, '')}")
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

if not env_path.is_file():
    print(f"WARN: {env_path} not found.", file=sys.stderr)
    if example_path.is_file():
        print(f"      cp {example_path.name} .env and fill values.", file=sys.stderr)
    if fallback:
        print("      Using DEVELOPMENT_TEAM / KLIPY_API_KEY from project.local.yml as fallback.", file=sys.stderr)
else:
    print(f"→ Wrote {out_path.relative_to(out_path.parents[1])}")
PY
